algor_dist_array – OptaDOS
algor_dist_array Subroutine
19 statements
Source File
public subroutine algor_dist_array(num_elements, elements_per_node)
Uses
od_comms
od_io
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: num_elements
integer, intent(out), allocatable :: elements_per_node(:)
Calls
Called by
Contents
Source Code
algor_dist_array
Source Code
  subroutine algor_dist_array(num_elements, elements_per_node)
    ! Takes the number of elements in an array, num_elements
    ! Returns an array 0,num_nodes-1 which contains the number of
    ! elements that should be on each node.
    ! AJM based on an idea from JRY
    !======================================================
    use od_comms, only: num_nodes
    use od_io, only: io_error
    implicit none
    integer, intent(in)                :: num_elements
    integer, allocatable, intent(out)  :: elements_per_node(:)
    integer :: loop, ierr
    allocate (elements_per_node(0:num_nodes - 1), stat=ierr)
    if (ierr /= 0) call io_error('Error: Problem allocating elements_per_node in algor_dist_array')
    elements_per_node(:) = num_elements/num_nodes
    if (num_elements < num_nodes) then
      call io_error('Fewer kpoints than nodes. Reduce the number of nodes used!')
    end if
    ! Distribute the remainder
    if (elements_per_node(0)*num_nodes .ne. num_elements) then
      do loop = 0, num_elements - elements_per_node(0)*num_nodes - 1
        elements_per_node(loop) = elements_per_node(loop) + 1
      end do
    end if
  end subroutine algor_dist_array
Call graph
algor_dist_array calls io_error
elec_read_band_gradient calls algor_dist_array, elec_read_optical_mat
elec_read_optical_mat calls algor_dist_array
elec_read_band_curvature calls algor_dist_array
elec_read_band_energy calls algor_dist_array
elec_read_foptical_mat calls algor_dist_array
elec_read_band_energy_ordered calls algor_dist_array
dos_utils_calculate calls elec_read_band_gradient
jdos_utils_calculate calls elec_read_band_gradient, dos_utils_set_efermi
read_ome_bin calls elec_read_optical_mat
dos_utils_calculate_at_e calls elec_read_band_gradient
read_dome_bin calls elec_read_band_gradient
optics_calculate calls elec_read_optical_mat, jdos_utils_calculate, dos_utils_calculate_at_e, dos_utils_set_efermi
get_band_energy calls elec_read_band_energy
optados calls elec_read_band_energy, elec_read_band_energy_ordered, optics_calculate, pdos_calculate, core_calculate, jdos_calculate, dos_calculate
read_fem_bin calls elec_read_foptical_mat
pdos_calculate calls dos_utils_calculate, dos_utils_set_efermi
core_calculate calls dos_utils_calculate, dos_utils_set_efermi
dos_utils_set_efermi calls dos_utils_calculate
jdos_calculate calls jdos_utils_calculate
dos_calculate calls dos_utils_calculate, dos_utils_set_efermi, dos_utils_compute_dos_at_efermi
od2od calls read_ome_bin, read_dome_bin, get_band_energy, read_fem_bin
dos_utils_compute_dos_at_efermi calls dos_utils_calculate_at_e