allocate_jdos – OptaDOS
allocate_jdos Subroutine
11 statements
Source File
public subroutine allocate_jdos(jdos)
Uses
od_electronic
od_parameters
od_io
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), allocatable :: jdos(:,:)
Calls
Called by
Contents
Source Code
allocate_jdos
Source Code
  subroutine allocate_jdos(jdos)
    !===============================================================================
    !===============================================================================
    use od_electronic, only: nspins
    use od_io, only: io_error
    use od_parameters, only: photo
    implicit none
    real(kind=dp), allocatable, intent(out)  :: jdos(:, :)
    integer :: ierr
    allocate (jdos(jdos_nbins, nspins), stat=ierr)
    if (ierr /= 0) call io_error("Error in allocating jdos (jdos_utils)")
    jdos = 0.0_dp
  end subroutine allocate_jdos
Call graph
allocate_jdos calls io_error
calculate_jdos calls allocate_jdos
jdos_utils_calculate calls calculate_jdos
jdos_calculate calls jdos_utils_calculate
optics_calculate calls jdos_utils_calculate
optados calls jdos_calculate, optics_calculate