calculate_jdos – OptaDOS
calculate_jdos Subroutine
96 statements
Source File
public subroutine calculate_jdos(jdos_type, jdos, matrix_weights, weighted_jdos)
Uses
od_algorithms
od_parameters
od_comms
od_dos_utils
od_cell
od_constants
od_electronic
od_io
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: jdos_type
real(kind=dp), intent(out), allocatable :: jdos(:,:)
real(kind=dp), intent(in), optional :: matrix_weights(:,:,:,:,:)
real(kind=dp), intent(inout), optional, allocatable :: weighted_jdos(:,:,:)
Calls
Called by
Contents
Source Code
calculate_jdos
Source Code
  subroutine calculate_jdos(jdos_type, jdos, matrix_weights, weighted_jdos)
    !===============================================================================
    !===============================================================================
    use od_comms, only: my_node_id, on_root
    use od_cell, only: num_kpoints_on_node, kpoint_grid_dim, kpoint_weight,&
         &recip_lattice
    use od_parameters, only: adaptive_smearing, fixed_smearing, iprint, photo, &
         finite_bin_correction, scissor_op, hybrid_linear_grad_tol, hybrid_linear, exclude_bands, num_exclude_bands, &
         photo_slab_max, photo_slab_min
    use od_io, only: io_error, stdout
    use od_electronic, only: band_gradient, nbands, band_energy, nspins, electrons_per_state, &
         & efermi, elec_pdos_read, pdos_weights, pdos_mwab, elec_dealloc_pdos
    use od_dos_utils, only: doslin, doslin_sub_cell_corners
    use od_algorithms, only: gaussian
    use od_constants, only: pi
    implicit none
    integer :: ik, is, ib, idos, jb, i
    integer :: N2, N_geom, ierr
    real(kind=dp) :: dos_temp, cuml, width, adaptive_smearing_temp, mean_height
    real(kind=dp) :: grad(1:3), step(1:3), EV(0:4), sub_cell_length(1:3)
    character(len=1), intent(in)                      :: jdos_type
    real(kind=dp), intent(inout), allocatable, optional :: weighted_jdos(:, :, :)
    real(kind=dp), intent(in), optional                :: matrix_weights(:, :, :, :, :)
    real(kind=dp), intent(out), allocatable :: jdos(:, :)
    logical :: linear, fixed, adaptive, force_adaptive
    linear = .false.
    fixed = .false.
    adaptive = .false.
    select case (jdos_type)
    case ("l")
      linear = .true.
    case ("a")
      adaptive = .true.
    case ("f")
      fixed = .true.
    case default
      call io_error(" ERROR : unknown jdos_type in calculate_jdos ")
    end select
    width = 0.0_dp
    if (linear .or. adaptive) step(:) = 1.0_dp/real(kpoint_grid_dim(:), dp)/2.0_dp
    if (adaptive .or. hybrid_linear) then
      do i = 1, 3
        sub_cell_length(i) = sqrt(recip_lattice(i, 1)**2 + recip_lattice(i, 2)**2 + recip_lattice(i, 3)**2)*step(i)
      end do
      if (photo) then
        mean_height = (photo_slab_min + photo_slab_max)/(2*2)
        sub_cell_length(3) = sqrt(recip_lattice(3,1)**2 + recip_lattice(3,2)**2 + (pi/mean_height)**2)*step(3)
      end if
      adaptive_smearing_temp = adaptive_smearing*sum(sub_cell_length)/3.0_dp
    end if
    if (fixed) width = fixed_smearing
    call allocate_jdos(jdos)
    if (calc_weighted_jdos) then
      N_geom = size(matrix_weights, 5)
      allocate (weighted_jdos(jdos_nbins, nspins, N_geom), stat=ierr)
      if (ierr /= 0) call io_error('Error: calculate_jdos - failed to allocate weighted_jdos')
      weighted_jdos = 0.0_dp
    end if
    if (iprint > 1 .and. on_root) then
      write (stdout, '(1x,a78)') '+------------------------------ Calculate JDOS ------------------------------+'
    end if
    do ik = 1, num_kpoints_on_node(my_node_id)
      if (iprint > 1 .and. on_root) then
        if (mod(real(ik, dp), 10.0_dp) == 0.0_dp) write (stdout, '(1x,a1,a38,i4,a3,i4,1x,a14,3x,a10)') ',', &
             &"Calculating k-point ", ik, " of", num_kpoints_on_node(my_node_id), 'on this node.', "<-- JDOS |"
      end if
      do is = 1, nspins
        occ_states: do ib = 1, nbands
          if (num_exclude_bands > 0) then
            if (any(exclude_bands == ib)) cycle
          end if
          if (band_energy(ib, is, ik) .ge. efermi) cycle occ_states
          unocc_states: do jb = 1, nbands
            if (band_energy(jb, is, ik) .lt. efermi) cycle unocc_states
            if (linear .or. adaptive) grad(:) = band_gradient(jb, :, ik, is) - band_gradient(ib, :, ik, is)
            ! If the band is very flat linear broadening can have problems describing it. In this case, fall back to
            ! adaptive smearing (and take advantage of FBCS if required).
            force_adaptive = .false.
            if (.not. fixed) then
              if (hybrid_linear .and. (hybrid_linear_grad_tol > sqrt(dot_product(grad, grad)))) force_adaptive = .true.
              if (linear .and. .not. force_adaptive) call doslin_sub_cell_corners(grad, step, band_energy(jb, is, ik) -&
  &band_energy(ib, is, ik) + scissor_op, EV)
              if (adaptive .or. force_adaptive) width = sqrt(dot_product(grad, grad))*adaptive_smearing_temp
            end if
            ! Hybrid Adaptive -- This way we don't lose weight at very flat parts of the
            ! band. It's a kind of fudge that we wouldn't need if we had infinitely small bins.
            if (finite_bin_correction .and. (width < delta_bins)) width = delta_bins
            do idos = 1, jdos_nbins
              ! The linear method has a special way to calculate the integrated dos
              ! we have to take account for this here.
              if (linear .and. .not. force_adaptive) then
                dos_temp = doslin(EV(0), EV(1), EV(2), EV(3), EV(4), E(idos), cuml)
              else
                dos_temp=gaussian(band_energy(jb,is,ik)-band_energy(ib,is,ik)+scissor_op,width,E(idos))!&
              end if
              jdos(idos, is) = jdos(idos, is) + dos_temp*electrons_per_state*kpoint_weight(ik)
              ! this will become a loop over final index (polarisation)
              ! Also need to remove kpoints weights.
              if (calc_weighted_jdos) then
                do N2 = 1, N_geom
                  weighted_jdos(idos, is, N2) = weighted_jdos(idos, is, N2) + dos_temp*matrix_weights(ib, jb, ik, is, N2)&
                                               &*electrons_per_state*kpoint_weight(ik)
                end do
              end if
            end do
          end do unocc_states
        end do occ_states
      end do
    end do
    if (iprint > 1 .and. on_root) then
      write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
    end if
  end subroutine calculate_jdos
Call graph
calculate_jdos calls io_error, doslin, gaussian, allocate_jdos, doslin_sub_cell_corners
allocate_jdos calls io_error
doslin_sub_cell_corners calls heap_sort
jdos_utils_calculate calls calculate_jdos
jdos_calculate calls jdos_utils_calculate
optics_calculate calls jdos_utils_calculate
optados calls jdos_calculate, optics_calculate