cell_calc_lattice – OptaDOS
cell_calc_lattice Subroutine
20 statements
Source File
public subroutine cell_calc_lattice()
Uses
od_constants
Arguments
None
Calls
Called by
Contents
Source Code
cell_calc_lattice
Source Code
  subroutine cell_calc_lattice
    !=========================================================================!
    ! Begin with a real lattice. Convert from bohr. Calculate a reciprocal
    ! lattice and the volume of the cell
    !-------------------------------------------------------------------------
    ! Arguments: None
    !-------------------------------------------------------------------------
    ! Parent module variables used: real_lattice, recip_lattice, cell_volume
    !-------------------------------------------------------------------------
    ! Modules used:  See below
    !-------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------
    ! Necessary conditions: None
    !-------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------
    ! Written by Andrew Morris from the LinDOS program             11/10/2010
    !=========================================================================
    use od_constants, only: pi, bohr2ang
    implicit none
    ! THESE ARE IN BOHR, DON'T GET TRIPPED UP AGAIN!
    real_lattice = real_lattice*bohr2ang
    call cell_get_real_lattice
    recip_lattice(1, 1) = real_lattice(2, 2)*real_lattice(3, 3) - &
                          real_lattice(3, 2)*real_lattice(2, 3)
    recip_lattice(2, 1) = real_lattice(2, 3)*real_lattice(3, 1) - &
                          real_lattice(3, 3)*real_lattice(2, 1)
    recip_lattice(3, 1) = real_lattice(2, 1)*real_lattice(3, 2) - &
                          real_lattice(3, 1)*real_lattice(2, 2)
    recip_lattice(1, 2) = real_lattice(3, 2)*real_lattice(1, 3) - &
                          real_lattice(1, 2)*real_lattice(3, 3)
    recip_lattice(2, 2) = real_lattice(3, 3)*real_lattice(1, 1) - &
                          real_lattice(1, 3)*real_lattice(3, 1)
    recip_lattice(3, 2) = real_lattice(3, 1)*real_lattice(1, 2) - &
                          real_lattice(1, 1)*real_lattice(3, 2)
    recip_lattice(1, 3) = real_lattice(1, 2)*real_lattice(2, 3) - &
                          real_lattice(2, 2)*real_lattice(1, 3)
    recip_lattice(2, 3) = real_lattice(1, 3)*real_lattice(2, 1) - &
                          real_lattice(2, 3)*real_lattice(1, 1)
    recip_lattice(3, 3) = real_lattice(1, 1)*real_lattice(2, 2) - &
                          real_lattice(2, 1)*real_lattice(1, 2)
    ! * Calculate cell volume
    cell_volume = real_lattice(1, 1)*recip_lattice(1, 1) + &
                  real_lattice(2, 1)*recip_lattice(1, 2) + &
                  real_lattice(3, 1)*recip_lattice(1, 3)
    if (cell_volume < 0.0_dp) then ! Left handed set
      cell_volume = -cell_volume
    end if
    ! Scale reciprocal lattice by 2*pi/volume
    recip_lattice(:, :) = recip_lattice(:, :)*pi*2.0_dp/cell_volume
  end subroutine cell_calc_lattice
Call graph
cell_calc_lattice calls cell_get_real_lattice
cell_get_real_lattice calls io_file_unit
cell_calc_kpoint_r_cart calls cell_calc_lattice
optados calls cell_calc_lattice