cell_dist – OptaDOS
cell_dist Subroutine
52 statements
Source File
public subroutine cell_dist()
Uses
od_comms
od_io
Arguments
None
Calls
Called by
Contents
Source Code
cell_dist
Source Code
  subroutine cell_dist
    use od_comms, only: comms_bcast, on_root
    use od_io, only: io_error
    implicit none
    integer :: max_sites, ierr
    call comms_bcast(real_lattice(1, 1), 9)
    call comms_bcast(recip_lattice(1, 1), 9)
    call comms_bcast(cell_volume, 1)
    !call comms_bcast(kpoint_r(:,:)
    !call comms_bcast(kpoint_r_cart(:,:)
    !call comms_bcast(kpoint_weight(:)
    call comms_bcast(nkpoints, 1)
    call comms_bcast(kpoint_grid_dim(1), 3)
    !-------------------------------------------------------------------------!
    call comms_bcast(num_atoms, 1)
    call comms_bcast(num_species, 1)
    if (num_atoms > 0) then
      if (.not. on_root) then
        allocate (atoms_species_num(num_species), stat=ierr)
        if (ierr /= 0) call io_error('Error allocating atoms_species_num in cell_dist')
      end if
      call comms_bcast(atoms_species_num(1), num_species)
      max_sites = maxval(atoms_species_num)
      if (.not. on_root) then
        allocate (atoms_pos_frac(3, max_sites, num_species), stat=ierr)
        if (ierr /= 0) call io_error('Error allocating atoms_pos_frac in cell_dist')
        allocate (atoms_pos_cart(3, max_sites, num_species), stat=ierr)
        if (ierr /= 0) call io_error('Error allocating atoms_pos_cart in cell_dist')
        allocate (atoms_label(num_species), stat=ierr)
        if (ierr /= 0) call io_error('Error allocating atoms_label in cell_dist')
        allocate (atoms_symbol(num_species), stat=ierr)
        if (ierr /= 0) call io_error('Error allocating atoms_symbol in cell_dist')
        ! For Photoemission
        allocate (atoms_pos_cart_photo(3, num_atoms), stat=ierr)
        if (ierr /= 0) call io_error('Error allocating atoms_pos_cart_photo in cell_dist')
        allocate (atoms_label_tmp(num_atoms), stat=ierr)
        if (ierr /= 0) call io_error('Error allocating atoms_label_tmp in cell_dist')
      end if
      call comms_bcast(atoms_pos_frac(1, 1, 1), 3*num_species*max_sites)
      call comms_bcast(atoms_pos_cart(1, 1, 1), 3*num_species*max_sites)
      call comms_bcast(atoms_label(1), len(atoms_label(1))*num_species)
      call comms_bcast(atoms_symbol(1), len(atoms_symbol(1))*num_species)
      ! For Photoemission
      call comms_bcast(atoms_pos_cart_photo(1, 1), 3*num_atoms)
      call comms_bcast(atoms_label_tmp(1), maxlen*num_atoms)
    end if
    call comms_bcast(num_crystal_symmetry_operations, 1)
    if (num_crystal_symmetry_operations > 0) then
      if (.not. on_root) then
        allocate (crystal_symmetry_operations(3, 3, num_crystal_symmetry_operations), stat=ierr)
        if (ierr /= 0) call io_error(" Error : cannot allocate crystal_symmetry_operations in cell_dist")
        allocate (crystal_symmetry_disps(3, num_crystal_symmetry_operations), stat=ierr)
        if (ierr /= 0) call io_error(" Error : cannot allocate crystal_symmetry_disps in cell_dist")
      end if
      call comms_bcast(crystal_symmetry_operations(1, 1, 1), 3*3*num_crystal_symmetry_operations)
      call comms_bcast(crystal_symmetry_disps(1, 1), 3*num_crystal_symmetry_operations)
    end if
  end subroutine cell_dist
Call graph
cell_dist calls comms_bcast, io_error
optados calls cell_dist