cell_get_symmetry – OptaDOS
cell_get_symmetry Subroutine
49 statements
Source File
public subroutine cell_get_symmetry()
Uses
od_comms
od_io
Arguments
None
Calls
Called by
Contents
Source Code
cell_get_symmetry
Source Code
  subroutine cell_get_symmetry
    !=========================================================================!
    ! Read in the cell symmetries                                             !
    !-------------------------------------------------------------------------!
    ! Arguments: kpoints - an array of kpoints                                !
    !            num_kpts - size of the kpoint array                          !
    !-------------------------------------------------------------------------!
    ! Returns: kpint_grid_dim - the number of kpoints in each dimension       !
    !-------------------------------------------------------------------------!
    ! Parent module variables used: None                                      !
    !-------------------------------------------------------------------------!
    ! Modules used:  None                                                     !
    !-------------------------------------------------------------------------!
    ! Key Internal Variables:                                                 !
    ! Described below                                                         !
    !-------------------------------------------------------------------------!
    ! Necessary conditions: None
    !--------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------!
    ! JRY, April 2011                                                         !
    !=========================================================================!
    use od_comms, only: on_root, comms_bcast
    use od_io, only: filename_len, io_file_unit, seedname, io_error, stdout
    implicit none
    integer :: ierr, sym_file
    logical :: exists
    character(filename_len)     :: sym_filename
    !check if we already have the symmetries
    if (allocated(crystal_symmetry_operations)) return
    sym_file = io_file_unit()
    sym_filename = trim(seedname)//".sym"
    if (on_root) inquire (file=sym_filename, exist=exists)
    call comms_bcast(exists, 1)
    if (.not. exists) then
      if (on_root) then
        write (stdout, '(1x,78a)') '!--------------------------------- WARNING ----------------------------------!'
        write (stdout, '(1x,78a)') '!                Symmetry Operations file (.sym) not found                   !'
        write (stdout, '(1x,78a)') '!                       Proceeding without symmetry                          !'
        write (stdout, '(1x,78a)') '!----------------------------------------------------------------------------!'
        write (stdout, '(1x,a78)') '|                                                                            |'
      end if
      num_crystal_symmetry_operations = 0
      return
    end if
    if (on_root) then
      open (unit=sym_file, file=sym_filename, form='unformatted', err=100, status='old')
      read (sym_file) num_crystal_symmetry_operations
      if (num_crystal_symmetry_operations > 0) then
        allocate (crystal_symmetry_operations(3, 3, num_crystal_symmetry_operations), stat=ierr)
        if (ierr /= 0) call io_error(" Error : cannot allocate crystal_symmetry_operations in cell_get_symmetry")
        allocate (crystal_symmetry_disps(3, num_crystal_symmetry_operations), stat=ierr)
        if (ierr /= 0) call io_error(" Error : cannot allocate crystal_symmetry_disps in cell_get_symmetry")
        read (sym_file) crystal_symmetry_operations
        read (sym_file) crystal_symmetry_disps
      end if
    end if
    call comms_bcast(num_crystal_symmetry_operations, 1)
    if (num_crystal_symmetry_operations > 0) then
      if (.not. on_root) then
        allocate (crystal_symmetry_operations(3, 3, num_crystal_symmetry_operations), stat=ierr)
        if (ierr /= 0) call io_error(" Error : cannot allocate crystal_symmetry_operations in cell_get_symmetry")
        allocate (crystal_symmetry_disps(3, num_crystal_symmetry_operations), stat=ierr)
        if (ierr /= 0) call io_error(" Error : cannot allocate crystal_symmetry_disps in cell_get_symmetry")
      end if
      call comms_bcast(crystal_symmetry_operations(1, 1, 1), 9*num_crystal_symmetry_operations)
      call comms_bcast(crystal_symmetry_disps(1, 1), 3*num_crystal_symmetry_operations)
    end if
    return
100 call io_error('Error: Problem opening sym file in cell_get_symmetry')
  end subroutine cell_get_symmetry
Call graph
cell_get_symmetry calls io_file_unit, comms_bcast, io_error
make_weights calls cell_get_symmetry
optics_calculate calls make_weights
optados calls optics_calculate