cell_get_real_lattice – OptaDOS
cell_get_real_lattice Subroutine
23 statements
Source File
public subroutine cell_get_real_lattice()
Uses
od_comms
od_io
od_constants
Arguments
None
Calls
Called by
Contents
Source Code
cell_get_real_lattice
Source Code
  subroutine cell_get_real_lattice
    !=========================================================================
    ! This subroutine reads the lattice parameters from the bands file in
    ! order to have them stored when the frac_to_cart and cart_frac subroutines
    ! are called. Independently of having used the elec_read_band_energy
    ! subroutine before.
    use od_comms, only: on_root
    use od_io, only: io_file_unit, seedname, filename_len, stdout, io_time, &
      io_error
    use od_constants, only: bohr2ang
    integer :: band_unit
    character(filename_len) :: band_filename
    !Open the bands file
    band_unit = io_file_unit()
    band_filename = trim(seedname)//".bands"
!    print*,'band_filename=',band_filename
    ! Read the header from the bands file
    if (on_root) then
      open (unit=band_unit, file=band_filename, status="old", form='formatted')!,err=100)
!100    call io_error('Error: Problem opening bands file in cell_get_real_lattice')
      read (band_unit, *)
      read (band_unit, *)
      read (band_unit, *)
      read (band_unit, *)
      read (band_unit, *)
      read (band_unit, *)
      read (band_unit, *) real_lattice(:, 1)
      read (band_unit, *) real_lattice(:, 2)
      read (band_unit, *) real_lattice(:, 3)
    end if
    real_lattice = real_lattice*bohr2ang
    if (on_root) close (unit=band_unit)
  end subroutine cell_get_real_lattice
Call graph
cell_get_real_lattice calls io_file_unit
cell_read_cell calls cell_get_real_lattice
cell_calc_kpoint_r_cart calls cell_get_real_lattice, cell_calc_lattice
cell_calc_lattice calls cell_get_real_lattice
cell_get_atoms calls cell_get_real_lattice
param_read calls cell_read_cell
optados calls cell_calc_lattice, param_read