cell_calc_kpoint_r_cart – OptaDOS
cell_calc_kpoint_r_cart Subroutine
25 statements
Source File
public subroutine cell_calc_kpoint_r_cart()
Uses
od_comms
od_io
od_algorithms
Arguments
None
Calls
Contents
Source Code
cell_calc_kpoint_r_cart
Source Code
  subroutine cell_calc_kpoint_r_cart
    !=========================================================================
    ! This subroutine calculates the cartesian coordinates of the k points
    use od_algorithms, only: utility_reciprocal_frac_to_cart
    use od_comms, only: my_node_id
    use od_io, only: io_file_unit, seedname, filename_len, stdout, io_time, &
      io_error
!    use od_electronic, only : elec_read_band_energy
    integer :: i, ik, loop, ierr
    real(kind=dp), allocatable, dimension(:, :) :: kpoint_r_tmp
    real(kind=dp), allocatable, dimension(:, :) :: kpoint_r_cart_tmp
    allocate (kpoint_r_tmp(3, num_kpoints_on_node(my_node_id)), stat=ierr)
    if (ierr /= 0) call io_error('Error allocating kpoint_r_tmp in&
&    cell_calc_kpoint_r_cart')
    allocate (kpoint_r_cart_tmp(3, num_kpoints_on_node(my_node_id)), stat=ierr)
    if (ierr /= 0) call io_error('Error allocating kpoint_r_cart_tmp in&
&    cell_calc_kpoint_r_cart')
    kpoint_r_tmp = kpoint_r
    !This is to be sure that the k point fractional coordinates are stored.
    !If they are, the elec_read_band_energy will return.
!    call elec_read_band_energy
    ! We will call this only if we have not read in the cell before. With a parallel build
    ! the non root nodes would not get the updated cell and perform another bohr2ang
    ! conversion. If I try to insert a comms_bcast in the cell_get_
    ! F.Mildner 04/2023
    if (.not. abs(cell_volume) .gt. 0.0_dp) then
      call cell_get_real_lattice
      call cell_calc_lattice
    end if
    do loop = 1, num_kpoints_on_node(my_node_id)
      call utility_reciprocal_frac_to_cart(kpoint_r_tmp(:, loop), kpoint_r_cart_tmp(:, loop), recip_lattice)
!      print*,kpoint_r_tmp(1,loop),kpoint_r_tmp(2,loop),kpoint_r_tmp(3,loop),&
!       kpoint_r_cart_tmp(1,loop),kpoint_r_cart_tmp(2,loop),kpoint_r_cart_tmp(3,loop)
!print*,loop,kpoint_r_cart_tmp(:,loop),recip_lattice
    end do
    kpoint_r_cart = kpoint_r_cart_tmp
!      do loop=1,num_kpoints_on_node(my_node_id)
!      print*,kpoint_r_tmp(1,loop),kpoint_r_cart(1,loop),&
!      kpoint_r_tmp(2,loop),kpoint_r_cart(2,loop),&
!      kpoint_r_tmp(3,loop),kpoint_r_cart(3,loop)
!      end do
    deallocate (kpoint_r_tmp, stat=ierr)
    if (ierr /= 0) call io_error('Error: cell_calc_kpoint_r_cart - &
&     failed to deallocate kpoint_r_tmp')
    deallocate (kpoint_r_cart_tmp, stat=ierr)
    if (ierr /= 0) call io_error('Error: cell_calc_kpoint_r_cart - &
&     failed to deallocate kpoint_r_cart_tmp')
  end subroutine cell_calc_kpoint_r_cart
Call graph
cell_calc_kpoint_r_cart calls io_error, utility_reciprocal_frac_to_cart, cell_calc_lattice, cell_get_real_lattice
cell_calc_lattice calls cell_get_real_lattice
cell_get_real_lattice calls io_file_unit