core_calculate – OptaDOS
core_calculate Subroutine
29 statements
Source File
public subroutine core_calculate()
Uses
od_parameters
od_comms
od_dos_utils
od_electronic
od_io
Arguments
None
Calls
Called by
Contents
Source Code
core_calculate
Source Code
  subroutine core_calculate
    use od_electronic, only: elec_read_elnes_mat, efermi_set
    use od_dos_utils, only: dos_utils_calculate, dos_utils_set_efermi, &
    & dos_utils_compute_bandgap
    use od_comms, only: on_root
    use od_io, only: stdout
    use od_parameters, only: core_LAI_broadening, LAI_gaussian, LAI_lorentzian, &
    & set_efermi_zero, LAI_lorentzian_scale, core_chemical_shift
    implicit none
    if (on_root) then
      write (stdout, *)
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)') '+                            Core Loss Calculation                           +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)') '|                                                                            |'
    end if
    ! read in the core matrix elements from disk
    call elec_read_elnes_mat
    !    (elnes_mat(orb,nb,indx,nk,ns),indx=1,3)
    if (.not. efermi_set) call dos_utils_set_efermi
    call core_prepare_matrix_elements
    call dos_utils_calculate(matrix_weights, weighted_dos)
    ! Lifetime and instrumental broadening
    if (core_LAI_broadening .eqv. .true.) then
      allocate (weighted_dos_broadened(size(weighted_dos, 1), size(weighted_dos, 2), size(weighted_dos, 3)))
      weighted_dos_broadened = 0.0_dp
      if (LAI_lorentzian .or. (LAI_lorentzian_scale .gt. 0.00001_dp)) call core_lorentzian
      if (LAI_gaussian) call core_gaussian
    end if
    if (set_efermi_zero .and. .not. efermi_set) call dos_utils_set_efermi
    if (on_root) then
      call write_core
    end if
  end subroutine core_calculate
Call graph
core_calculate calls elec_read_elnes_mat, dos_utils_set_efermi, dos_utils_calculate
elec_read_elnes_mat calls io_time, io_file_unit, comms_bcast, comms_send, io_error, comms_recv, elec_elnes_find_channel_names
dos_utils_set_efermi calls dos_utils_calculate, comms_bcast, io_error, comms_reduce
dos_utils_calculate calls io_time, comms_bcast, io_error, dos_utils_merge, elec_read_band_gradient
elec_elnes_find_channel_names calls io_error
dos_utils_merge calls comms_reduce
elec_read_band_gradient calls io_time, io_file_unit, comms_bcast, comms_send, io_error, comms_recv, algor_dist_array, elec_read_optical_mat, elec_dealloc_optical
algor_dist_array calls io_error
elec_read_optical_mat calls io_time, io_file_unit, comms_send, io_error, comms_recv, algor_dist_array
elec_dealloc_optical calls io_error
optados calls core_calculate