dos_utils_merge – OptaDOS
dos_utils_merge Subroutine
10 statements
Source File
public subroutine dos_utils_merge(dos, weighted_dos)
Uses
od_comms
od_electronic
od_parameters
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout), allocatable :: dos(:,:)
real(kind=dp), intent(inout), optional, allocatable :: weighted_dos(:,:,:)
Calls
Called by
Contents
Source Code
dos_utils_merge
Source Code
  subroutine dos_utils_merge(dos, weighted_dos)
    !===============================================================================
    ! The DOS was calculated accross nodes. Now give them all back to root
    ! and free up the memeory on the slaves
    !-------------------------------------------------------------------------------
    ! Arguments: dos          (in - slaves) (inout -  root)       : The DOS
    !            weighted_dos (in - slaves) (inout -  root) (opt) : Weighted DOS
    !-------------------------------------------------------------------------------
    ! Parent Module Varables Used: mw
    !-------------------------------------------------------------------------------
    ! Modules Used: See below
    !-------------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------------
    ! Necessary Conditions: None
    !-------------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------------
    ! Written by : A J Morris December 2010
    !===============================================================================
    use od_comms, only: comms_reduce
    use od_electronic, only: nspins
    use od_parameters, only: dos_nbins
    implicit none
    real(kind=dp), intent(inout), allocatable, optional :: weighted_dos(:, :, :) ! bins.spins, orbitals
    real(kind=dp), allocatable, intent(inout) :: dos(:, :)
    call comms_reduce(dos(1, 1), nspins*dos_nbins, "SUM")
    if (present(weighted_dos)) call comms_reduce(weighted_dos(1, 1, 1), mw%nspins*dos_nbins*mw%norbitals, "SUM")
!    if(.not.on_root) then
!       if(allocated(dos)) deallocate(dos,stat=ierr)
!       if (ierr/=0) call io_error (" ERROR : dos : merge_dos : cannot deallocate dos")
!       if(present(weighted_dos))  then
!          if(allocated(weighted_dos)) deallocate(weighted_dos,stat=ierr)
!          if (ierr/=0) call io_error (" ERROR : dos : merge_dos : cannot deallocate weighted_dos")
!       end if
!    endif
  end subroutine dos_utils_merge
Call graph
dos_utils_merge calls comms_reduce
dos_utils_calculate calls dos_utils_merge
pdos_calculate calls dos_utils_calculate, dos_utils_set_efermi
core_calculate calls dos_utils_calculate, dos_utils_set_efermi
dos_utils_set_efermi calls dos_utils_calculate
dos_calculate calls dos_utils_calculate, dos_utils_set_efermi
optados calls pdos_calculate, core_calculate, dos_calculate, optics_calculate, jdos_calculate
jdos_utils_calculate calls dos_utils_set_efermi
optics_calculate calls dos_utils_set_efermi, jdos_utils_calculate
jdos_calculate calls jdos_utils_calculate