dos_utils_compute_band_energies – OptaDOS
dos_utils_compute_band_energies Subroutine
42 statements
Source File
public subroutine dos_utils_compute_band_energies()
Uses
od_parameters
od_comms
od_cell
od_electronic
od_io
Arguments
None
Calls
Called by
Contents
Source Code
dos_utils_compute_band_energies
Source Code
  subroutine dos_utils_compute_band_energies
    !===============================================================================
    ! High-level subroutine to compute band energies of the DOS calculated.
    ! Calculates using the band_energies directly and compares with the
    ! function calc_band_energies which does the low level computation on the DOS.
    !-------------------------------------------------------------------------------
    ! Arguments: None
    !-------------------------------------------------------------------------------
    ! Parent Module Varables Used: E,dos_fixed,dos_adaptive,dos_linear
    !-------------------------------------------------------------------------------
    ! Modules Used: See below
    !-------------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------------
    ! Necessary Conditions: E must be set
    !-------------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------------
    ! Written by : A J Morris December 2010
    !===============================================================================
    use od_parameters, only: adaptive, linear, fixed, iprint
    use od_electronic, only: electrons_per_state, efermi, nbands, nspins, band_energy
    use od_cell, only: kpoint_weight, num_kpoints_on_node
    use od_comms, only: comms_reduce, my_node_id, on_root
    use od_io, only: stdout, io_time
    implicit none
    real(kind=dp) :: eband
    real(kind=dp) :: time0, time1
    integer :: ik, is, ib
    time0 = io_time()
    if (on_root) then
      write (stdout, '(1x,a78)') '+--------------------------- Band Energy Analysis ---------------------------+'
      if (fixed) then
        write (stdout, '(1x,a1,a46,f12.4,a3,8x,a8)') "|", &
          " Band energy (Fixed broadening)  : ", calc_band_energies(dos_fixed), "eV", "<- BEF |"
      end if
      if (adaptive) then
        write (stdout, '(1x,a1,a46,f12.4,a3,8x,a8)') "|", &
          " Band energy (Adaptive broadening) : ", calc_band_energies(dos_adaptive), "eV", "<- BEA |"
      end if
      if (linear) then
        write (stdout, '(1x,a1,a46,f12.4,a3,8x,a8)') "|", &
          " Band energy (Linear broadening) : ", calc_band_energies(dos_linear), "eV", "<- BEL |"
      end if
    end if
    eband = 0.0_dp
    do ik = 1, num_kpoints_on_node(my_node_id)
      do is = 1, nspins
        do ib = 1, nbands
          if (band_energy(ib, is, ik) .le. efermi) eband = eband + band_energy(ib, is, ik)*electrons_per_state&
                                                          &*kpoint_weight(ik)
        end do
      end do
    end do
    call comms_reduce(eband, 1, 'SUM')
    if (on_root) then
      write (stdout, '(1x,a1,a46,f12.4,a3,8x,a8)') "|", " Band energy (From CASTEP) : ", eband, "eV", "<- BEC |"
      write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
      time1 = io_time()
      if (iprint > 1) then
        write (stdout, '(1x,a59,f11.3,a8)') &
             '+ Time to calculate Band Energies                        &
          &      ', time1 - time0, ' (sec) +'
      end if
      write (stdout, '(1x,a78)')
    end if
  end subroutine dos_utils_compute_band_energies
Call graph
dos_utils_compute_band_energies calls io_time, comms_reduce
dos_calculate calls dos_utils_compute_band_energies
optados calls dos_calculate