dos_utils_compute_dos_at_efermi – OptaDOS
dos_utils_compute_dos_at_efermi Subroutine
46 statements
Source File
public subroutine dos_utils_compute_dos_at_efermi()
Uses
od_comms
od_electronic
od_parameters
od_io
Arguments
None
Calls
Called by
Contents
Source Code
dos_utils_compute_dos_at_efermi
Source Code
  subroutine dos_utils_compute_dos_at_efermi
    !===============================================================================
    use od_io, only: stdout, io_time
    use od_comms, only: on_root, comms_bcast
    use od_electronic, only: efermi, nspins
    use od_parameters, only: fixed, linear, adaptive, iprint, compute_band_gap
    implicit none
    real(dp) :: time0, time1
    real(dp) :: dos_at_efermi(1:3, 1:nspins) ! Fix,Adapt,Linear
    integer :: is
    time0 = io_time()
    call dos_utils_calculate_at_e(efermi, dos_at_e=dos_at_efermi)
    if ((iprint > 1) .and. on_root) then
      write (stdout, *)
    end if
    if (on_root) then
      write (stdout, '(1x,a78)') '+----------------------- DOS at Fermi Energy Analysis -----------------------+'
      write (stdout, '(1x,a1,a46,f8.4,a3,12x,a8)') "|", " Fermi energy used : ", efermi, "eV", "       |"
      if (fixed) then
        write (stdout, '(1x,a78)') "| From Fixed broadening                                                      |"
        do is = 1, nspins
          write (stdout, '(1x,a1,a20,i1,a25,f8.4,a9,6x,a8)') "|", "Spin Component : ", is,&
               &"  DOS at Fermi Energy : ", dos_at_efermi(1, is), " eln/cell", "<- DEF |"
        end do
        write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
      end if
      if (adaptive) then
        write (stdout, '(1x,a78)') "| From Adaptive broadening                                                   |"
        do is = 1, nspins
          write (stdout, '(1x,a1,a20,i1,a25,f8.4,a9,6x,a8)') "|", "Spin Component : ", is,&
               &"  DOS at Fermi Energy : ", dos_at_efermi(2, is), " eln/cell", "<- DEA |"
        end do
        write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
      end if
      if (linear) then
        write (stdout, '(1x,a78)') "| From Linear broadening                                                     |"
        do is = 1, nspins
          write (stdout, '(1x,a1,a20,i1,a25,f8.4,a9,6x,a8)') "|", "Spin Component : ", is,&
               &"  DOS at Fermi Energy : ", dos_at_efermi(3, is), " eln/cell", "<- DEL |"
        end do
        write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
      end if
      time1 = io_time()
      if (iprint > 1) then
        write (stdout, '(1x,a59,f11.3,a8)') &
             '+ Time to calculate DOS at Fermi Energy                  &
             &      ', time1 - time0, ' (sec) +'
      end if
      write (stdout, '(1x,a78)')
      !-------------------------------------------------------------------------------
    end if
    call comms_bcast(compute_band_gap, 1)
  end subroutine dos_utils_compute_dos_at_efermi
Call graph
dos_utils_compute_dos_at_efermi calls io_time, dos_utils_calculate_at_e, comms_bcast
dos_utils_calculate_at_e calls io_time, io_error, elec_read_band_gradient
elec_read_band_gradient calls io_time, comms_bcast, io_error, io_file_unit, elec_read_optical_mat, comms_recv, algor_dist_array, comms_send, elec_dealloc_optical
elec_read_optical_mat calls io_time, io_error, io_file_unit, comms_recv, algor_dist_array, comms_send
algor_dist_array calls io_error
elec_dealloc_optical calls io_error
dos_calculate calls dos_utils_compute_dos_at_efermi
optados calls dos_calculate