dos_calculate – OptaDOS
dos_calculate Subroutine
31 statements
Source File
public subroutine dos_calculate()
Uses
od_parameters
od_dos_utils
od_comms
od_electronic
od_io
$ $ unshifted_efermi=efermi $ $ if(set_efermi_zero) then $ if(on_root) then $ write(stdout,*) $ write(stdout,'(1x,a71)') '+----------------------- Shift Fermi Energy --------------------------+' $ write(stdout,'(1x,a1,a46,a24)')"|", " Setting Fermi energy to 0 : ","|" $ endif $ E(:)=E(:)-efermi $ band_energy(:,:,:) = band_energy(:,:,:) - efermi $ efermi=0.0_dp $ endif $ $ if(on_root) then $ write(stdout,'(1x,a1,a46,f8.4,a3,12x,a8)')"|", " Fermi energy used : ", unshifted_efermi,"eV","| <- Ef " $ write(stdout,'(1x,a71)') '+---------------------------------------------------------------------+' $ $ time1=io_time() $ write(stdout,'(1x,a40,f11.3,a)') 'Time to perfom analysis ',time1-time0,' (sec)' $ !------------------------------------------------------------------------------- $ end if
Arguments
None
Calls
Called by
Contents
Source Code
dos_calculate
Source Code
  subroutine dos_calculate
    !===============================================================================
    ! Main routine in dos module, drives the calculation of density of states for
    ! both task : dos and also if it is required elsewhere.
    !-------------------------------------------------------------------------------
    ! Arguments: matrix_weigths (in) (opt) : LCAO or other weightings for DOS
    !            weighted_dos   (out)(opt) : Output DOS weigthed by matrix_weights
    !-------------------------------------------------------------------------------
    ! Parent Module Varables Used: mw, E, dos_adaptive, dos_fixed, dos_linear
    ! intdos_adaptive, intdos_fixed, intdos_linear, efermi_fixed, efermi_adaptive
    ! efermi_linear, delta_bins, calc_weighted_dos
    !-------------------------------------------------------------------------------
    ! Modules Used: see below
    !-------------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------------
    ! Necessary Conditions: One of linear, adaptive or fixed must be .true.
    !-------------------------------------------------------------------------------
    ! Known Worries: (1) If more than one of linear, adaptive or fixed are set it
    ! uses the most complicated method.
    ! (2) It should be possible to pass optioinal arguments to sub programs as
    ! optional argumnets without checking whether they are there or not. g95 will
    ! allow this behaviour. gfotran will not.
    !-------------------------------------------------------------------------------
    ! Written by : A J Morris December 2010
    !===============================================================================
    use od_io, only: stdout, io_time
    use od_dos_utils, only: E, dos_fixed, intdos_fixed, dos_adaptive, &
         &intdos_adaptive, dos_linear, intdos_linear, dos_utils_calculate,&
         &dos_utils_compute_dos_at_efermi, dos_utils_compute_bandgap,&
         &dos_utils_compute_band_energies, dos_utils_set_efermi
    use od_parameters, only: fixed, adaptive, linear, compute_band_gap,&
         &compute_band_energy, set_efermi_zero, iprint
    use od_comms, only: on_root
    use od_electronic, only: nspins, efermi, band_energy, efermi_set
    real(dp) :: time0, time1, unshifted_efermi
    if (on_root) then
      write (stdout, *)
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)') '+                              Density of States                             +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)')
    end if
    call dos_utils_calculate   ! Will return if this has already been done.
    if (.not. efermi_set) call dos_utils_set_efermi
    time0 = io_time()
    !-------------------------------------------------------------------------------
    ! D O S   A T   F E R M I  L E V E L   A N A L Y S I S
    call dos_utils_compute_dos_at_efermi
    !-------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------
    ! B A N D  G A P  A N A L Y S I S
    ! The compute_dos_at_efermi routine may have set compute_band_gap to true
    if (compute_band_gap) call dos_utils_compute_bandgap
    !-------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------
    ! B A N D   E N E R G Y   A N A L Y S I S
    ! Now for a bit of crosschecking  band energies
    ! These should all converge to the same number as the number of bins is increased
    if (compute_band_energy) call dos_utils_compute_band_energies
    !-------------------------------------------------------------------------------
!!$
!!$    unshifted_efermi=efermi
!!$
!!$    if(set_efermi_zero) then
!!$       if(on_root) then
!!$          write(stdout,*)
!!$          write(stdout,'(1x,a71)')  '+----------------------- Shift Fermi Energy --------------------------+'
!!$          write(stdout,'(1x,a1,a46,a24)')"|", " Setting Fermi energy to 0 : ","|"
!!$       endif
!!$       E(:)=E(:)-efermi
!!$       band_energy(:,:,:) = band_energy(:,:,:) - efermi
!!$       efermi=0.0_dp
!!$    endif
!!$
!!$    if(on_root) then
!!$       write(stdout,'(1x,a1,a46,f8.4,a3,12x,a8)')"|", " Fermi energy used : ", unshifted_efermi,"eV","| <- Ef "
!!$       write(stdout,'(1x,a71)')  '+---------------------------------------------------------------------+'
!!$
!!$       time1=io_time()
!!$       write(stdout,'(1x,a40,f11.3,a)') 'Time to perfom analysis ',time1-time0,' (sec)'
!!$       !-------------------------------------------------------------------------------
!!$    end if
    ! W R I T E   O U T   D O S
    time0 = io_time()
    ! Otherwise we have written to wdos and dos, so they can be called
    ! by whatever.
    if (on_root) then
      if (fixed) call write_dos(E, dos_fixed, intdos_fixed, "fixed")
      if (adaptive) call write_dos(E, dos_adaptive, intdos_adaptive, "adaptive")
      if (linear) call write_dos(E, dos_linear, intdos_linear, "linear")
      !if(quad)    call write_dos(E, dos_quad, intdos_quad, "quad")
    end if
    time1 = io_time()
    if (on_root .and. iprint > 1) then
      write (stdout, '(1x,a59,f11.3,a8)') &
           '+ Time to write DOS to disk                              &
           &      ', time1 - time0, ' (sec) +'
    end if
    !-------------------------------------------------------------------------------
  end subroutine dos_calculate
Call graph
dos_calculate calls dos_utils_calculate, io_time, dos_utils_set_efermi, dos_utils_compute_bandgap, dos_utils_compute_dos_at_efermi, dos_utils_compute_band_energies, write_dos
dos_utils_calculate calls io_time, io_error, dos_utils_merge, comms_bcast, elec_read_band_gradient
dos_utils_set_efermi calls dos_utils_calculate, io_error, comms_bcast, comms_reduce
dos_utils_compute_bandgap calls io_time, io_error, comms_recv, comms_send
dos_utils_compute_dos_at_efermi calls io_time, comms_bcast, dos_utils_calculate_at_e
dos_utils_compute_band_energies calls io_time, comms_reduce
write_dos calls io_error, io_date, write_dos_xmgrace, io_file_unit
dos_utils_merge calls comms_reduce
elec_read_band_gradient calls io_time, io_error, comms_bcast, comms_recv, comms_send, io_file_unit, algor_dist_array, elec_read_optical_mat, elec_dealloc_optical
dos_utils_calculate_at_e calls io_time, io_error, elec_read_band_gradient
write_dos_xmgrace calls io_error, io_file_unit, xmgu_setup, xmgu_legend, xmgu_title, xmgu_subtitle, xmgu_axis, xmgu_vertical_line, xmgu_data_header, xmgu_data
algor_dist_array calls io_error
elec_read_optical_mat calls io_time, io_error, comms_recv, comms_send, io_file_unit, algor_dist_array
xmgu_setup calls io_date
elec_dealloc_optical calls io_error
xmgu_data calls io_error
optados calls dos_calculate