dos_utils_set_efermi – OptaDOS
dos_utils_set_efermi Subroutine
58 statements
Source File
public subroutine dos_utils_set_efermi()
Uses
od_parameters
od_comms
od_cell
od_electronic
od_io
Arguments
None
Calls
Called by
Contents
Source Code
dos_utils_set_efermi
Source Code
  subroutine dos_utils_set_efermi
    !===============================================================================
    use od_parameters, only: efermi_choice, efermi_user, fixed,&
         & linear, adaptive, iprint
    use od_electronic, only: efermi_castep, num_electrons, nspins, efermi, &
         & electrons_per_state, band_energy, nbands, efermi_set
    use od_io, only: io_error, stdout
    use od_comms, only: on_root, my_node_id, comms_reduce, comms_bcast
    use od_cell, only: num_kpoints_on_node
    implicit none
    integer :: is, ik, top_occ_band
    real(kind=dp) :: vbm, cbm
    if (on_root) then
      write (stdout, '(1x,a78)') '+--------------------------- Setting Fermi Energy  --------------------------+'
    end if
!    if(on_root) write(stdout,'(1x,a1,a46,f8.4,a3,12x,a8)') "|",&
!         &" Fermi energy from file : ",efermi_castep," eV","| <- EfC"
    select case (efermi_choice)
    case ("file")
      if (on_root) write (stdout, '(1x,a1,a46,f8.4,a3,12x,a8)') "|",&
           &" Set fermi energy from file : ", efermi_castep, " eV", "  <- EfC"
      efermi = efermi_castep
    case ("user")
      if (on_root) write (stdout, '(1x,a1,a46,f8.4,a3,12x,a8)') "|",&
           &" Fermi energy from user : ", efermi_user, " eV", "  <- EfU"
      efermi = efermi_user
    case ("insulator")
      ! Same fermi level for up and down spins. Different number
      ! of electrons for up and down spins.
      ! For an insulator. Hence same number of electrons at each kpoint.
      ! band_energy(ib,is,ik)
      vbm = -huge(vbm)
      cbm = huge(cbm)
      if (on_root .and. iprint > 3) write (stdout, *) vbm, " =vbm : cbm= ", cbm
      ! Go between global VBM and CBM band_energy(ib,is,ik)
      do ik = 1, num_kpoints_on_node(my_node_id)
        do is = 1, nspins
          ! Which is the band below the fermi energy at this spin and kpoint
          top_occ_band = ceiling(num_electrons(is)/electrons_per_state)
          if (band_energy(top_occ_band, is, ik) > vbm) &
               &vbm = band_energy(top_occ_band, is, ik)
          ! If the band_energy array is big enough then there will be occupied states.
          if (num_electrons(is) + 1 .le. nbands) then
            if (band_energy(top_occ_band + 1, is, ik) < cbm) &
                 &cbm = band_energy(top_occ_band + 1, is, ik)
          end if
        end do
        if (on_root .and. iprint > 3) write (stdout, *) vbm, " =vbm : cbm= ", cbm
      end do
      ! Find the globals
      call comms_reduce(cbm, 1, 'MIN')
      call comms_bcast(cbm, 1)
      call comms_reduce(vbm, 1, 'MAX')
      call comms_bcast(vbm, 1)
      ! If we have a CBM then set the efermi halfway between VBM and CBM
      ! If we don't have a CBM then set it 0.5 eV above VBM and hope for
      ! the best.
      if (cbm == huge(cbm)) then
        efermi = vbm + 0.5_dp
      else
        efermi = vbm + 0.5_dp*(cbm - vbm)
      end if
      if (on_root) write (stdout, '(1x,a1,a46,f8.4,a3,12x,a8)') "|",&
           &" Fermi energy assuming insulator : ", efermi, " eV", "  <- EfI"
    case ("optados")
      ! So in the case of compare_jdos we pick efermi_adaptive.
      call dos_utils_calculate ! This will return if we already have.
      if (fixed) efermi = efermi_fixed
      if (linear) efermi = efermi_linear
      if (adaptive) efermi = efermi_adaptive
      if (on_root) write (stdout, '(1x,a1,a46,f8.4,a3,12x,a8)') "|",&
           &" Fermi energy from DOS : ", efermi, " eV", "<- EfD |"
    case default
      call io_error('Error in dos_utils_set_efermi: unknown efermi choice this is a bug')
    end select
    if (on_root) then
      write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
      write (stdout, '(1x,a78)')
    end if
    efermi_set = .true.
  end subroutine dos_utils_set_efermi
Call graph
dos_utils_set_efermi calls comms_reduce, comms_bcast, dos_utils_calculate, io_error
dos_utils_calculate calls comms_bcast, io_error, dos_utils_merge, elec_read_band_gradient, io_time
dos_utils_merge calls comms_reduce
elec_read_band_gradient calls comms_bcast, io_error, io_time, io_file_unit, elec_read_optical_mat, comms_recv, algor_dist_array, comms_send, elec_dealloc_optical
elec_read_optical_mat calls io_error, io_time, io_file_unit, comms_recv, algor_dist_array, comms_send
algor_dist_array calls io_error
elec_dealloc_optical calls io_error
pdos_calculate calls dos_utils_set_efermi
jdos_utils_calculate calls dos_utils_set_efermi
core_calculate calls dos_utils_set_efermi
dos_calculate calls dos_utils_set_efermi
optics_calculate calls dos_utils_set_efermi, jdos_utils_calculate
optados calls pdos_calculate, core_calculate, dos_calculate, optics_calculate, jdos_calculate
jdos_calculate calls jdos_utils_calculate