dos_utils_compute_bandgap – OptaDOS
dos_utils_compute_bandgap Subroutine
181 statements
Source File
public subroutine dos_utils_compute_bandgap()
Uses
od_parameters
od_comms
od_cell
od_electronic
od_io
Arguments
None
Calls
Called by
Contents
Source Code
dos_utils_compute_bandgap
Source Code
  subroutine dos_utils_compute_bandgap
    !===============================================================================
    ! Modified from LINDOS -- AJM 3rd June 2011
    ! Rewritten 31/1/12 AJM
    use od_electronic, only: nspins, nbands, efermi, band_energy, num_electrons, &
         &  all_kpoints
    use od_cell, only: nkpoints, num_kpoints_on_node
    use od_io, only: stdout, io_time, io_error
    use od_parameters, only: iprint
    use od_comms, only: comms_send, comms_recv, on_root, my_node_id, &
         &num_nodes, root_id
    implicit none
    ! Local array containing vbm and cbm at each kpoint and spin.
    real(dp), allocatable :: bandgap(:, :, :)        !nbands=1,2,nspins,nkpoints
    ! Same as bandgap only merged over all nodes to the root-node
    real(dp), allocatable :: global_bandgap(:, :, :)
    ! Avergae bandgap for up and down spins (summed over all kpoints and divided
    ! by num_kpoints)
    real(dp), allocatable :: average_bandgap(:)
    ! Optical bandgap. Smallest vertical distance between two kpoints
    real(dp), allocatable ::  optical_bandgap(:)
    ! The number of kpoints that have the vbm and cbm
    integer, allocatable :: thermal_vbm_multiplicity(:), thermal_cbm_multiplicity(:)
    ! The number of kpoints that have the optical gap
    integer, allocatable :: optical_multiplicity(:)
    ! Timing variables
    real(dp) :: time0, time1
    ! Loop counters
    integer :: ik, is, ib, ierr, inode, kpoints_before_this_node
    ! Temporary variables
    real(dp), allocatable :: kpoint_bandgap(:)
    real(dp) :: thermal_cbm, thermal_vbm, thermal_bandgap, weighted_average
    integer :: thermal_vbm_k, thermal_cbm_k
    logical :: thermal_multiplicity
    time0 = io_time()
    ! Preamble
    if (on_root) then
      if (iprint > 2) then
        write (stdout, *)
        write (stdout, '(1x,a78)') "| Finding an estimate of the maximum bandgap...                              |"
      end if
      write (stdout, '(1x,a78)') '+----------------------------- Bandgap Analysis -----------------------------+'
    end if
    if (.not. allocated(all_kpoints)) call io_error('Error all_kpoints not allocated in dos_utils: compute_bandgap')
    allocate (bandgap(1:2, 1:nspins, 1:num_kpoints_on_node(my_node_id)), stat=ierr)
    if (ierr /= 0) call io_error('Error allocating bandgap in dos_utils: compute_bandgap')
    bandgap = -200.00_dp
    ! Write the VBM and CBM into a slice of an band_energy array
    ! It is easier to merge these slices onto the root node rather than try
    ! the horrendous book-keeping of which kpoint on which node has which
    ! gap
    do is = 1, nspins
      do ik = 1, num_kpoints_on_node(my_node_id)
        bands_loop: do ib = 1, nbands
          ! If this eignevalue is greater than efermi, then this is the CBM
          ! and the one below it is the VBM
          if (band_energy(ib, is, ik) .gt. efermi) then
            bandgap(1, is, ik) = band_energy(ib - 1, is, ik)
            bandgap(2, is, ik) = band_energy(ib, is, ik)
            exit bands_loop
          end if
        end do bands_loop
      end do !ik
    end do !is
    ! Create a global kpoint array,and set it to something silly in case we need to debug whether
    ! data was actually written to it.
    if (on_root) then
      allocate (global_bandgap(1:2, 1:nspins, 1:nkpoints), stat=ierr)
      if (ierr /= 0) call io_error('Error allocating global_bandgap in dos_utils: compute_bandgap')
      global_bandgap = -100.00_dp
    end if
    ! Pass all the slices around Efermi to the head node, making sure whe get the global
    ! kpoint number. *And* crucially the same kpoint numbers as in the bands file.
    ! Otherwise the kpoint numbers of the VBM and CBM change as different numbers of nodes
    ! are used.
    kpoints_before_this_node = 0
    do inode = 1, (num_nodes - 1)
      if (my_node_id == inode) call comms_send(bandgap(1, 1, 1), 2*is*num_kpoints_on_node(inode), root_id)
      if (on_root) call comms_recv(global_bandgap(1, 1, &
           & kpoints_before_this_node + 1), 2*is*num_kpoints_on_node(inode), inode)
      kpoints_before_this_node = kpoints_before_this_node + num_kpoints_on_node(inode)
    end do
    ! Copy the root node's slice to the global array.
    if (on_root) &
         & global_bandgap(1:2, 1:nspins, kpoints_before_this_node &
         & + 1:kpoints_before_this_node + num_kpoints_on_node(root_id)) &
             & = bandgap(1:2, 1:nspins, 1:num_kpoints_on_node(root_id))
    ! We now have an array with the VBM and CBM of all kpoints, so we can deallocate the local ones.
    deallocate (bandgap, stat=ierr)
    if (ierr /= 0) call io_error('Error deallocating bandgap in dos_utils: compute_bandgap')
    ! We've freed up a bit of memory, so now we can allocate all of the output data arrays on the
    ! headnode
    if (on_root) then
      allocate (average_bandgap(nspins), stat=ierr)
      if (ierr /= 0) call io_error('Error allocating average_bandgap in dos_utils: compute_bandgap')
      allocate (optical_bandgap(nspins), stat=ierr)
      if (ierr /= 0) call io_error('Error allocating optical_bandgap in dos_utils: compute_bandgap')
      allocate (kpoint_bandgap(nspins), stat=ierr)
      if (ierr /= 0) call io_error('Error allocating kpoint_bandgap in dos_utils: compute_bandgap')
      allocate (thermal_vbm_multiplicity(nspins), stat=ierr)
      if (ierr /= 0) call io_error('Error allocating thermal_vbm_multiplicity in dos_utils: compute_bandgap')
      allocate (thermal_cbm_multiplicity(nspins), stat=ierr)
      if (ierr /= 0) call io_error('Error allocatingthermal_cbm_multiplicity in dos_utils: compute_bandgap')
      allocate (optical_multiplicity(nspins), stat=ierr)
      if (ierr /= 0) call io_error('Error allocating optical_multiplicity in dos_utils: compute_bandgap')
    end if
    ! Now lets look for the various bandgaps by cycling through the global_bandgap array
    if (on_root) then
      ! COMMENTED OUT: This writes out the complete global_bandgap array to fort.7 if you'd like
      ! to take a look
      !  do ik=1,nkpoints
      !     do is=1,nspins
      !        write(7,*) ik,is, global_bandgap(1,is,ik),global_bandgap(2,is,ik)
      !     enddo
      ! enddo
      average_bandgap = 0.0_dp
      thermal_cbm = huge(1.0_dp)
      thermal_vbm = -huge(1.0_dp)
      thermal_vbm_multiplicity = 1
      thermal_cbm_multiplicity = 1
      thermal_vbm_k = -1
      thermal_cbm_k = -1
      optical_multiplicity = 1
      optical_bandgap = huge(1.0_dp)
      do is = 1, nspins
        do ik = 1, nkpoints
          ! Look for the thermal vbm. This is done for both spin components although
          ! ws care about the individual spin multiplicity
          if (global_bandgap(1, is, ik) .ge. thermal_vbm) then
            if (abs(global_bandgap(1, is, ik) - thermal_vbm) < epsilon(thermal_vbm)) then
              ! If this is the same value of vbm as we had before, then
              ! we have multiple maxima, and we need to know that we might not
              ! get the direct/indirect gap right
              thermal_vbm_multiplicity(is) = thermal_vbm_multiplicity(is) + 1
            else
              ! If we haven't had this high a vbm value before, then we take it
              ! and set the multiplicty back to zero
              thermal_vbm = global_bandgap(1, is, ik)
              thermal_vbm_multiplicity(is) = 1
              thermal_vbm_k = ik
            end if
          end if
          ! We search for the CBM in the same way as the VBM above.
          if (global_bandgap(2, is, ik) .le. thermal_cbm) then
            if (abs(global_bandgap(2, is, ik) - thermal_cbm) < epsilon(thermal_cbm)) then
              thermal_cbm_multiplicity(is) = thermal_cbm_multiplicity(is) + 1
            else
              thermal_cbm = global_bandgap(2, is, ik)
              thermal_cbm_multiplicity(is) = 1
              thermal_cbm_k = ik
            end if
          end if
          ! Work out the bandgap for this particular kpoint and spin
          kpoint_bandgap(is) = global_bandgap(2, is, ik) - global_bandgap(1, is, ik)
          ! If this is smaller than the optical gap. Then this is our next iteration
          ! of the optical gap. Worry about mutiplicties in the same way. Although this
          ! is just for into, since we can't have direct/indirect optical gaps.
          if (kpoint_bandgap(is) .le. optical_bandgap(is)) then
            if (abs(kpoint_bandgap(is) - optical_bandgap(is)) < epsilon(optical_bandgap(is))) then
              optical_multiplicity(is) = optical_multiplicity(is) + 1
            else
              optical_bandgap(is) = kpoint_bandgap(is)
              optical_multiplicity(is) = 1
            end if
          end if
          average_bandgap(is) = average_bandgap(is) + (global_bandgap(2, is, ik) - global_bandgap(1, is, ik))
        end do ! nkpoints
      end do ! nspins
      ! We now have enough info to calculate the average bandgap and the thermal bandgap
      average_bandgap = average_bandgap/nkpoints
      vbm_energy = thermal_vbm
      cbm_energy = thermal_cbm
      thermal_bandgap = thermal_cbm - thermal_vbm
      ! Don't want this array hanging around a moment longer than we need it.
      deallocate (global_bandgap, stat=ierr)
      if (ierr /= 0) call io_error('Error deallocating global_bandgap in dos_utils: compute_bandgap')
      ! If there is more than one VBM and CBM let's flag it up.
      ! We wouldn't like to comment on the nature of the gap at this point
      ! Unless we did some more work. (Which should have been done before we deallocated
      ! global_bandgap!)
      thermal_multiplicity = .false.
      do is = 1, nspins
        if ((thermal_vbm_multiplicity(is) .ne. 1) .or. (thermal_cbm_multiplicity(is) .ne. 1)) thermal_multiplicity = .true.
      end do
      ! Report the thermal gap multiplicity
      write (stdout, '(1x,1a,a50, 19x, a8)') "|", "Number of kpoints at       VBM       CBM", "       |"
      do is = 1, nspins
        write (stdout, '(1x,a1,a25,1x,i3,1x,a3,1x,i5,5x,i5,20x,a8)') "|", " Spin :", is, " : ", &
             &thermal_vbm_multiplicity(is), thermal_cbm_multiplicity(is), "       |"
      end do
      ! Write out the thermal gap info
      write (stdout, '(1x,a1,a32,f15.10,1x,a3,18x,a8)') "|", "Thermal Bandgap :", thermal_bandgap, "eV", "<- TBg |"
      if (.not. thermal_multiplicity) then
        if (thermal_vbm_k == thermal_cbm_k) then
          write (stdout, '(1x,a1,a32,1x,f10.5,1x,f10.5,1x,f10.5,4x,a8)') "|", "At kpoint :", &
            all_kpoints(1:3, thermal_vbm_k), "       |"
          write (stdout, '(1x,a78)') '|             ==> Direct Gap                                                  |'
        else
          write (stdout, '(1x,a1,a32,1x,f10.5,1x,f10.5,1x,f10.5,4x,a8)') "|", "Between VBM kpoint :", &
            all_kpoints(1:3, thermal_vbm_k), "       |"
          write (stdout, '(1x,a1,a32,1x,f10.5,1x,f10.5,1x,f10.5,4x,a8)') "|", "and CBM kpoint:", &
            all_kpoints(1:3, thermal_cbm_k), "       |"
          write (stdout, '(1x,a78)') '|             ==> Indirect Gap                                               |'
        end if
      else ! thermal_mutiplicty=.true.
        write (stdout, '(1x,a78)') '|          ==> Multiple Band Minima and Maxima -- Gap unknown                |'
      end if
      ! We allocated this in elec_read_band_energy but kept it if compute_band_gap=T
      deallocate (all_kpoints, stat=ierr)
      if (ierr /= 0) call io_error('Error: Problem deallocating all_kpoints in read_band_energy')
      ! Write out the Optical gap indo
      write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
      write (stdout, '(1x,a1,a45,a32)') "|", "Optical Bandgap  ", "|"
      do is = 1, nspins
        write (stdout, '(1x,a1,a25,1x,i3,1x,a3,1x,f15.10,1x,a3,16x,a8)') "|", " Spin :", is, " : ", optical_bandgap(is),&
             &"eV", "<- OBg |"
      end do
      write (stdout, '(1x,1a,a50, 19x, a8)') "|", "Number of kpoints with this gap         ", "       |"
      ! The multiplicity info here is just for reference.
      do is = 1, nspins
        write (stdout, '(1x,a1,a25,1x,i3,1x,a3,6x,i5,25x,a8)') "|", " Spin :", is, " : ", optical_multiplicity(is), "       |"
      end do
      ! Write out the average bandgap
      write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
      write (stdout, '(1x,a1,a45,a32)') "|", "Average Bandgap  ", "|"
      do is = 1, nspins
        write (stdout, '(1x,a1,a25,1x,i3,1x,a3,1x,f15.10,1x,a3,16x,a8)') "|", " Spin :", is, " : ", &
             &average_bandgap(is), "eV", "<- ABg |"
      end do
      ! If we have more then one spin, then we need some way to combine the up and down spin bandgaps
      ! At Richard Needs' suggestion we use the weighted sum.
      if (nspins > 1) then
        weighted_average = (average_bandgap(1)*num_electrons(1) + average_bandgap(2)*num_electrons(2)) &
             & /(num_electrons(1) + num_electrons(2))
        write (stdout, '(1x,a1,a33,1x,f15.10,1x,a3,16x,a8)') "|", " Weighted Average : ", weighted_average, "eV", "<- wAB |"
      end if
    end if
    ! Let not have these other arrays hanging around a moment longer than we need them
    if (on_root) then
      deallocate (average_bandgap, stat=ierr)
      if (ierr /= 0) call io_error('Error deallocating average_bandgap in dos_utils: compute_bandgap')
      deallocate (optical_bandgap, stat=ierr)
      if (ierr /= 0) call io_error('Error deallocating optical_bandgap in dos_utils: compute_bandgap')
      deallocate (kpoint_bandgap, stat=ierr)
      if (ierr /= 0) call io_error('Error deallocating kpoint_bandgap in dos_utils: compute_bandgap')
      deallocate (thermal_vbm_multiplicity, stat=ierr)
      if (ierr /= 0) call io_error('Error deallocating thermal_vbm_multiplicity in dos_utils: compute_bandgap')
      deallocate (thermal_cbm_multiplicity, stat=ierr)
      if (ierr /= 0) call io_error('Error deallocatingthermal_cbm_multiplicity in dos_utils: compute_bandgap')
      deallocate (optical_multiplicity, stat=ierr)
      if (ierr /= 0) call io_error('Error deallocating optical_multiplicity in dos_utils: compute_bandgap')
    end if
    if (on_root) then
      write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
      write (stdout, '(1x,a78)') '|                                                                            |'
    end if
    time1 = io_time()
    if (on_root .and. iprint > 1) write (stdout, '(1x,a40,f11.3,a)') 'Time to calculate Bandgap ', time1 - time0, ' (sec)'
  end subroutine dos_utils_compute_bandgap
Call graph
dos_utils_compute_bandgap calls io_time, comms_recv, comms_send, io_error
dos_calculate calls dos_utils_compute_bandgap
optados calls dos_calculate