dos_utils_calculate – OptaDOS
dos_utils_calculate Subroutine
124 statements
Source File
public subroutine dos_utils_calculate(matrix_weights, weighted_dos)
Uses
od_parameters
od_comms
od_cell
od_electronic
od_io
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), optional, allocatable :: matrix_weights(:,:,:,:)
real(kind=dp), intent(out), optional, allocatable :: weighted_dos(:,:,:)
Calls
Called by
Contents
Source Code
dos_utils_calculate
Source Code
  subroutine dos_utils_calculate(matrix_weights, weighted_dos)
    !===============================================================================
    ! Main routine in dos module, drives the calculation of density of states for
    ! both task : dos and also if it is required elsewhere.
    !-------------------------------------------------------------------------------
    ! Arguments: matrix_weigths (in) (opt) : LCAO or other weightings for DOS
    !            weighted_dos   (out)(opt) : Output DOS weigthed by matrix_weights
    !-------------------------------------------------------------------------------
    ! Parent Module Varables Used: mw, E, dos_adaptive, dos_fixed, dos_linear
    ! intdos_adaptive, intdos_fixed, intdos_linear, efermi_fixed, efermi_adaptive
    ! efermi_linear, delta_bins, calc_weighted_dos
    !-------------------------------------------------------------------------------
    ! Modules Used: see below
    !-------------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------------
    ! Necessary Conditions: One of linear, adaptive or fixed must be .true.
    !-------------------------------------------------------------------------------
    ! Known Worries: (1) If more than one of linear, adaptive or fixed are set it
    ! uses the most complicated method.
    ! (2) It should be possible to pass optioinal arguments to sub programs as
    ! optional argumnets without checking whether they are there or not. g95 will
    ! allow this behaviour. gfotran will not.
    !-------------------------------------------------------------------------------
    ! Written by : A J Morris December 2010
    !===============================================================================
    use od_io, only: stdout, io_time, io_error
    use od_comms, only: on_root, my_node_id, comms_bcast
    use od_electronic, only: band_gradient, band_energy, efermi, efermi_castep, nspins, &
         & elec_read_band_gradient, unshifted_efermi
    use od_parameters, only: linear, adaptive, fixed, quad, &
         & dos_per_volume, iprint, set_efermi_zero, efermi_choice, iprint, photo
    use od_cell, only: cell_volume, num_kpoints_on_node
    implicit none
    !-------------------------------------------------------------------------------
    ! I N T E R N A L   V A R I A B L E S
    real(kind=dp) :: time0, time1
    real(kind=dp), intent(in), allocatable, optional  :: matrix_weights(:, :, :, :)
    real(kind=dp), intent(out), allocatable, optional  :: weighted_dos(:, :, :) ! bins.spins, orbitals
    !-------------------------------------------------------------------------------
    if (.not. (linear .or. adaptive .or. fixed .or. quad)) call io_error(" DOS: No Broadening Set")
    calc_weighted_dos = .false.
    if (present(matrix_weights)) calc_weighted_dos = .true.
    if (calc_weighted_dos .eqv. .false.) then ! We are called just to provide dos.
      if (allocated(E)) then
        if (on_root .and. iprint > 1) write (stdout, '(1x,a78)') "| Already calculated dos, so returning... &
             &                                   |"
        return  ! The dos has already been calculated previously so just return.
      end if
    end if
    if (calc_weighted_dos) then
      mw%norbitals = size(matrix_weights, 1)
      mw%nbands = size(matrix_weights, 2)
      mw%nkpoints = size(matrix_weights, 3)
      mw%nspins = size(matrix_weights, 4)
    end if
    if (calc_weighted_dos) then
      !       print*,'mw%nkpoints.ne.num_nkpoints_on_node(my_node_id))',mw%nkpoints,nunum_nkpoints_on_node(my_node_id)
      if (mw%nspins .ne. nspins) call io_error("ERROR : DOS :  mw%nspins not equal to nspins.")
      if (mw%nkpoints .ne. num_kpoints_on_node(my_node_id)) &
        call io_error("ERROR : DOS : mw%nkpoints not equal to nkpoints.")
    end if
    !-------------------------------------------------------------------------------
    ! R E A D   B A N D   G R A D I E N T S
    ! If we're using one of the more accurate roadening schemes we also need to read in the
    ! band gradients too
    if (quad .or. linear .or. adaptive) then
      if (.not. allocated(band_gradient)) call elec_read_band_gradient
    end if
    !-------------------------------------------------------------------------------
    ! C A L C U L A T E   D O S
    ! Now everything is set up, we can perform the dos accumulation in parallel
    time0 = io_time()
    call setup_energy_scale
    if (on_root .and. (iprint > 1)) write (stdout, *)
    if (fixed) then
      if (calc_weighted_dos .and. (.not. adaptive) .and. (.not. linear)) then
        call calculate_dos("f", dos_fixed, intdos_fixed, matrix_weights=matrix_weights, weighted_dos=weighted_dos)
        call dos_utils_merge(dos_fixed, weighted_dos=weighted_dos)
      else
        call calculate_dos("f", dos_fixed, intdos_fixed)
        call dos_utils_merge(dos_fixed)
      end if
      call dos_utils_merge(intdos_fixed)
    end if
    if (adaptive) then
      if (calc_weighted_dos .and. (.not. linear)) then
        call calculate_dos("a", dos_adaptive, intdos_adaptive, matrix_weights=matrix_weights, weighted_dos=weighted_dos)
        call dos_utils_merge(dos_adaptive, weighted_dos=weighted_dos)
      else
        call calculate_dos("a", dos_adaptive, intdos_adaptive)
        call dos_utils_merge(dos_adaptive)
      end if
      call dos_utils_merge(intdos_adaptive)
    end if
    if (linear) then
      if (calc_weighted_dos) then
        call calculate_dos("l", dos_linear, intdos_linear, matrix_weights=matrix_weights, weighted_dos=weighted_dos)
        call dos_utils_merge(dos_linear, weighted_dos=weighted_dos)
      else
        call calculate_dos("l", dos_linear, intdos_linear)
        call dos_utils_merge(dos_linear)
      end if
      call dos_utils_merge(intdos_linear)
    end if
    if (quad) then
      call io_error("quadratic broadening not implemented")
      !if(quad)    call merge_dos(dos_quad)
      !if(quad)    call merge_dos(intdos_quad)
    end if
    !    if(.not.on_root) then
    !       if(allocated(E)) deallocate(E, stat=ierr)
    !       if (ierr/=0) call io_error ("cannot deallocate  E")
    !    endif
    time1 = io_time()
    if (on_root .and. iprint > 1) then
      write (stdout, '(1x,a59,f11.3,a8)') '+ Time to calculate DOS                                     ', &
      &time1 - time0, ' (sec) +'
      write (stdout, '(1x,a78)')
    end if
    !-------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------
    ! F E R M I   E N E R G Y   A N A L Y S I S
    if (efermi_choice == "optados") then
      if (on_root) then
        time0 = io_time()
        write (stdout, '(1x,a78)') '+----------------------------- Fermi Energy Analysis ------------------------+'
        !    write(stdout,'(1x,a1,a46,f8.4,a3,12x,a8)') "|"," Fermi energy from CASTEP : ",efermi_castep," eV","<- EfC |"
        !    write(stdout,'(1x,a71)')  '+---------------------------------------------------------------------+'
        if (fixed) then
          write (stdout, '(1x,a23,54x,a1)') "| From Fixed broadening", "|"
          efermi_fixed = calc_efermi_from_intdos(intdos_fixed)
          write (stdout, '(1x,a1,a46,f8.4,a3,12x,a8)') "|", " Fermi energy (Fixed broadening) : ", &
          &efermi_fixed, "eV", "<- EfF |"
          write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
        end if
        if (adaptive) then
          write (stdout, '(1x,a26,51x,a1)') "| From Adaptive broadening", "|"
          efermi_adaptive = calc_efermi_from_intdos(intdos_adaptive)
          write (stdout, '(1x,a1,a46,f8.4,a3,12x,a8)') "|", " Fermi energy (Adaptive broadening) : " &
            , efermi_adaptive, "eV", "<- EfA |"
          write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
        end if
        if (linear) then
          write (stdout, '(1x,a24,53x,a1)') "| From Linear broadening", "|"
          efermi_linear = calc_efermi_from_intdos(intdos_linear)
          write (stdout, '(1x,a1,a46,f8.4,a3,12x,a8)') "|", " Fermi energy (Linear broadening) : ", &
            efermi_linear, " eV", "<- EfL |"
          write (stdout, '(1x,a78)') '+----------------------------------------------------------------------------+'
        end if
      end if
    end if
    call comms_bcast(efermi_fixed, 1)
    call comms_bcast(efermi_linear, 1)
    call comms_bcast(efermi_adaptive, 1)
    if (on_root) then
      if (dos_per_volume) then
        if (fixed) then
          dos_fixed = dos_fixed/cell_volume
          intdos_fixed = intdos_fixed/cell_volume
        end if
        if (adaptive) then
          dos_adaptive = dos_adaptive/cell_volume
          intdos_adaptive = intdos_adaptive/cell_volume
        end if
        if (linear) then
          dos_linear = dos_linear/cell_volume
          intdos_linear = intdos_linear/cell_volume
        end if
        if (calc_weighted_dos) then
          if (photo) then
            weighted_dos = weighted_dos
          else
            weighted_dos = weighted_dos/cell_volume
          end if
        end if
        ! if(quad) then
        !    dos_quad=dos_quad/cell_volume
        !    intdos_quad=intdos_quad/cell_volume
        ! endif
      end if
    end if
  end subroutine dos_utils_calculate
Call graph
dos_utils_calculate calls io_error, dos_utils_merge, comms_bcast, elec_read_band_gradient, io_time
dos_utils_merge calls comms_reduce
elec_read_band_gradient calls io_error, comms_bcast, io_time, comms_recv, algor_dist_array, comms_send, io_file_unit, elec_read_optical_mat, elec_dealloc_optical
algor_dist_array calls io_error
elec_read_optical_mat calls io_error, io_time, comms_recv, algor_dist_array, comms_send, io_file_unit
elec_dealloc_optical calls io_error
pdos_calculate calls dos_utils_calculate, dos_utils_set_efermi
core_calculate calls dos_utils_calculate, dos_utils_set_efermi
dos_utils_set_efermi calls dos_utils_calculate
dos_calculate calls dos_utils_calculate, dos_utils_set_efermi
optados calls pdos_calculate, core_calculate, dos_calculate, optics_calculate, jdos_calculate
jdos_utils_calculate calls dos_utils_set_efermi
optics_calculate calls dos_utils_set_efermi, jdos_utils_calculate
jdos_calculate calls jdos_utils_calculate