dos_utils_calculate_at_e – OptaDOS
dos_utils_calculate_at_e Subroutine
61 statements
Source File
public subroutine dos_utils_calculate_at_e(energy, dos_at_e, matrix_weights, weighted_dos_at_e)
Uses
od_parameters
od_comms
od_cell
od_electronic
od_io
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: energy
real(kind=dp), intent(out) :: dos_at_e(1:3,nspins)
real(kind=dp), intent(in), optional, allocatable :: matrix_weights(:,:,:,:)
real(kind=dp), intent(out), optional :: weighted_dos_at_e(:,:)
Calls
Called by
Contents
Source Code
dos_utils_calculate_at_e
Source Code
  subroutine dos_utils_calculate_at_e(energy, dos_at_e, matrix_weights, weighted_dos_at_e)
    !===============================================================================
    ! Main routine in dos module, drives the calculation of density of states for
    ! both task : dos and also if it is required elsewhere.
    !-------------------------------------------------------------------------------
    ! Arguments: matrix_weigths (in) (opt) : LCAO or other weightings for DOS
    !            weighted_dos   (out)(opt) : Output DOS weigthed by matrix_weights
    !-------------------------------------------------------------------------------
    ! Parent Module Varables Used: mw, E, dos_adaptive, dos_fixed, dos_linear
    ! intdos_adaptive, intdos_fixed, intdos_linear, efermi_fixed, efermi_adaptive
    ! efermi_linear, delta_bins, calc_weighted_dos
    !-------------------------------------------------------------------------------
    ! Modules Used: see below
    !-------------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------------
    ! Necessary Conditions: One of linear, adaptive or fixed must be .true.
    !-------------------------------------------------------------------------------
    ! Known Worries: (1) If more than one of linear, adaptive or fixed are set it
    ! uses the most complicated method.
    ! (2) It should be possible to pass optioinal arguments to sub programs as
    ! optional argumnets without checking whether they are there or not. g95 will
    ! allow this behaviour. gfotran will not.
    !-------------------------------------------------------------------------------
    ! Written by : A J Morris December 2010
    !===============================================================================
    use od_io, only: stdout, io_time, io_error
    use od_comms, only: on_root, my_node_id
    use od_electronic, only: band_gradient, nspins, elec_read_band_gradient
    use od_parameters, only: linear, adaptive, fixed, quad, iprint
    use od_cell, only: nkpoints, num_kpoints_on_node
    implicit none
    !-------------------------------------------------------------------------------
    ! I N T E R N A L   V A R I A B L E S
    real(kind=dp) :: time0, time1
    real(kind=dp), intent(in), allocatable, optional  :: matrix_weights(:, :, :, :)
    real(kind=dp), intent(out), optional  :: weighted_dos_at_e(:, :) ! spins, orbitals RJN3Jun changed
    real(kind=dp), intent(in) :: energy
    real(kind=dp), intent(out) :: dos_at_e(1:3, nspins) ! fixed, adaptive, linear : spins
    !-------------------------------------------------------------------------------
    if (.not. (linear .or. adaptive .or. fixed .or. quad)) call io_error(" DOS: No Broadening Set")
    calc_weighted_dos = .false.
    if (present(matrix_weights)) calc_weighted_dos = .true.
    if (calc_weighted_dos) then
      mw%norbitals = size(matrix_weights, 1)
      mw%nbands = size(matrix_weights, 2)
      mw%nkpoints = size(matrix_weights, 3)
      mw%nspins = size(matrix_weights, 4)
    end if
    if (calc_weighted_dos) then
      if (mw%nspins .ne. nspins) call io_error("ERROR : DOS :  mw%nspins not equal to nspins.")
      if (mw%nkpoints .ne. num_kpoints_on_node(my_node_id)) &
           & call io_error("ERROR : DOS : mw%nkpoints not equal to nkpoints.")
    end if
    !-------------------------------------------------------------------------------
    ! R E A D   B A N D   G R A D I E N T S
    ! If we're using one of the more accurate roadening schemes we also need to read in the
    ! band gradients too
    if (quad .or. linear .or. adaptive) then
      if (.not. allocated(band_gradient)) call elec_read_band_gradient
    end if
    !-------------------------------------------------------------------------------
    ! C A L C U L A T E   D O S
    ! Now everything is set up, we can perform the dos accumulation in parellel
    time0 = io_time()
    if (fixed) then
      if (calc_weighted_dos .and. (.not. adaptive) .and. (.not. linear)) then
        call calculate_dos_at_e("f", energy, dos_at_e(1, :), matrix_weights=matrix_weights, &
             &weighted_dos_at_e=weighted_dos_at_e)
        call dos_utils_merge_at_e(dos_at_e(1, :), weighted_dos_at_e=weighted_dos_at_e)
      else
        call calculate_dos_at_e("f", energy, dos_at_e(1, :))
        call dos_utils_merge_at_e(dos_at_e(1, :))
      end if
    end if
    if (adaptive) then
      if (calc_weighted_dos .and. (.not. linear)) then
        call calculate_dos_at_e("a", energy, dos_at_e(2, :), matrix_weights=matrix_weights, &
             &weighted_dos_at_e=weighted_dos_at_e)
        call dos_utils_merge_at_e(dos_at_e(2, :), weighted_dos_at_e=weighted_dos_at_e)
      else
        call calculate_dos_at_e("a", energy, dos_at_e(2, :))
        call dos_utils_merge_at_e(dos_at_e(2, :))
      end if
    end if
    if (linear) then
      if (calc_weighted_dos) then
        call calculate_dos_at_e("l", energy, dos_at_e(3, :), matrix_weights=matrix_weights, &
             &weighted_dos_at_e=weighted_dos_at_e)
        call dos_utils_merge_at_e(dos_at_e(3, :), weighted_dos_at_e=weighted_dos_at_e)
      else
        call calculate_dos_at_e("l", energy, dos_at_e(3, :))
        call dos_utils_merge_at_e(dos_at_e(3, :))
      end if
    end if
    ! if(quad) then
    !
    ! endif
    time1 = io_time()
    if (on_root .and. iprint > 1) then
      write (stdout, '(1x,a59,f11.3,a8)') &
           '+ Time to calculate DOS at certain energy                &
           &      ', time1 - time0, ' (sec) +'
    end if
    !-------------------------------------------------------------------------------
  end subroutine dos_utils_calculate_at_e
Call graph
dos_utils_calculate_at_e calls io_error, elec_read_band_gradient, io_time
elec_read_band_gradient calls io_error, io_time, comms_bcast, comms_recv, algor_dist_array, comms_send, io_file_unit, elec_read_optical_mat, elec_dealloc_optical
algor_dist_array calls io_error
elec_read_optical_mat calls io_error, io_time, comms_recv, algor_dist_array, comms_send, io_file_unit
elec_dealloc_optical calls io_error
dos_utils_compute_dos_at_efermi calls dos_utils_calculate_at_e
optics_calculate calls dos_utils_calculate_at_e
dos_calculate calls dos_utils_compute_dos_at_efermi
optados calls optics_calculate, dos_calculate