doslin – OptaDOS
doslin Function
67 statements
Source File
public function doslin(e0, e1, e2, e3, e4, e, int)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: e0
real(kind=dp), intent(in) :: e1
real(kind=dp), intent(in) :: e2
real(kind=dp), intent(in) :: e3
real(kind=dp), intent(in) :: e4
real(kind=dp), intent(in) :: e
real(kind=dp), intent(out) :: int
Return Value real(kind=dp)
Called by
Contents
Source Code
doslin
Source Code
  function doslin(e0, e1, e2, e3, e4, e, int)
    !===============================================================================
    ! Return the DoS contribution for a linear band portion and a cubic cell
    !-------------------------------------------------------------------------------
    ! Arguments: e0 (in) : Energy at centre of sub cell
    !   e1,e2,e3,e4 (in) : Energies of the four lowest corners of the sub cell
    !            e  (in) : Energy at which DOS is evaluated
    !          int  (out): Integrated DOS contribution for energy, E)
    ! (The function itself returns the DOS couribution for energy, E)
    !-------------------------------------------------------------------------------
    ! Parent Module Varables Used: None
    !-------------------------------------------------------------------------------
    ! Modules Used: See below
    !-------------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------------
    ! Necessary Conditions: None
    !-------------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------------
    ! Written by : C J Pickard. From LinDOS. Extra Comments A J Morris Sept 2010
    !===============================================================================
    implicit none
    ! - E X T R A   C O M M E N T S   B Y   A J M
    real(kind=dp), intent(in)  :: e0, e1, e2, e3, e4
    real(kind=dp), intent(in)  :: e
    real(kind=dp), intent(out) :: int
    real(kind=dp) :: doslin
    real(kind=dp) :: alpha, e_use
    logical        :: shift
    ! ** Check the input arguments
    ! The inputs must be in ascending order. These are the four lowest corners of the
    ! cube (sub cell) around the k-point. E_0 is the energy of the k-point which would
    ! in a Gaussian smearing scheme, be the only info we have about this cube of recip
    ! space.
    if (.not. ((e4 .le. e3) .and. (e3 .le. e2) .and. (e2 .le. e1) .and. (e1 .le. e0))) then
      stop 'doslin: input arguments incorrect'
    end if
    ! ** Return if outside the range
    ! If the energy is below the smallest corner, then return. The CES doesn't cut this
    ! sub cell
    if (e .le. e4) then
      doslin = 0.0_dp ! TRUE
      int = 0.0_dp ! TRUE
      return
    end if
    ! Since the energy in the sub cell is linearly extrapolated, if the energy is twice as
    ! big as the energy difference between the smallest corner and the middle, then this
    ! energy is outdside the top of the cell, and whilst this cell doesn't contribute to the
    ! CES, it does to the occupation.
    if (e .ge. (2.0_dp*e0 - e4)) then
      doslin = 0.0_dp ! TRUE
      int = 1.0_dp ! TRUE
      return
    end if
    ! ** Special treatment if all vertices at the same energy
    ! If the CES is perfectly flat in the cell, then we don't want to be dividing by zero.
    ! the below just catches this case and forces alpha to be 1. This is fine as the else
    ! block below looks for the same problem and the answer comes out correctly to
    if ((e1 == e2) .and. (e1 == e3) .and. (e3 == e4)) then
      alpha = 1.0_dp
    else
      alpha = 1.0_dp/((e1 - e3)*(e1 - e4) + (e3 - e4)**2/3.0_dp - (e1 - e2)**2/3.0_dp + (e1 + e2 - e3 - e4)*(e0 - e1)) ! TRUE
    end if
    ! ** Flip if above e0
    ! If e is greater than the energy of the k-point, then we're going to subtract the
    ! contribution from a full cell, rather than add it to an empty one. The extrapolation
    ! is linear, so we can do this fine.
    if (e .gt. e0) then
      e_use = 2.0_dp*e0 - e ! TRUE
      shift = .true.
    else
      e_use = e ! TRUE
      shift = .false.
    end if
    ! ** The analytic constributions to the DOS and integrated DOS
    if (e_use .le. e4) then
      ! P O S S I B L E   S P E E D   U P
      ! If we ended up in here, something went wrong as this should already have been trapped.
      doslin = 0.0_dp ! TRUE
      int = 0.0_dp ! TRUE
    else if (e_use .lt. e3) then
      ! There isn't a problem with divide by zero here. Since if e3=e4 and e_use < e3
      ! we would have been caugh in the above if.
      doslin = (e_use - e4)**2/(e3 - e4)/2.0_dp ! TRUE
      int = (e_use - e4)**3/(e3 - e4)/6.0_dp ! TRUE
    else if (e_use .lt. e2) then
      doslin = (e_use - (e3 + e4)/2.0_dp) ! TRUE
      int = ((e3 - e4)**2/3.0_dp + (e_use - e3)*(e_use - e4))/2.0_dp ! TRUE
    else if (e_use .lt. e1) then
      doslin = (e1 + e2 - e3 - e4)/2.0_dp ! TRUE
      ! Ok, so the IF costs more than the maths. But this way also catches the
      ! divide by zero. Clever!
      if (e1 .ne. e2) doslin = doslin - (e1 - e_use)**2/(e1 - e2)/2.0_dp ! TRUE
      int = ((e2 - e4)*(e_use - e3) + (e1 - e3)*(e_use - e2) + (e3 - e4)**2/3.0_dp + &
             ((e1 - e_use)**3 - (e1 - e2)**3)/(e1 - e2)/3.0_dp)/2.0_dp ! TRUE
    else if (e_use .le. e0) then
      ! Check to see if the band is flat.
      if ((e1 + e2 - e3 - e4) .gt. 0.0_dp) then
        doslin = (e1 + e2 - e3 - e4)/2.0_dp ! TRUE
        int = ((e1 - e3)*(e1 - e4) + (e3 - e4)**2/3.0_dp - (e1 - e2)**2/3.0_dp + &
               (e1 + e2 - e3 - e4)*(e_use - e1))/2.0_dp ! TRUE
      else ! This can only happen if e1=e2=e3=e4,
        ! in this case we stop doing what we were doing and calculate the contirbution from the
        ! gradient simplistically. grad E = e0-e4.
        doslin = 1.0_dp/(e0 - e4)/2.0_dp ! TRUE
        int = (e_use - e4)/(e0 - e4)/2.0_dp ! SO YES, THIS DOES INTEGRATE FROM THE LINE ABOVE
      end if
    else
      write (*, *) e_use, e
      write (*, *) e0, e1, e2, e3, e4
      stop 'Got here, but not supposed to!'
    end if
    ! ** Normalise
    doslin = doslin*alpha
    if (shift) then
      int = 1.0_dp - int*alpha ! TRUE
    else
      int = int*alpha ! TRUE
    end if
    return
  end function doslin
Call graph
calculate_jdos calls doslin
jdos_utils_calculate calls calculate_jdos
jdos_calculate calls jdos_utils_calculate
optics_calculate calls jdos_utils_calculate
optados calls jdos_calculate, optics_calculate