doslin_sub_cell_corners – OptaDOS
doslin_sub_cell_corners Subroutine
30 statements
Source File
public subroutine doslin_sub_cell_corners(grad, step, energy, EigenV)
Uses
od_cell
od_algorithms
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: grad(1:3)
real(kind=dp), intent(in) :: step(1:3)
real(kind=dp), intent(in) :: energy
real(kind=dp), intent(out) :: EigenV(0:4)
Calls
Called by
Contents
Source Code
doslin_sub_cell_corners
Source Code
  subroutine doslin_sub_cell_corners(grad, step, energy, EigenV)
    !===============================================================================
    ! A helper subroutine for calculated_dos, which is used for the linear
    ! broadening method. This routine extrapolates the energies at the corner of the
    ! sub cells by using the gradient at the centre of the cell
    !-------------------------------------------------------------------------------
    ! Arguments: grad   (in) : The Gradient of the band at the centre of a sub-cell
    !            step   (in) : The directions to the edge of the sub_cell
    !            energy (in) : The Band energy at the centre of the sub cell
    !            EigenV (out): The Energies at the corners of the sub-cell
    !-------------------------------------------------------------------------------
    ! Parent Module Varables Used: None
    !-------------------------------------------------------------------------------
    ! Modules Used: See below
    !-------------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------------
    ! Necessary Conditions: None
    !-------------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------------
    ! Written by : A J Morris December 2010 Heavliy modified from LinDOS
    !===============================================================================
    use od_algorithms, only: heap_sort
    use od_cell, only: recip_lattice
    implicit none
    real(kind=dp), intent(in)  :: grad(1:3), step(1:3)
    real(kind=dp), intent(out) :: EigenV(0:4)
    real(kind=dp), intent(in)  :: energy
    integer :: m, n, o, nn, i
    real(kind=dp) :: stepp(1:3), DE(1:8)
    nn = 0
    do m = -1, 1, 2
      do n = -1, 1, 2
        do o = -1, 1, 2
          nn = nn + 1
          stepp(1) = step(1)*m
          stepp(2) = step(2)*n
          stepp(3) = step(3)*o
          ! Reciprocal lattice in inverse Ang
          stepp = matmul(recip_lattice, stepp)
          ! DE in eV
          DE(nn) = dot_product(grad, stepp)
        end do
      end do
    end do
    ! Yes this is a hack to the sorter to work the right way around.
    DE = -DE
    call heap_sort(8, DE)
    DE = -DE
    ! WHY ARE WE STORING ALL THIS?
    !EV(0,ib,is,ik) = band_energy(ib,is,ik)
    !EV(1,ib,is,ik) = EV(0,ib,is,ik) + DE(5)
    !EV(2,ib,is,ik) = EV(0,ib,is,ik) + DE(6)
    !EV(3,ib,is,ik) = EV(0,ib,is,ik) + DE(7)
    !EV(4,ib,is,ik) = EV(0,ib,is,ik) + DE(8)
    EigenV(0) = Energy
    do i = 1, 4
      EigenV(i) = EigenV(0) + DE(4 + i)
    end do
  end subroutine doslin_sub_cell_corners
Call graph
doslin_sub_cell_corners calls heap_sort
calculate_jdos calls doslin_sub_cell_corners
jdos_utils_calculate calls calculate_jdos
jdos_calculate calls jdos_utils_calculate
optics_calculate calls jdos_utils_calculate
optados calls jdos_calculate, optics_calculate