elec_pdos_read – OptaDOS
elec_pdos_read Subroutine
116 statements
Source File
public subroutine elec_pdos_read()
Uses
od_comms
od_cell
od_parameters
od_io
Arguments
None
Calls
Called by
Contents
Source Code
elec_pdos_read
Source Code
  subroutine elec_pdos_read
    !=========================================================================
    ! Read in the full pdos_weights. Write out any variables that we find on the
    ! way. These will be checked for consistency in the dos module. We can't do it
    ! yet as we haven't read the bands file.
    !-------------------------------------------------------------------------
    ! Arguments: None
    !-------------------------------------------------------------------------
    ! Parent module variables: pw, pdos_weights, pdos_orbital
    !-------------------------------------------------------------------------
    ! Modules used:  See below
    !-------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------
    ! Necessary conditions: None
    !-------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------
    ! Written by  A J Morris                                         Dec 2010
    !=========================================================================
    use od_comms, only: comms_bcast, comms_send, comms_recv, num_nodes, my_node_id,&
        & on_root, root_id
    use od_io, only: stdout, io_file_unit, io_error, seedname, filename_len
    use od_cell, only: num_kpoints_on_node
    use od_parameters, only: legacy_file_format, devel_flag, iprint
    implicit none
    ! Band indices used in the read-in of the pdos
    real(kind=dp)                        :: dummyr1, dummyr2, dummyr3
    integer                              :: dummyi, ib, ik, is
    integer                              :: pdos_in_unit, ierr, inodes
    logical                              :: full_debug_pdos_weights = .false.
    character(filename_len) :: pdos_filename
    real(kind=dp) :: time0, time1, file_version
    real(kind=dp), parameter :: file_ver = 1.0_dp
    if (allocated(pdos_weights)) return
    !-------------------------------------------------------------------------!
    ! R E A D   T H E   D A T A   H E A D E R
    if (on_root) then
      pdos_in_unit = io_file_unit()
      if (index(devel_flag, 'old_filename') > 0 .or. legacy_file_format) then
        pdos_filename = trim(seedname)//".pdos_weights"
        if (iprint > 1) write (stdout, '(1x,a)') 'Reading pdos weights from file: '//trim(pdos_filename)
        open (unit=pdos_in_unit, file=pdos_filename, form='unformatted', err=100, status='old')
      else
        pdos_filename = trim(seedname)//".pdos_bin"
        if (iprint > 1) write (stdout, '(1x,a)') 'Reading pdos weights from file: '//trim(pdos_filename)
        open (unit=pdos_in_unit, file=pdos_filename, status="old", form='unformatted', err=102)
        read (pdos_in_unit) file_version
        if ((file_version - file_ver) > 0.001_dp) &
          call io_error('Error: Trying to read newer version of pdos_bin file. Update optados!')
        read (pdos_in_unit) pdosfile_header
        if (iprint > 1) write (stdout, '(1x,a)') trim(pdosfile_header)
      end if
      read (pdos_in_unit) pdos_mwab%nkpoints
      read (pdos_in_unit) pdos_mwab%nspins
      read (pdos_in_unit) pdos_mwab%norbitals
      read (pdos_in_unit) pdos_mwab%nbands
      if (full_debug_pdos_weights) then
        write (stdout, *) " ***** F U L L _ D E B U G _ P D O S _ W E I G H T S ***** "
        write (stdout, *) "pdos_mwab%nkpoints= ", pdos_mwab%nkpoints
        write (stdout, *) "pdos_mwab%nspins= ", pdos_mwab%nspins
        write (stdout, *) "pdos_mwab%norbitals= ", pdos_mwab%norbitals
        write (stdout, *) "pdos_mwab%nbands= ", pdos_mwab%nbands
        write (stdout, *) "   **** ***** *****  ***** ***** *****  ***** ***** *****  "
      end if
      allocate (pdos_orbital%species_no(pdos_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(" Error : cannot allocate pdos_orbital")
      allocate (pdos_orbital%rank_in_species(pdos_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(" Error : cannot allocate pdos_orbital")
      allocate (pdos_orbital%am_channel(pdos_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(" Error : cannot allocate pdos_orbital")
      read (pdos_in_unit) pdos_orbital%species_no(1:pdos_mwab%norbitals)
      read (pdos_in_unit) pdos_orbital%rank_in_species(1:pdos_mwab%norbitals)
      read (pdos_in_unit) pdos_orbital%am_channel(1:pdos_mwab%norbitals)
      !-------------------------------------------------------------------------!
    end if
    call comms_bcast(pdos_mwab%norbitals, 1)
    call comms_bcast(pdos_mwab%nbands, 1)
    call comms_bcast(pdos_mwab%nkpoints, 1)
    call comms_bcast(pdos_mwab%nspins, 1)
    if (.not. on_root) then
      allocate (pdos_orbital%species_no(pdos_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(" Error : cannot allocate pdos_orbital")
      allocate (pdos_orbital%rank_in_species(pdos_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(" Error : cannot allocate pdos_orbital")
      allocate (pdos_orbital%am_channel(pdos_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(" Error : cannot allocate pdos_orbital")
    end if
    call comms_bcast(pdos_orbital%species_no(1), pdos_mwab%norbitals)
    call comms_bcast(pdos_orbital%rank_in_species(1), pdos_mwab%norbitals)
    call comms_bcast(pdos_orbital%am_channel(1), pdos_mwab%norbitals)
    !-------------------------------------------------------------------------!
    ! N O W   R E A D   T H E   D A T A
    allocate (nbands_occ(1:num_kpoints_on_node(my_node_id), 1:pdos_mwab%nspins), stat=ierr)
    if (ierr /= 0) stop " Error : cannot allocate nbands_occ"
    allocate (pdos_weights(1:pdos_mwab%norbitals, 1:pdos_mwab%nbands, &
                           1:num_kpoints_on_node(my_node_id), 1:pdos_mwab%nspins), stat=ierr)
    if (ierr /= 0) stop " Error : cannot allocate pdos_weights"
    if (on_root) then
      do inodes = 1, num_nodes - 1
        do ik = 1, num_kpoints_on_node(inodes)
          ! The kpoint number, followed by the kpoint-vector
          read (pdos_in_unit) dummyi, dummyr1, dummyr2, dummyr3
          do is = 1, pdos_mwab%nspins
            read (pdos_in_unit) dummyi ! this is the spin number
            read (pdos_in_unit) nbands_occ(ik, is)
            if (full_debug_pdos_weights) write(nbands_occ(ik,is))
            do ib = 1, nbands_occ(ik, is)
              if (full_debug_pdos_weights) then
                write (stdout, *) " ***** F U L L _ D E B U G _ P D O S _ W E I G H T S ***** "
                write (stdout, *) ib, ik, is
                write (stdout, *) "   **** ***** *****  ***** ***** *****  ***** ***** *****  "
              end if
              read (pdos_in_unit) pdos_weights(1:pdos_mwab%norbitals, ib, ik, is)
            end do
          end do
        end do
        call comms_send(pdos_weights(1, 1, 1, 1), pdos_mwab%norbitals*pdos_mwab%nbands* &
                        nspins*num_kpoints_on_node(inodes), inodes)
      end do
      do ik = 1, num_kpoints_on_node(0)
        ! The kpoint number, followed by the kpoint-vector
        read (pdos_in_unit) dummyi, dummyr1, dummyr2, dummyr3
        do is = 1, pdos_mwab%nspins
          read (pdos_in_unit) dummyi ! this is the spin number
          read (pdos_in_unit) nbands_occ(ik, is)
          if (full_debug_pdos_weights) write (stdout,*) nbands_occ(ik,is)
          do ib = 1, nbands_occ(ik, is)
            if (full_debug_pdos_weights) then
              write (stdout, *) " ***** F U L L _ D E B U G _ P D O S _ W E I G H T S ***** "
              write (stdout, *) ib, ik, is
              write (stdout, *) "   **** ***** *****  ***** ***** *****  ***** ***** *****  "
            end if
            read (pdos_in_unit) pdos_weights(1:pdos_mwab%norbitals, ib, ik, is)
            if (full_debug_pdos_weights) write (stdout, *) pdos_weights(1:pdos_mwab%norbitals, ib, ik, is)
          end do
        end do
      end do
    end if
    if (.not. on_root) then
      call comms_recv(pdos_weights(1, 1, 1, 1), pdos_mwab%norbitals*pdos_mwab%nbands* &
                      nspins*num_kpoints_on_node(my_node_id), root_id)
    end if
    if (on_root) close (pdos_in_unit)
    return
100 call io_error('Error: Problem opening pdos_weights file in elec_pdos_read')
102 call io_error('Error: Problem opening pdos_bin file in elec_pdos_read')
  end subroutine elec_pdos_read
Call graph
elec_pdos_read calls io_file_unit, comms_bcast, comms_recv, comms_send, io_error
pdos_calculate calls elec_pdos_read
read_pdos_bin calls elec_pdos_read
optados calls pdos_calculate
od2od calls read_pdos_bin