elec_read_band_gradient – OptaDOS
elec_read_band_gradient Subroutine
85 statements
Source File
public subroutine elec_read_band_gradient()
Uses
od_algorithms
od_parameters
od_comms
od_cell
od_constants
od_io
Arguments
None
Calls
Called by
Contents
Source Code
elec_read_band_gradient
Source Code
  subroutine elec_read_band_gradient
    !=========================================================================
    ! Read the .cst_ome file in paralell if appropriate. These are the
    ! gradients of the bands at each kpoint.
    !-------------------------------------------------------------------------
    ! Arguments: None
    !-------------------------------------------------------------------------
    ! Parent module variables: band_gradient,nspins,nbands
    !-------------------------------------------------------------------------
    ! Modules used:  See below
    !-------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------
    ! Necessary conditions: None
    !-------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------
    ! Written by  A J Morris                                         Dec 2010
    !=========================================================================
    use od_comms, only: on_root, my_node_id, num_nodes, root_id,&
         & comms_recv, comms_send, comms_bcast
    use od_io, only: io_time, filename_len, seedname, stdout, io_file_unit,&
         & io_error
    use od_cell, only: num_kpoints_on_node, nkpoints
    use od_constants, only: bohr2ang, H2eV
    use od_parameters, only: legacy_file_format, iprint, devel_flag
    use od_algorithms, only: algor_dist_array
    implicit none
    integer :: gradient_unit, i, ib, jb, is, ik, inodes, ierr, loop
    character(filename_len) :: gradient_filename
    logical :: exists
    real(kind=dp) :: time0, time1, file_version
    real(kind=dp), parameter :: file_ver = 1.0_dp
    ! Check that we haven't already done this.
    if (allocated(band_gradient)) return
    ! first try to read a velocity file
    if (index(devel_flag, 'old_filename') > 0 .or. legacy_file_format) then
      gradient_filename = trim(seedname)//".cst_vel"
    else
      gradient_filename = trim(seedname)//".dome_bin"
    end if
    if (on_root) inquire (file=gradient_filename, exist=exists)
    call comms_bcast(exists, 1)
    if (exists) then  ! good. We are reading from a velocity file
      time0 = io_time()
      if (on_root) then
        !if (iprint > 1) write (stdout, '(a)') ' '
        if (iprint > 1) write (stdout, '(a)') ' Reading band gradients from file: '//trim(gradient_filename)
        gradient_unit = io_file_unit()
        if (index(devel_flag, 'old_filename') > 0 .or. legacy_file_format) then
          gradient_filename = trim(seedname)//".cst_vel"
          open (unit=gradient_unit, file=gradient_filename, status="old", form='unformatted', err=101)
        else
          gradient_filename = trim(seedname)//".dome_bin"
          open (unit=gradient_unit, file=gradient_filename, status="old", form='unformatted', err=102)
          read (gradient_unit) file_version
          if ((file_version - file_ver) > 0.001_dp) &
            call io_error('Error: Trying to read newer version of dome_bin file. Update optados!')
          read (gradient_unit) domefile_header
          if (iprint > 1) write (stdout, '(1x,a)') trim(domefile_header)
        end if
      end if
      ! Figure out how many kpoint should be on each node
      call algor_dist_array(nkpoints, num_kpoints_on_node)
      allocate (band_gradient(1:nbands, 1:3, 1:num_kpoints_on_node(my_node_id), 1:nspins), stat=ierr)
      if (ierr /= 0) call io_error('Error: Problem allocating band_gradient in elec_read_band_gradient')
      band_gradient = 0.0_dp
      if (on_root) then
        do inodes = 1, num_nodes - 1
          do ik = 1, num_kpoints_on_node(inodes)
            do is = 1, nspins
              read (gradient_unit) ((band_gradient(ib, i, ik, is), ib=1, nbands), i=1, 3)
            end do
          end do
          call comms_send(band_gradient(1, 1, 1, 1), nbands*3*nspins*num_kpoints_on_node(inodes), inodes)
        end do
        do ik = 1, num_kpoints_on_node(0)
          do is = 1, nspins
            read (gradient_unit) ((band_gradient(ib, i, ik, is), ib=1, nbands), i=1, 3)
          end do
        end do
      end if
      if (.not. on_root) then
        call comms_recv(band_gradient(1, 1, 1, 1), nbands*3*nspins*num_kpoints_on_node(my_node_id), root_id)
      end if
!        write(*,*) "I'm node", my_node_id, "k-pts:", num_kpoints_on_node(my_node_id),"bgarray:", &
!& size(band_gradient), "or:", nbands*3*nspins*num_kpoints_on_node(my_node_id)
      if (on_root) close (unit=gradient_unit)
      ! Convert all band gradients to eV Ang
      band_gradient = band_gradient*bohr2ang*H2eV
      time1 = io_time()
      if (on_root .and. iprint > 1) then
        write (stdout, '(1x,a30,29x,f11.3,a8)') '+ Time to read band gradients ', time1 - time0, ' (sec) +'
      end if
    else ! lets try to get the data from the cst_ome file
      allocate (band_gradient(1:nbands, 1:3, 1:num_kpoints_on_node(my_node_id), 1:nspins), stat=ierr)
      if (ierr /= 0) call io_error('Error: Problem allocating band_gradient (b) in elec_read_band_gradient')
      if (allocated(optical_mat)) then
        do loop = 1, nbands
          band_gradient(loop, :, :, :) = real(optical_mat(loop, loop, :, :, :), dp)
        end do
      else
        call elec_read_optical_mat
        do loop = 1, nbands
          band_gradient(loop, :, :, :) = real(optical_mat(loop, loop, :, :, :), dp)
        end do
        call elec_dealloc_optical  ! given that it is a large matrix we'll let it go
        ! potentially that means reading it twice...
      end if
    end if
    return
101 call io_error('Error: Problem opening cst_vel file in read_band_gradient')
102 call io_error('Error: Problem opening dome_bin file in read_band_gradient')
  end subroutine elec_read_band_gradient
Call graph
elec_read_band_gradient calls comms_bcast, io_time, io_error, algor_dist_array, io_file_unit, comms_send, comms_recv, elec_read_optical_mat, elec_dealloc_optical
algor_dist_array calls io_error
elec_read_optical_mat calls io_time, io_error, algor_dist_array, io_file_unit, comms_send, comms_recv
elec_dealloc_optical calls io_error
dos_utils_calculate calls elec_read_band_gradient
jdos_utils_calculate calls elec_read_band_gradient, dos_utils_set_efermi
dos_utils_calculate_at_e calls elec_read_band_gradient
read_dome_bin calls elec_read_band_gradient
pdos_calculate calls dos_utils_calculate, dos_utils_set_efermi
core_calculate calls dos_utils_calculate, dos_utils_set_efermi
dos_utils_set_efermi calls dos_utils_calculate
jdos_calculate calls jdos_utils_calculate
dos_calculate calls dos_utils_calculate, dos_utils_set_efermi, dos_utils_compute_dos_at_efermi
optics_calculate calls jdos_utils_calculate, dos_utils_calculate_at_e, dos_utils_set_efermi
dos_utils_compute_dos_at_efermi calls dos_utils_calculate_at_e
od2od calls read_dome_bin
optados calls pdos_calculate, core_calculate, jdos_calculate, dos_calculate, optics_calculate