elec_read_band_curvature – OptaDOS
elec_read_band_curvature Subroutine
73 statements
Source File
public subroutine elec_read_band_curvature()
Uses
od_algorithms
od_parameters
od_comms
od_cell
od_constants
od_io
Arguments
None
Calls
Contents
Source Code
elec_read_band_curvature
Source Code
  subroutine elec_read_band_curvature
    !=========================================================================
    ! Read the .ddome file in paralell if appropriate. These are the
    ! curvatures of the bands at each kpoint.
    !-------------------------------------------------------------------------
    ! Arguments: None
    !-------------------------------------------------------------------------
    ! Parent module variables: band_curvature,nspins,nbands
    !-------------------------------------------------------------------------
    ! Modules used:  See below
    !-------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------
    ! Necessary conditions: None
    !-------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------
    ! Written by  V Chang                                             Nov 2020
    !=========================================================================
    use od_comms, only: on_root, my_node_id, num_nodes, root_id,&
         & comms_recv, comms_send, comms_bcast
    use od_io, only: io_time, filename_len, seedname, stdout, io_file_unit,&
         & io_error
    use od_cell, only: num_kpoints_on_node, nkpoints
    use od_constants, only: bohr2ang, H2eV
    use od_parameters, only: legacy_file_format, iprint, devel_flag
    use od_algorithms, only: algor_dist_array
    implicit none
    integer :: curvature_unit, i, j, ib, jb, is, ik, inodes, ierr, loop
    character(filename_len) :: curvature_filename
    character(len=80)       :: header
    logical :: exists
    real(kind=dp) :: time0, time1, file_version
    real(kind=dp), parameter :: file_ver = 1.0_dp
    ! Check that we haven't already done this.
    if (allocated(band_curvature)) return
    ! first try to read a effective mass file
    curvature_filename = trim(seedname)//".ddome_bin"
    if (on_root) inquire (file=curvature_filename, exist=exists)
    call comms_bcast(exists, 1)
    if (exists) then  ! good. We are reading from a velocity file
      time0 = io_time()
      if (on_root) then
        if (iprint > 1) write (stdout, '(a)') ' '
        if (iprint > 1) write (stdout, '(a)') ' Reading band curvature from file:'//trim(curvature_filename)
        curvature_unit = io_file_unit()
        curvature_filename = trim(seedname)//".ddome_bin"
        open (unit=curvature_unit, file=curvature_filename, status="old", form='unformatted', err=102)
        read (curvature_unit) file_version
        if ((file_version - file_ver) > 0.001_dp) &
          call io_error('Error: Trying to read newer version of ddome_bin file. Update optados!')
        read (curvature_unit) femfile_header
        if (iprint > 1) write (stdout, *) trim(femfile_header)
      end if
      ! Figure out how many kpoint should be on each node
      call algor_dist_array(nkpoints, num_kpoints_on_node)
      allocate (band_curvature(1:nbands, 1:3, 1:3, 1:num_kpoints_on_node(my_node_id), 1:nspins), stat=ierr)
      if (ierr /= 0) call io_error('Error: Problem allocating band_curvature in elec_read_band_curvature')
      if (on_root) then
        do inodes = 1, num_nodes - 1
          do ik = 1, num_kpoints_on_node(inodes)
            do is = 1, nspins
              do ib = 1, nbands
                do i = 1, 3
                  do j = 1, 3
                    read (curvature_unit) band_curvature(ib, i, j, ik, is)
                  end do
                end do
              end do
            end do
          end do
          call comms_send(band_curvature(1, 1, 1, 1, 1), nbands*3*3*nspins*num_kpoints_on_node(inodes), inodes)
        end do
        do ik = 1, num_kpoints_on_node(0)
          do is = 1, nspins
            do ib = 1, nbands
              do i = 1, 3
                do j = 1, 3
                  read (curvature_unit) band_curvature(ib, i, j, ik, is)
                end do
              end do
            end do
          end do
        end do
      end if
      if (.not. on_root) then
        call comms_recv(band_curvature(1, 1, 1, 1, 1), nbands*3*3*nspins*num_kpoints_on_node(my_node_id), root_id)
      end if
      if (on_root) close (unit=curvature_unit)
      ! Convert all band curvatures to eV Ang^2
      band_curvature = band_curvature*bohr2ang*bohr2ang*H2eV
      time1 = io_time()
      if (on_root .and. iprint > 1) write (stdout, '(1x,a40,f11.3,a)') 'Time to read band curvature', time1 - time0, ' (sec)'
    end if
    return
101 call io_error('Error: Problem opening cst_vel file in read_band_curvature')
102 call io_error('Error: Problem opening dome_bin file in read_band_curvature')
  end subroutine elec_read_band_curvature
Call graph
elec_read_band_curvature calls comms_bcast, io_time, io_error, algor_dist_array, io_file_unit, comms_send, comms_recv
algor_dist_array calls io_error