elec_elnes_find_channel_numbers – OptaDOS
elec_elnes_find_channel_numbers Subroutine
43 statements
Source File
public subroutine elec_elnes_find_channel_numbers()
Uses
od_io
Arguments
None
Calls
Called by
Contents
Source Code
elec_elnes_find_channel_numbers
Source Code
  subroutine elec_elnes_find_channel_numbers
    !=========================================================================
    !
    ! The elnes_bin has channel numbers 1-16 internally optados thinks about
    ! channel names. So we need to be able to go back and forth.
    !
    ! CASTEP (hence the bin file) and OptaDOS think about am_channel numbers
    ! differently. To keep consistent we convert to CASTEP's numbering scheme
    ! before we write out.
    ! AJM 5/12/2019
    use od_io, only: io_error
    implicit none
    integer :: loop
    do loop = 1, elnes_mwab%norbitals
      selectcase (trim(elnes_orbital%am_channel_name(loop)))
      case ('s')
        elnes_orbital%am_channel(loop) = 1
      case ('px')
        elnes_orbital%am_channel(loop) = 2
      case ('py')
        elnes_orbital%am_channel(loop) = 3
      case ('pz')
        elnes_orbital%am_channel(loop) = 4
      case ('dzz')
        elnes_orbital%am_channel(loop) = 5
      case ('dzy')
        elnes_orbital%am_channel(loop) = 6
      case ('dzx')
        elnes_orbital%am_channel(loop) = 7
      case ('dxx-yy')
        elnes_orbital%am_channel(loop) = 8
      case ('dxy')
        elnes_orbital%am_channel(loop) = 9
      case ('fxxx')
        elnes_orbital%am_channel(loop) = 10
      case ('fyyy')
        elnes_orbital%am_channel(loop) = 11
      case ('fzzz')
        elnes_orbital%am_channel(loop) = 12
      case ('fxyz')
        elnes_orbital%am_channel(loop) = 13
      case ('fz(xx-yy)')
        elnes_orbital%am_channel(loop) = 14
      case ('fy(zz-xx)')
        elnes_orbital%am_channel(loop) = 15
      case ('fx(yy-zz)')
        elnes_orbital%am_channel(loop) = 16
      case default
        call io_error(' Error : unknown angular momentum state in elec_elnes_find_channel_numbers')
      end select
    end do
  end subroutine elec_elnes_find_channel_numbers
Call graph
elec_elnes_find_channel_numbers calls selectcase, io_error
write_elnes_bin calls elec_elnes_find_channel_numbers
write_elnes_fmt calls elec_elnes_find_channel_numbers
od2od calls write_elnes_bin, write_elnes_fmt