elec_dealloc_optical – OptaDOS
elec_dealloc_optical Subroutine
9 statements
Source File
public subroutine elec_dealloc_optical()
Uses
od_io
Arguments
None
Calls
Called by
Contents
Source Code
elec_dealloc_optical
Source Code
  subroutine elec_dealloc_optical
    use od_io, only: io_error
    implicit none
    integer :: ierr
    if (allocated(optical_mat)) then
      deallocate (optical_mat, stat=ierr)
      if (ierr /= 0) call io_error('Error in deallocating optical_mat in elec_dealloc_optical')
    end if
  end subroutine elec_dealloc_optical
Call graph
elec_dealloc_optical calls io_error
elec_read_band_gradient calls elec_dealloc_optical
optics_calculate calls elec_dealloc_optical, jdos_utils_calculate, dos_utils_calculate_at_e, dos_utils_set_efermi
dos_utils_calculate calls elec_read_band_gradient
jdos_utils_calculate calls elec_read_band_gradient, dos_utils_set_efermi
dos_utils_calculate_at_e calls elec_read_band_gradient
read_dome_bin calls elec_read_band_gradient
optados calls optics_calculate, pdos_calculate, core_calculate, jdos_calculate, dos_calculate
pdos_calculate calls dos_utils_calculate, dos_utils_set_efermi
core_calculate calls dos_utils_calculate, dos_utils_set_efermi
dos_utils_set_efermi calls dos_utils_calculate
jdos_calculate calls jdos_utils_calculate
dos_calculate calls dos_utils_calculate, dos_utils_set_efermi, dos_utils_compute_dos_at_efermi
dos_utils_compute_dos_at_efermi calls dos_utils_calculate_at_e
od2od calls read_dome_bin