elec_read_optical_mat – OptaDOS
elec_read_optical_mat Subroutine
95 statements
Source File
public subroutine elec_read_optical_mat()
Uses
od_algorithms
od_parameters
od_comms
od_cell
od_constants
od_io
Arguments
None
Calls
Called by
Contents
Source Code
elec_read_optical_mat
Source Code
  subroutine elec_read_optical_mat
    !=========================================================================
    ! Read the .cst_ome file in paralell if appropriate. These are the
    ! gradients of the bands at each kpoint.
    !-------------------------------------------------------------------------
    ! Arguments: None
    !-------------------------------------------------------------------------
    ! Parent module variables: band_gradient,nspins,nbands
    !-------------------------------------------------------------------------
    ! Modules used:  See below
    !-------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------
    ! Necessary conditions: None
    !-------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------
    ! Written by  A J Morris                                         Dec 2010
    !=========================================================================
    use od_comms, only: on_root, my_node_id, num_nodes, root_id,&
         & comms_recv, comms_send
    use od_io, only: io_time, filename_len, seedname, stdout, io_file_unit,&
         & io_error
    use od_cell, only: num_kpoints_on_node, nkpoints
    use od_constants, only: bohr2ang, H2eV
    use od_parameters, only: legacy_file_format, iprint, devel_flag
    use od_algorithms, only: algor_dist_array
    implicit none
    integer :: gradient_unit, i, ib, jb, is, ik, inodes, ierr
    character(filename_len) :: gradient_filename
    real(kind=dp) :: time0, time1, file_version
    real(kind=dp), parameter :: file_ver = 1.0_dp
    ! Check that we haven't already done this.
    if (allocated(optical_mat)) return
    time0 = io_time()
    if (on_root) then
      gradient_unit = io_file_unit()
      if (index(devel_flag, 'old_filename') > 0 .or. legacy_file_format) then
        gradient_filename = trim(seedname)//".cst_ome"
        if (iprint > 1) write (stdout, '(1x,a)') 'Reading optical matrix elements from file: '//trim(gradient_filename)
        open (unit=gradient_unit, file=gradient_filename, status="old", form='unformatted', err=101)
      else
        gradient_filename = trim(seedname)//".ome_bin"
        if (iprint > 1) write (stdout, '(1x,a)') 'Reading optical matrix elements from file: '//trim(gradient_filename)
        open (unit=gradient_unit, file=gradient_filename, status="old", form='unformatted', err=102)
        read (gradient_unit) file_version
        if ((file_version - file_ver) > 0.001_dp) &
          call io_error('Error: Trying to read newer version of ome_bin file. Update optados!')
        read (gradient_unit) omefile_header
        if (iprint > 1) write (stdout, '(1x,a)') trim(omefile_header)
      end if
    end if
    ! Figure out how many kpoints should be on each node
    call algor_dist_array(nkpoints, num_kpoints_on_node)
    allocate (optical_mat(1:nbands, 1:nbands, 1:3, 1:num_kpoints_on_node(my_node_id), 1:nspins), stat=ierr)
    if (ierr /= 0) call io_error('Error: Problem allocating optical_mat in elec_read_optical_mat')
    if (legacy_file_format) then
      if (on_root) then
        do inodes = 1, num_nodes - 1
          do ik = 1, num_kpoints_on_node(inodes)
            do is = 1, nspins
              do i = 1, 3
                do jb = 1, nbands
                  do ib = 1, nbands
                    ! Read in units of Ha Bohr^2 / Ang
                    read (gradient_unit) optical_mat(ib, jb, i, ik, is)
                  end do
                end do
              end do
            end do
          end do
          call comms_send(optical_mat(1, 1, 1, 1, 1), nbands*nbands*3*nspins*num_kpoints_on_node(inodes), inodes)
        end do
        do ik = 1, num_kpoints_on_node(0)
          do is = 1, nspins
            do i = 1, 3
              do jb = 1, nbands
                do ib = 1, nbands
                  ! Read in units of Ha Bohr^2 / Ang
                  read (gradient_unit) optical_mat(ib, jb, i, ik, is)
                end do
              end do
            end do
          end do
        end do
      end if
    else ! sane file format
      if (on_root) then
        do inodes = 1, num_nodes - 1
          do ik = 1, num_kpoints_on_node(inodes)
            do is = 1, nspins
              read (gradient_unit) (((optical_mat(ib, jb, i, ik, is), ib=1, nbands) &
                                     , jb=1, nbands), i=1, 3)
            end do
          end do
          call comms_send(optical_mat(1, 1, 1, 1, 1), nbands*nbands*3*nspins*num_kpoints_on_node(inodes), inodes)
        end do
        do ik = 1, num_kpoints_on_node(0)
          do is = 1, nspins
            read (gradient_unit) (((optical_mat(ib, jb, i, ik, is), ib=1, nbands), jb=1, nbands), i=1, 3)
          end do
        end do
      end if
    end if
    if (.not. on_root) then
      call comms_recv(optical_mat(1, 1, 1, 1, 1), nbands*nbands*3*nspins*num_kpoints_on_node(my_node_id), root_id)
    end if
    if (on_root) close (unit=gradient_unit)
    ! Convert all band gradients to eV Ang
    if (legacy_file_format) then
      optical_mat = optical_mat*bohr2ang*bohr2ang*H2eV
    else
      optical_mat = optical_mat*bohr2ang*H2eV
    end if
    time1 = io_time()
    if (on_root .and. iprint > 1) then
      write (stdout, '(1x,a59,f11.3,a8)') &
           '+ Time to read Optical Matrix Elements                   &
           &      ', time1 - time0, ' (sec) +'
    end if
    return
101 call io_error('Error: Problem opening cst_ome file in read_band_optical_mat')
102 call io_error('Error: Problem opening ome_bin file in read_band_optical_mat')
  end subroutine elec_read_optical_mat
Call graph
elec_read_optical_mat calls io_time, io_file_unit, algor_dist_array, comms_send, io_error, comms_recv
algor_dist_array calls io_error
elec_read_band_gradient calls elec_read_optical_mat
read_ome_bin calls elec_read_optical_mat
optics_calculate calls elec_read_optical_mat, jdos_utils_calculate, dos_utils_calculate_at_e, dos_utils_set_efermi
dos_utils_calculate calls elec_read_band_gradient
jdos_utils_calculate calls elec_read_band_gradient, dos_utils_set_efermi
od2od calls read_ome_bin, read_dome_bin
dos_utils_calculate_at_e calls elec_read_band_gradient
read_dome_bin calls elec_read_band_gradient
optados calls optics_calculate, pdos_calculate, core_calculate, jdos_calculate, dos_calculate
pdos_calculate calls dos_utils_calculate, dos_utils_set_efermi
core_calculate calls dos_utils_calculate, dos_utils_set_efermi
dos_utils_set_efermi calls dos_utils_calculate
jdos_calculate calls jdos_utils_calculate
dos_calculate calls dos_utils_calculate, dos_utils_set_efermi, dos_utils_compute_dos_at_efermi
dos_utils_compute_dos_at_efermi calls dos_utils_calculate_at_e