elec_read_band_energy_ordered – OptaDOS
elec_read_band_energy_ordered Subroutine
135 statements
Source File
public subroutine elec_read_band_energy_ordered()
Uses
od_algorithms
od_parameters
od_comms
od_cell
od_constants
od_io
Arguments
None
Calls
Called by
Contents
Source Code
elec_read_band_energy_ordered
Source Code
  subroutine elec_read_band_energy_ordered !(band_energy,kpoint_r,kpoint_weight)
    !=========================================================================
    ! Read the .bands file in the kpoint list, kpoint weights and band energies
    ! also obtain, nkpoints, nspins, num_electrons(:),nbands, efermi_castep
    ! in the correct order.
    !-------------------------------------------------------------------------
    ! Arguments: None
    !-------------------------------------------------------------------------
    ! Parent module variables: band_energy, efermi_castep, num_electrons
    ! spin_polarised, electrons_per_state, nspins,nbands
    !-------------------------------------------------------------------------
    ! Modules used:  See below
    !-------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------
    ! Necessary conditions: None
    !-------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------
    ! Written by  A J Morris                                         Dec 2010
    !=========================================================================
    use od_constants, only: H2eV
    use od_cell, only: nkpoints, kpoint_r, kpoint_weight, cell_find_MP_grid,&
         & real_lattice, kpoint_grid_dim, num_kpoints_on_node
    use od_comms, only: comms_bcast, comms_send, comms_recv, num_nodes, my_node_id,&
         & on_root, root_id
    use od_io, only: io_file_unit, seedname, filename_len, stdout, io_time,&
         & io_error
    use od_algorithms, only: algor_dist_array
    use od_parameters, only: iprint, compute_band_gap, kpoint_mp_grid, pdis
    implicit none
    integer :: inodes, ik, is, ib, band_unit, iall_kpoints, i
    integer :: ik_bandfile, ierr, str_pos
    character(filename_len) :: band_filename
    character(len=80) :: dummy
    real(kind=dp) :: time0, time1
    real(kind=dp), allocatable :: all_band_energy(:, :, :)
    real(kind=dp) :: dummy_kpt(4)
    time0 = io_time()
    ! Check that we haven't already read in the energies
    if (allocated(band_energy)) return
    !Open the bands file
    band_unit = io_file_unit()
    band_filename = trim(seedname)//".bands"
    ! Read the header from the bands file
    if (on_root) then
      open (unit=band_unit, file=band_filename, status="old", form='formatted', err=100)
      read (band_unit, '(a)') dummy
      str_pos = index(dummy, 'k-points')
      read (dummy(str_pos + 8:), *) nkpoints
      read (band_unit, '(a)') dummy
      str_pos = index(dummy, 'components')
      read (dummy(str_pos + 10:), *) nspins
      read (band_unit, '(a)') dummy
      allocate (num_electrons(nspins), stat=ierr)
      if (ierr /= 0) stop " Error : cannot allocate num_electrons"
      str_pos = index(dummy, 'electrons')
      read (dummy(str_pos + 10:), *) num_electrons(:)
      read (band_unit, '(a)') dummy
      str_pos = index(dummy, 'eigenvalues')
      read (dummy(str_pos + 11:), *) nbands
      read (band_unit, '(a)') dummy
      str_pos = index(dummy, 'units)')
      read (dummy(str_pos + 6:), '(f12.4)') efermi_castep
      read (band_unit, '(a)') dummy
      read (band_unit, *) real_lattice(:, 1)
      read (band_unit, *) real_lattice(:, 2)
      read (band_unit, *) real_lattice(:, 3)
    end if
    call comms_bcast(nspins, 1)
    if (.not. on_root) then
      allocate (num_electrons(nspins), stat=ierr)
      if (ierr /= 0) stop " Error : cannot allocate num_electrons"
    end if
    call comms_bcast(num_electrons(1), nspins)
    call comms_bcast(nkpoints, 1)
    call comms_bcast(nbands, 1)
    call comms_bcast(efermi_castep, 1)
    !
    call algor_dist_array(nkpoints, num_kpoints_on_node)
    !
    allocate (band_energy(1:nbands, 1:nspins, 1:num_kpoints_on_node(0)), stat=ierr)
    if (ierr /= 0) call io_error('Error: Problem allocating band_energy in read_band_energy')
    allocate (all_band_energy(1:nbands, 1:nspins, 1:nkpoints), stat=ierr)
    if (ierr /= 0) call io_error('Error: Problem allocating all_band_energy in read_band_energy')
    allocate (kpoint_weight(1:num_kpoints_on_node(0)), stat=ierr)
    if (ierr /= 0) call io_error('Error: Problem allocating kpoint_weight in read_band_energy')
    allocate (kpoint_r(1:3, 1:num_kpoints_on_node(0)), stat=ierr)
    if (ierr /= 0) call io_error('Error: Problem allocating kpoint_r in read_band_energy')
    if (on_root) then
      allocate (all_kpoints(1:3, nkpoints), stat=ierr)
      allocate (all_kpoint_weight(nkpoints), stat=ierr)
      if (ierr /= 0) call io_error('Error: Problem allocating all_kpoints in read_band_energy')
      do ik = 1, nkpoints
        read (band_unit, '(a)') dummy
        str_pos = index(dummy, 'K-point')
        dummy_kpt = 0
        read (dummy(str_pos + 7:), *) ik_bandfile, dummy_kpt(1), dummy_kpt(2), dummy_kpt(4)
        do i = 1, 3
          all_kpoints(i, ik_bandfile) = dummy_kpt(i)
        end do
        all_kpoint_weight(ik_bandfile) = dummy_kpt(4)
        do is = 1, nspins
          read (band_unit, *) dummy
          do ib = 1, nbands
            read (band_unit, *) all_band_energy(ib, is, ik_bandfile) !NB spin <-> kpt swapped
          end do
        end do
      end do
      ! split bands across node-level arrays
      iall_kpoints = 0
      do inodes = 0, num_nodes - 1
        do ik = 1, num_kpoints_on_node(inodes)
          do i = 1, 3
            kpoint_r(i, ik) = all_kpoints(i, ik + iall_kpoints)
          end do
          kpoint_weight(ik) = all_kpoint_weight(ik + iall_kpoints)
          do is = 1, nspins
            do ib = 1, nbands
              band_energy(ib, is, ik) = all_band_energy(ib, is, ik + iall_kpoints) !NB spin <-> kpt swapped
            end do
          end do
        end do
        iall_kpoints = iall_kpoints + num_kpoints_on_node(inodes)
        ! distribute bands across kpoints
        if (inodes /= 0) then
          call comms_send(band_energy(1, 1, 1), nbands*nspins*num_kpoints_on_node(0), inodes)
          call comms_send(kpoint_r(1, 1), 3*num_kpoints_on_node(0), inodes)
          call comms_send(kpoint_weight(1), num_kpoints_on_node(0), inodes)
        end if
      end do
      ! Do this here so we can free up the all_kpoints memory, unless we need it to calculate
      ! the kpoints at the band-gap or do a pdispersion
      if (kpoint_mp_grid(1) > 0) then
        ! we must have set this manually
        kpoint_grid_dim = kpoint_mp_grid
      else
        call cell_find_MP_grid(all_kpoints, nkpoints, kpoint_grid_dim)
      end if
      if ((.not. compute_band_gap) .and. (.not. pdis)) then
        deallocate (all_kpoints, stat=ierr)
        if (ierr /= 0) call io_error('Error: Problem deallocating all_kpoints in read_band_energy')
        deallocate (all_band_energy, stat=ierr)
        if (ierr /= 0) call io_error('Error: Problem deallocating all_band_energy in read_band_energy')
        deallocate (all_kpoint_weight, stat=ierr)
        if (ierr /= 0) call io_error('Error: Problem deallocating all_kpoint_weight in read_band_energy')
      end if
    end if
    if (.not. on_root) then
      call comms_recv(band_energy(1, 1, 1), nbands*nspins*num_kpoints_on_node(0), root_id)
      call comms_recv(kpoint_r(1, 1), 3*num_kpoints_on_node(0), root_id)
      call comms_recv(kpoint_weight(1), num_kpoints_on_node(0), root_id)
    end if
    if (on_root) close (unit=band_unit)
    band_energy = band_energy*H2eV
    efermi_castep = efermi_castep*H2eV
    ! Things that follow
    if (nspins .lt. 2) then
      spin_polarised = .false.
      electrons_per_state = 2.0_dp
    else
      spin_polarised = .true.
      electrons_per_state = 1.0_dp
    end if
    time1 = io_time()
    if (on_root .and. iprint > 1) write (stdout, '(1x,a40,f11.3,a)') 'Time to read band energies  ', time1 - time0, ' (sec)'
    return
100 call io_error('Error: Problem opening bands file in read_band_energy')
  end subroutine elec_read_band_energy_ordered
Call graph
elec_read_band_energy_ordered calls io_time, io_file_unit, comms_bcast, algor_dist_array, io_error, comms_send, cell_find_mp_grid, comms_recv
algor_dist_array calls io_error
cell_find_mp_grid calls io_error
optados calls elec_read_band_energy_ordered