elec_read_elnes_mat – OptaDOS
elec_read_elnes_mat Subroutine
125 statements
Source File
public subroutine elec_read_elnes_mat()
Uses
od_comms
od_parameters
od_io
od_cell
Arguments
None
Calls
Called by
Contents
Source Code
elec_read_elnes_mat
Source Code
  subroutine elec_read_elnes_mat
    !=========================================================================
    ! Read the .bands file in the kpoint list, kpoint weights and band energies
    ! also obtain, nkpoints, nspins, num_electrons(:),nbands, efermi_castep
    !-------------------------------------------------------------------------
    ! Arguments: None
    !-------------------------------------------------------------------------
    ! Parent module variables: band_energy, efermi_castep, num_electrons
    ! spin_polarised, electrons_per_state, nspins,nbands
    !-------------------------------------------------------------------------
    ! Modules used:  See below
    !-------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------
    ! Necessary conditions: None
    !-------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------
    ! Written by  A J Morris                                         Dec 2010
    !=========================================================================
    use od_cell, only: num_kpoints_on_node
    use od_comms, only: comms_bcast, comms_send, comms_recv, num_nodes, my_node_id,&
         & on_root, root_id
    use od_io, only: io_file_unit, seedname, filename_len, io_time,&
         & io_error, stdout
    use od_parameters, only: legacy_file_format, devel_flag, iprint
    implicit none
    integer :: inodes, ik, ns, nb, indx
    integer :: ierr, elnes_unit, orb, loop
    character(filename_len) :: elnes_filename
    real(kind=dp) :: time0, time1, file_version
    real(kind=dp), parameter :: file_ver = 1.0_dp
    time0 = io_time()
    ! Check that we haven't already read in the energies
    if (allocated(elnes_mat)) return
    !Open the elnes sfile
    if (on_root) then
      elnes_unit = io_file_unit()
      if (index(devel_flag, 'old_filename') > 0 .or. legacy_file_format) then
        elnes_filename = trim(seedname)//".eels_mat"
        if (iprint > 1) write (stdout, '(1x,a)') 'Reading elnes matrix elements from file: '//trim(elnes_filename)
        open (unit=elnes_unit, file=elnes_filename, form='unformatted', err=100, status='old')
      else
        elnes_filename = trim(seedname)//".elnes_bin"
        if (iprint > 1) write (stdout, '(1x,a)') 'Reading elnes matrix elements from file: '//trim(elnes_filename)
        open (unit=elnes_unit, file=elnes_filename, status="old", form='unformatted', err=102)
        read (elnes_unit) file_version
        if ((file_version - file_ver) > 0.001_dp) &
          call io_error('Error: Trying to read newer version of elnes_bin file. Update optados!')
        read (elnes_unit) elnesfile_header
        if (iprint > 1) write (stdout, '(1x,a)') trim(elnesfile_header)
      end if
      read (elnes_unit) elnes_mwab%norbitals
      read (elnes_unit) elnes_mwab%nbands
      read (elnes_unit) elnes_mwab%nkpoints
      read (elnes_unit) elnes_mwab%nspins
      ! check these agree with band data?
      allocate (elnes_orbital%ion_no(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbital%ion_no')
      allocate (elnes_orbital%species_no(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbital%species_no')
      allocate (elnes_orbital%rank_in_species(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbitall%rank_in_species')
      allocate (elnes_orbital%shell(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbitall%shell')
      allocate (elnes_orbital%am_channel(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbital%am_channel')
      allocate (elnes_orbital%am_channel_name(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbital%am_channel_name')
      read (elnes_unit) elnes_orbital%species_no(1:elnes_mwab%norbitals)
      read (elnes_unit) elnes_orbital%rank_in_species(1:elnes_mwab%norbitals)
      read (elnes_unit) elnes_orbital%shell(1:elnes_mwab%norbitals)
      read (elnes_unit) elnes_orbital%am_channel(1:elnes_mwab%norbitals)
    end if
    call comms_bcast(elnes_mwab%norbitals, 1)
    call comms_bcast(elnes_mwab%nbands, 1)
    call comms_bcast(elnes_mwab%nkpoints, 1)
    call comms_bcast(elnes_mwab%nspins, 1)
    if (.not. on_root) then
      allocate (elnes_orbital%ion_no(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbital%ion_no')
      allocate (elnes_orbital%species_no(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbital%species_no')
      allocate (elnes_orbital%rank_in_species(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbitall%rank_in_species')
      allocate (elnes_orbital%shell(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbitall%shell')
      allocate (elnes_orbital%am_channel(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbital%am_channel')
      allocate (elnes_orbital%am_channel_name(elnes_mwab%norbitals), stat=ierr)
      if (ierr /= 0) call io_error(' Error : elec_read_elnes_mat cannot allocate elnes_orbital%am_channel_name')
    end if
    call comms_bcast(elnes_orbital%species_no(1), elnes_mwab%norbitals)
    call comms_bcast(elnes_orbital%rank_in_species(1), elnes_mwab%norbitals)
    call comms_bcast(elnes_orbital%shell(1), elnes_mwab%norbitals)
    call comms_bcast(elnes_orbital%am_channel(1), elnes_mwab%norbitals)
    ! assume same data distribution as bands
    allocate (elnes_mat(1:elnes_mwab%norbitals, 1:elnes_mwab%nbands, 1:3, &
                        1:num_kpoints_on_node(0), 1:elnes_mwab%nspins), stat=ierr)
    if (ierr /= 0) call io_error('Error: Problem allocating elnes_mat in elec_read_elnes_mat')
    if (on_root) then
      if (legacy_file_format) then
        do inodes = 1, num_nodes - 1
          do ik = 1, num_kpoints_on_node(inodes)
            do ns = 1, elnes_mwab%nspins
              do orb = 1, elnes_mwab%norbitals
                do nb = 1, elnes_mwab%nbands
                  read (elnes_unit) (elnes_mat(orb, nb, indx, ik, ns), indx=1, 3)
                end do
              end do
            end do
          end do
          call comms_send(elnes_mat(1, 1, 1, 1, 1), elnes_mwab%norbitals*elnes_mwab%nbands*3* &
                          nspins*num_kpoints_on_node(0), inodes)
        end do
        do ik = 1, num_kpoints_on_node(0)
          do ns = 1, elnes_mwab%nspins
            do orb = 1, elnes_mwab%norbitals
              do nb = 1, elnes_mwab%nbands
                read (elnes_unit) (elnes_mat(orb, nb, indx, ik, ns), indx=1, 3)
              end do
            end do
          end do
        end do
      else ! sane format
        do inodes = 1, num_nodes - 1
          do ik = 1, num_kpoints_on_node(inodes)
            do ns = 1, elnes_mwab%nspins
              read (elnes_unit) (((elnes_mat(orb, nb, indx, ik, ns), orb=1, elnes_mwab%norbitals), &
                                  nb=1, elnes_mwab%nbands), indx=1, 3)
            end do
          end do
          call comms_send(elnes_mat(1, 1, 1, 1, 1), elnes_mwab%norbitals*elnes_mwab%nbands*3*nspins* &
                          num_kpoints_on_node(0), inodes)
        end do
        do ik = 1, num_kpoints_on_node(0)
          do ns = 1, elnes_mwab%nspins
            read (elnes_unit) (((elnes_mat(orb, nb, indx, ik, ns), orb=1, elnes_mwab%norbitals), &
                                nb=1, elnes_mwab%nbands), indx=1, 3)
          end do
        end do
      end if
    end if
    if (.not. on_root) then
      call comms_recv(elnes_mat(1, 1, 1, 1, 1), elnes_mwab%norbitals*elnes_mwab%nbands*3*nspins* &
                      num_kpoints_on_node(0), root_id)
    end if
    if (on_root) close (elnes_unit)
    call elec_elnes_find_channel_names()
    time1 = io_time()
    if (on_root .and. iprint > 1) then
      write (stdout, '(1x,a59,f11.3,a8)') &
           '+ Time to read Elnes Matrix Elements                     &
           &      ', time1 - time0, ' (sec) +'
    end if
    return
100 call io_error('Error: Problem opening elnes file in elec_read_elnes_mat')
102 call io_error('Error: Problem opening elnes_bin file in elec_read_elnes_mat')
  end subroutine elec_read_elnes_mat
Call graph
elec_read_elnes_mat calls io_time, io_file_unit, comms_bcast, comms_send, io_error, comms_recv, elec_elnes_find_channel_names
elec_elnes_find_channel_names calls io_error
read_elnes_bin calls elec_read_elnes_mat
core_calculate calls elec_read_elnes_mat
od2od calls read_elnes_bin
optados calls core_calculate