elec_read_foptical_mat – OptaDOS
elec_read_foptical_mat Subroutine
113 statements
Source File
public subroutine elec_read_foptical_mat()
Uses
od_algorithms
od_parameters
od_comms
od_cell
od_constants
od_io
Arguments
None
Calls
Called by
Contents
Source Code
elec_read_foptical_mat
Source Code
  subroutine elec_read_foptical_mat
    !=========================================================================
    ! Read the .fem_bin file in paralell if appropriate. These are the
    ! free electron matrix at each kpoint.
    !-------------------------------------------------------------------------
    ! Arguments: None
    !-------------------------------------------------------------------------
    ! Parent module variables: foptical_mat,nspins,nbands
    !-------------------------------------------------------------------------
    ! Modules used:  See below
    !-------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------
    ! Necessary conditions: None
    !-------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------
    ! Written by  V Chang                                             Nov 2020
    !=========================================================================
    use od_comms, only: on_root, my_node_id, num_nodes, root_id,&
         & comms_recv, comms_send, comms_reduce
    use od_io, only: io_time, filename_len, seedname, stdout, io_file_unit,&
         & io_error
    use od_cell, only: num_kpoints_on_node, nkpoints, kpoint_r
    use od_constants, only: bohr2ang, H2eV
    use od_parameters, only: legacy_file_format, iprint, devel_flag
    use od_algorithms, only: algor_dist_array
    implicit none
    integer :: gradient_unit, i, ib, jb, is, ik, inodes, ierr, gam_unit = 23, inode = 0, ktmp
    character(filename_len) :: gradient_filename
    real(kind=dp) :: time0, time1, file_version, tolerance = 0.000001_dp
    real(kind=dp), parameter :: file_ver = 1.0_dp
    complex(kind=dp),dimension(:,:,:),allocatable :: foptical_mat_temp
    logical :: have_gamma = .False.
    ! Check that we haven't already done this.
    if (allocated(foptical_mat)) return
    time0 = io_time()
    if (on_root) then
      gradient_unit = io_file_unit()
      gradient_filename = trim(seedname)//".fem_bin"
      if (iprint > 1) write (stdout, '(1x,a)') 'Reading foptical matrix elements from file: '//trim(gradient_filename)
      open (unit=gradient_unit, file=gradient_filename, status="old", form='unformatted', err=102)
      read (gradient_unit) file_version
      if ((file_version - file_ver) > 0.001_dp) &
        call io_error('Error: Trying to read newer version of fem_bin file. Update optados!')
      read (gradient_unit) femfile_header
      if (iprint > 1) write (stdout, '(1x,a)') trim(femfile_header)
    end if
    ! Figure out how many kpoints should be on each node
    call algor_dist_array(nkpoints, num_kpoints_on_node)
    allocate (foptical_mat(1:nbands + 1, 1:nbands + 1, 1:3, 1:num_kpoints_on_node(my_node_id), 1:nspins), stat=ierr)
    if (ierr /= 0) call io_error('Error: Problem allocating foptical_mat in elec_read_optical_mat')
    if (on_root) then
      do inodes = 1, num_nodes - 1
        do ik = 1, num_kpoints_on_node(inodes)
          do is = 1, nspins
            read (gradient_unit) (((foptical_mat(ib, jb, i, ik, is), ib=1, nbands + 1) &
                                   , jb=1, nbands + 1), i=1, 3)
          end do
        end do
        call comms_send(foptical_mat(1, 1, 1, 1, 1), (nbands + 1)*(nbands + 1)*3*nspins*num_kpoints_on_node(inodes), inodes)
      end do
      do ik = 1, num_kpoints_on_node(0)
        do is = 1, nspins
          read (gradient_unit) (((foptical_mat(ib, jb, i, ik, is), ib=1, nbands + 1), jb=1, nbands + 1), i=1, 3)
        end do
      end do
    end if
    if (.not. on_root) then
      call comms_recv(foptical_mat(1, 1, 1, 1, 1), (nbands + 1)*(nbands + 1)*3*nspins*num_kpoints_on_node(my_node_id), root_id)
    end if
    if (on_root) close (unit=gradient_unit)
    ! Convert all band gradients to eV Ang
    if (legacy_file_format) then
      foptical_mat = foptical_mat*bohr2ang*bohr2ang*H2eV
    else
      foptical_mat = foptical_mat*bohr2ang*H2eV
    end if
    if (index(devel_flag,'write_gam_fome') .gt. 0) then
      do ik = 1, num_kpoints_on_node(my_node_id)
        if (kpoint_r(1,ik) .lt. tolerance .and. kpoint_r(2,ik) .lt. tolerance .and. kpoint_r(3,ik) .lt. tolerance) then
          inode = my_node_id
          ktmp = ik
          have_gamma = .True.
          write (stdout,*) 'node',my_node_id,'k#',ktmp
        end if
      end do
      call comms_reduce(inode, 1,'SUM')
      if (have_gamma .and. .not. on_root) then
        ! allocate the tmp array
        allocate (foptical_mat_temp(1:nbands + 1, 1:3, 1:nspins), stat=ierr)
        if (ierr /= 0) call io_error('Error: Problem allocating foptical_mat_temp in elec_read_foptical_mat')
        ! write to tmp array
        foptical_mat_temp = foptical_mat(:, nbands + 1,:,ktmp,:)
        ! send the tmp array to root node
        call comms_send(foptical_mat_temp(1,1,1),(nbands + 1)*3*nspins,root_id)
        ! deallocate the tmp array
        deallocate (foptical_mat_temp, stat=ierr)
        if (ierr /= 0) call io_error('Error: Problem deallocating foptical_mat_temp in elec_read_foptical_mat')
      end if
      if (on_root) then
        if (have_gamma) then
          ! Write out the fomes
          open (unit=gam_unit, action='write', file=trim(seedname)//'_gamma_fomes.dat')
          write (gam_unit, '(1x,a28)') '############################'
          write (gam_unit, *) '# Free electron OMEs for', seedname
          write (gam_unit, '(1x,a28)') '############################'
          do is = 1, nspins
            write (gam_unit, *) 'Spin Channel', is
            write (gam_unit, *) '# bands + free electron band', nbands + 1
            do ib = 1, nbands + 1
              write (gam_unit, '(1x, I3, 6(1x,ES24.16E2))') ib, (foptical_mat(ib,nbands + 1, i, ktmp, is),i=1, 3)
            end do
          end do
          close (unit=gam_unit)
        else
          ! allocate the tmp array
          allocate (foptical_mat_temp(1:nbands + 1, 1:3, 1:nspins), stat=ierr)
          if (ierr /= 0) call io_error('Error: Problem allocating foptical_mat_temp in elec_read_foptical_mat')
          ! receive the tmp array to root node
          call comms_recv(foptical_mat_temp(1,1,1),(nbands + 1)*3*nspins,inode)
          ! write out the tmp array
          open (unit=gam_unit, action='write', file=trim(seedname)//'_gamma_fomes.dat')
          write (gam_unit, '(1x,a28)') '############################'
          write (gam_unit, *) '# Free electron OMEs for', seedname
          write (gam_unit, '(1x,a28)') '############################'
          do is = 1, nspins
            write (gam_unit, *) 'Spin Channel', is
            write (gam_unit, *) '# bands + free electron band', nbands
            do ib = 1, nbands + 1
              write (gam_unit, '(1x, I3, 3(1x,ES24.16E2))') ib, (foptical_mat_temp(ib, i, is),i=1, 3)
            end do
          end do
          close (unit=gam_unit)
          ! deallocate the tmp array
          deallocate (foptical_mat_temp, stat=ierr)
          if (ierr /= 0) call io_error('Error: Problem deallocating foptical_mat_temp in elec_read_foptical_mat')
        end if
      end if
    end if
    time1 = io_time()
    if (on_root .and. iprint > 1) then
      write (stdout, '(1x,a59,f11.3,a8)') &
           '+ Time to read Free electron Matrix Elements                   &
           &      ', time1 - time0, ' (sec) +'
    end if
    return
102 call io_error('Error: Problem opening fem_bin file in read_band_foptical_mat')
  end subroutine elec_read_foptical_mat
Call graph
elec_read_foptical_mat calls io_time, io_file_unit, algor_dist_array, comms_send, io_error, comms_recv, comms_reduce
algor_dist_array calls io_error
read_fem_bin calls elec_read_foptical_mat
od2od calls read_fem_bin