gaussian – OptaDOS
gaussian Function
12 statements
Source File
public function gaussian(m, w, x)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: m
real(kind=dp), intent(in) :: w
real(kind=dp), intent(in) :: x
Return Value real(kind=dp)
Called by
Contents
Source Code
gaussian
Source Code
  function gaussian(m, w, x)
!=========================================================================!
! ** Return value of Gaussian(mean=m,width=w) at position x
! I don't know who's this function originally was, CJP? MIJP?
!=========================================================================!
    implicit none
    real(kind=dp), intent(in) :: m, w, x
    real(kind=dp)             :: gaussian
    if (0.5_dp*((x - m)/w)**2 .gt. 30.0_dp) then
      gaussian = 0.0_dp
      return
    else
      gaussian = inv_sqrt_two_pi*exp(-0.5_dp*((x - m)/w)**2)/w
    end if
    return
  end function gaussian
Call graph
calculate_jdos calls gaussian
jdos_utils_calculate calls calculate_jdos
jdos_calculate calls jdos_utils_calculate
optics_calculate calls jdos_utils_calculate
optados calls jdos_calculate, optics_calculate