get_band_energy – OptaDOS
get_band_energy Subroutine
8 statements
Source File
public subroutine get_band_energy()
Read the band file info which is prerequisite to know about k-points bands etc. It would be nice for od2od to work this out for itself. But at least this way it is consistent. The problem is that to convert, say a ome to a ome one also requires a .bands file.
Arguments
None
Calls
Called by
Contents
Source Code
get_band_energy
Source Code
  subroutine get_band_energy()
    !! Read the band file info which is prerequisite to know about k-points
    !! bands etc.
    !! It would be nice for od2od to work this out for itself. But at least this
    !! way it is consistent.  The problem is that to convert, say a ome to a ome
    !! one also requires a .bands file.
    implicit none
    write (stdout, *)
    write (stdout, *) "+----------------------------- K-point information --------------------------+"
    call elec_read_band_energy()
    call report_arraysize()
    write (stdout, *) "+----------------------------------------------------------------------------+"
  end subroutine get_band_energy
Call graph
get_band_energy calls elec_read_band_energy, report_arraysize
elec_read_band_energy calls io_time, io_file_unit, comms_bcast, algor_dist_array, io_error, comms_send, cell_find_mp_grid, comms_recv
algor_dist_array calls io_error
cell_find_mp_grid calls io_error
od2od calls get_band_energy