io_date – OptaDOS
io_date Subroutine
11 statements
Source File
public subroutine io_date(cdate, ctime)
Arguments
Type Intent Optional Attributes Name
character(len=11), intent(out) :: cdate
character(len=9), intent(out) :: ctime
Called by
Contents
Source Code
io_date
Source Code
  subroutine io_date(cdate, ctime)
    !==================================================================!
    !                                                                  !
    !     Returns two strings containing the date and the time         !
    !     in human-readable format. Uses a standard f90 call.          !
    !                                                                  !
    !===================================================================
    implicit none
    character(len=11), intent(out) :: cdate
    character(len=9), intent(out) :: ctime
    character(len=3), dimension(12) :: months
    data months/'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', &
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'/
    integer date_time(8)
    !
    call date_and_time(values=date_time)
    !
    write (cdate, '(i2,1x,a3,1x,i4)') date_time(3), months(date_time(2)), date_time(1)
    write (ctime, '(i2.2,":",i2.2,":",i2.2)') date_time(5), date_time(6), date_time(7)
  end subroutine io_date
Call graph
write_jdos calls io_date, write_jdos_xmgrace
xmgu_setup calls io_date
od2od calls io_date
optados calls io_date, jdos_calculate, dos_calculate
write_dos calls io_date, write_dos_xmgrace
jdos_calculate calls write_jdos
write_jdos_xmgrace calls xmgu_setup
dos_calculate calls write_dos
write_dos_xmgrace calls xmgu_setup