io_error – OptaDOS
io_error Subroutine
8 statements
Source File
public subroutine io_error(error_msg)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: error_msg
Called by
Contents
Source Code
io_error
Source Code
  subroutine io_error(error_msg)
    !==================================================================!
    !                                                                  !
    ! Aborts giving error message                                      !
    !                                                                  !
    !===================================================================
    implicit none
    character(len=*), intent(in) :: error_msg
    write (stderr, *) 'Exiting.......'
    write (stderr, '(1x,a)') trim(error_msg)
    close (stderr)
    error stop "Optados error: examine the output/error file for details"
  end subroutine io_error
Call graph
projection_get_string calls io_error
dos_utils_deallocate calls io_error
conv_get_seedname calls io_error
cell_find_mp_grid calls io_error
elec_read_optical_mat calls io_error, algor_dist_array
cell_get_symmetry calls io_error
read_pdos_fmt calls io_error
param_dist calls io_error
jdos_utils_calculate calls io_error, calculate_jdos, dos_utils_set_efermi, elec_read_band_gradient, setup_energy_scale
dos_utils_compute_bandgap calls io_error
allocate_jdos calls io_error
param_read calls io_error, cell_read_cell
write_jdos_xmgrace calls io_error, xmgu_data
projection_merge calls io_error
xmgu_data calls io_error
projection_analyse_orbitals calls io_error
calculate_jdos calls io_error, allocate_jdos
elec_dealloc_optical calls io_error
dos_utils_calculate_at_e calls io_error, elec_read_band_gradient
cell_read_cell calls io_error
make_weights calls io_error, cell_get_symmetry
algor_dist_array calls io_error
od2od calls io_error, conv_get_seedname, read_pdos_fmt, read_elnes_fmt, write_elnes_bin, read_pdos_bin, write_elnes_fmt, read_dome_bin, read_elnes_bin, read_ome_bin, read_fem_bin, get_band_energy
elec_read_band_energy_ordered calls io_error, cell_find_mp_grid, algor_dist_array
elec_dealloc_band_gradient calls io_error
cell_dist calls io_error
elec_read_foptical_mat calls io_error, algor_dist_array
write_dos_xmgrace calls io_error, xmgu_data
elec_elnes_find_channel_names calls io_error
write_dos calls io_error, write_dos_xmgrace
elec_read_band_energy calls io_error, cell_find_mp_grid, algor_dist_array
elec_pdos_read calls io_error
elec_elnes_find_channel_numbers calls io_error
elec_pdis_read calls io_error
elec_dealloc_pdos calls io_error
elec_read_band_curvature calls io_error, algor_dist_array
cell_get_atoms calls io_error
dos_utils_calculate calls io_error, elec_read_band_gradient
jdos_deallocate calls io_error
elec_dealloc_elnes calls io_error
dos_utils_set_efermi calls io_error, dos_utils_calculate
cell_calc_kpoint_r_cart calls io_error
elec_read_band_gradient calls io_error, elec_read_optical_mat, elec_dealloc_optical, algor_dist_array
elec_read_elnes_mat calls io_error, elec_elnes_find_channel_names
read_elnes_fmt calls io_error, elec_elnes_find_channel_names
write_jdos calls io_error, write_jdos_xmgrace
setup_energy_scale calls io_error
write_elnes_bin calls elec_elnes_find_channel_numbers
read_pdos_bin calls elec_pdos_read
write_elnes_fmt calls elec_elnes_find_channel_numbers
core_calculate calls dos_utils_calculate, dos_utils_set_efermi, elec_read_elnes_mat
read_dome_bin calls elec_read_band_gradient
read_elnes_bin calls elec_read_elnes_mat
pdos_calculate calls projection_get_string, projection_merge, projection_analyse_orbitals, elec_pdos_read, dos_utils_calculate, dos_utils_set_efermi
read_ome_bin calls elec_read_optical_mat
optados calls param_dist, param_read, elec_read_band_energy_ordered, cell_dist, elec_read_band_energy, core_calculate, pdos_calculate, pdis_calculate, optics_calculate, jdos_calculate, dos_calculate
pdis_calculate calls projection_get_string, projection_merge, projection_analyse_orbitals, elec_pdis_read
optics_calculate calls elec_read_optical_mat, jdos_utils_calculate, elec_dealloc_optical, dos_utils_calculate_at_e, make_weights, dos_utils_set_efermi
jdos_calculate calls jdos_utils_calculate, write_jdos
dos_calculate calls dos_utils_compute_bandgap, write_dos, dos_utils_calculate, dos_utils_set_efermi, dos_utils_compute_dos_at_efermi
dos_utils_compute_dos_at_efermi calls dos_utils_calculate_at_e
read_fem_bin calls elec_read_foptical_mat
get_band_energy calls elec_read_band_energy