io_file_unit – OptaDOS
io_file_unit Function
13 statements
Source File
public function io_file_unit()
Arguments
None
Return Value integer
Called by
Contents
Source Code
io_file_unit
Source Code
  function io_file_unit()
    !==================================================================!
    !                                                                  !
    ! Returns an unused unit number                                    !
    ! (so we can open a file on that unit                              !
    !                                                                  !
    !===================================================================
    implicit none
    integer :: io_file_unit, unit
    logical :: file_open
    unit = 9
    file_open = .true.
    do while (file_open)
      unit = unit + 1
      inquire (unit, OPENED=file_open)
    end do
    io_file_unit = unit
    return
  end function io_file_unit
Call graph
write_loss_fn calls io_file_unit
write_conduct calls io_file_unit
write_absorp calls io_file_unit
write_elnes_bin calls io_file_unit
write_pdos_fmt calls io_file_unit
cell_get_symmetry calls io_file_unit
read_pdos_fmt calls io_file_unit
elec_read_optical_mat calls io_file_unit
write_jdos_xmgrace calls io_file_unit
cell_get_real_lattice calls io_file_unit
elec_read_elnes_mat calls io_file_unit
write_pdos_bin calls io_file_unit
cell_read_cell calls io_file_unit, cell_get_real_lattice
elec_read_foptical_mat calls io_file_unit
elec_read_band_energy calls io_file_unit
od2od calls io_file_unit, write_elnes_bin, write_pdos_fmt, read_pdos_fmt, write_pdos_bin, write_elnes_fmt, read_elnes_fmt, read_dome_bin, read_elnes_bin, read_fem_bin, get_band_energy, read_pdos_bin, read_ome_bin
optados calls io_file_unit, elec_read_band_energy, elec_read_band_energy_ordered, jdos_calculate, param_read, pdis_calculate, optics_calculate, cell_calc_lattice, core_calculate, dos_calculate, pdos_calculate
write_elnes_fmt calls io_file_unit
elec_read_band_energy_ordered calls io_file_unit
write_dos calls io_file_unit, write_dos_xmgrace
write_refract calls io_file_unit
write_dos_xmgrace calls io_file_unit
cell_get_atoms calls io_file_unit, cell_get_real_lattice
write_epsilon calls io_file_unit
elec_pdos_read calls io_file_unit
elec_pdis_read calls io_file_unit
elec_read_band_curvature calls io_file_unit
elec_read_band_gradient calls io_file_unit, elec_read_optical_mat
write_reflect calls io_file_unit
read_elnes_fmt calls io_file_unit
write_jdos calls io_file_unit, write_jdos_xmgrace
jdos_utils_calculate calls elec_read_band_gradient, dos_utils_set_efermi
dos_utils_calculate_at_e calls elec_read_band_gradient
read_dome_bin calls elec_read_band_gradient
jdos_calculate calls write_jdos, jdos_utils_calculate
make_weights calls cell_get_symmetry
read_elnes_bin calls elec_read_elnes_mat
param_read calls cell_read_cell
read_fem_bin calls elec_read_foptical_mat
get_band_energy calls elec_read_band_energy
pdis_calculate calls elec_pdis_read
read_pdos_bin calls elec_pdos_read
dos_utils_calculate calls elec_read_band_gradient
optics_calculate calls write_loss_fn, write_conduct, write_absorp, elec_read_optical_mat, write_refract, write_epsilon, write_reflect, jdos_utils_calculate, dos_utils_calculate_at_e, make_weights, dos_utils_set_efermi
read_ome_bin calls elec_read_optical_mat
cell_calc_lattice calls cell_get_real_lattice
cell_calc_kpoint_r_cart calls cell_get_real_lattice, cell_calc_lattice
core_calculate calls elec_read_elnes_mat, dos_utils_calculate, dos_utils_set_efermi
dos_calculate calls write_dos, dos_utils_calculate, dos_utils_compute_dos_at_efermi, dos_utils_set_efermi
pdos_calculate calls elec_pdos_read, dos_utils_calculate, dos_utils_set_efermi
dos_utils_compute_dos_at_efermi calls dos_utils_calculate_at_e
dos_utils_set_efermi calls dos_utils_calculate