io_time – OptaDOS
io_time Function
17 statements
Source File
public function io_time()
Uses
od_constants
Arguments
None
Return Value real(kind=dp)
Called by
Contents
Source Code
io_time
Source Code
  function io_time()
    !==================================================================!
    !                                                                  !
    ! Returns elapsed CPU time in seconds since its first call         !
    ! uses standard f90 call                                           !
    !                                                                  !
    !===================================================================
    use od_constants, only: dp
    implicit none
    real(kind=dp) :: io_time
    ! t0 contains the time of the first call
    ! t1 contains the present time
    real(kind=dp) :: t0, t1
    logical :: first = .true.
    save first, t0
    !
    call cpu_time(t1)
    !
    if (first) then
      t0 = t1
      io_time = 0.0_dp
      first = .false.
    else
      io_time = t1 - t0
    end if
    return
  end function io_time
Call graph
dos_utils_compute_bandgap calls io_time
dos_utils_calculate_at_e calls io_time, elec_read_band_gradient
elec_read_foptical_mat calls io_time
elec_read_band_energy calls io_time
dos_utils_compute_band_energies calls io_time
elec_read_band_curvature calls io_time
dos_calculate calls io_time, dos_utils_compute_bandgap, dos_utils_compute_band_energies, dos_utils_calculate, dos_utils_compute_dos_at_efermi, dos_utils_set_efermi
od2od calls io_time, get_band_energy, read_ome_bin, read_dome_bin, read_fem_bin, read_elnes_bin
elec_read_band_energy_ordered calls io_time
optados calls io_time, elec_read_band_energy, dos_calculate, elec_read_band_energy_ordered, jdos_calculate, optics_calculate, pdos_calculate, core_calculate
elec_read_band_gradient calls io_time, elec_read_optical_mat
elec_read_optical_mat calls io_time
jdos_calculate calls io_time, jdos_utils_calculate
jdos_utils_calculate calls io_time, elec_read_band_gradient, dos_utils_set_efermi
dos_utils_calculate calls io_time, elec_read_band_gradient
elec_read_elnes_mat calls io_time
dos_utils_compute_dos_at_efermi calls io_time, dos_utils_calculate_at_e
optics_calculate calls dos_utils_calculate_at_e, elec_read_optical_mat, jdos_utils_calculate, dos_utils_set_efermi
get_band_energy calls elec_read_band_energy
read_ome_bin calls elec_read_optical_mat
read_dome_bin calls elec_read_band_gradient
read_fem_bin calls elec_read_foptical_mat
pdos_calculate calls dos_utils_calculate, dos_utils_set_efermi
dos_utils_set_efermi calls dos_utils_calculate
core_calculate calls dos_utils_calculate, elec_read_elnes_mat, dos_utils_set_efermi
read_elnes_bin calls elec_read_elnes_mat