jdos_utils_merge – OptaDOS
jdos_utils_merge Subroutine
12 statements
Source File
public subroutine jdos_utils_merge(jdos, weighted_jdos)
Uses
od_comms
od_electronic
od_parameters
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout), allocatable :: jdos(:,:)
real(kind=dp), intent(inout), optional, allocatable :: weighted_jdos(:,:,:)
Calls
Called by
Contents
Source Code
jdos_utils_merge
Source Code
  subroutine jdos_utils_merge(jdos, weighted_jdos)
    !===============================================================================
    ! The DOS was calculated accross nodes. Now give them all back to root
    ! and free up the memeory on the slaves
    !-------------------------------------------------------------------------------
    ! Arguments: dos          (in - slaves) (inout -  root)       : The DOS
    !            weighted_dos (in - slaves) (inout -  root) (opt) : Weighted DOS
    !-------------------------------------------------------------------------------
    ! Parent Module Varables Used: mw
    !-------------------------------------------------------------------------------
    ! Modules Used: See below
    !-------------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------------
    ! Necessary Conditions: None
    !-------------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------------
    ! Written by : A J Morris December 2010
    !===============================================================================
    use od_comms, only: comms_reduce
    use od_electronic, only: nspins
    use od_parameters, only: photo
    implicit none
    real(kind=dp), intent(inout), allocatable, optional :: weighted_jdos(:, :, :) ! bins.spins, orbitals
    real(kind=dp), allocatable, intent(inout) :: jdos(:, :)
    integer :: N_geom
    if (present(weighted_jdos)) N_geom = size(weighted_jdos, 3)
    call comms_reduce(jdos(1, 1), nspins*jdos_nbins, "SUM")
    if (present(weighted_jdos)) call comms_reduce(weighted_jdos(1, 1, 1), nspins*jdos_nbins*N_geom, "SUM")
!    if(.not.on_root) then
!       if(allocated(jdos)) deallocate(jdos,stat=ierr)
!       if (ierr/=0) call io_error (" ERROR : jdos : merge_jdos : cannot deallocate dos")
!       if(present(weighted_jdos))  then
!          if(allocated(weighted_jdos)) deallocate(weighted_jdos,stat=ierr)
!          if (ierr/=0) call io_error (" ERROR : jdos : merge_jdos : cannot deallocate weighted_dos")
!       end if
!    endif
  end subroutine jdos_utils_merge
Call graph
jdos_utils_merge calls comms_reduce
jdos_utils_calculate calls jdos_utils_merge
jdos_calculate calls jdos_utils_calculate
optics_calculate calls jdos_utils_calculate
optados calls jdos_calculate, optics_calculate