jdos_calculate – OptaDOS
jdos_calculate Subroutine
23 statements
Source File
public subroutine jdos_calculate()
Uses
od_io
od_comms
od_parameters
od_jdos_utils
Arguments
None
Calls
Called by
Contents
Source Code
jdos_calculate
Source Code
  subroutine jdos_calculate
    !===============================================================================
    use od_jdos_utils, only: jdos_utils_calculate, E, jdos_fixed &
         &, jdos_adaptive, jdos_linear
    use od_parameters, only: fixed, adaptive, linear
    use od_io, only: io_time, stdout
    use od_comms, only: on_root
    implicit none
    real(kind=dp) :: time0, time1
    if (on_root) then
      write (stdout, *)
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)') '+                           Joint Density of States                          +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)') '|                                                                            |'
    end if
    call jdos_utils_calculate
    !-------------------------------------------------------------------------------
    ! W R I T E   O U T   J D O S
    time0 = io_time()
    ! Otherwise we have written to wdos and dos, so they can be called
    ! by whatever.
    if (on_root) then
      if (fixed) call write_jdos(E, jdos_fixed, "fixed")
      if (adaptive) call write_jdos(E, jdos_adaptive, "adaptive")
      if (linear) call write_jdos(E, jdos_linear, "linear")
      !if(quad)    call write_jdos(E, dos_quad, intdos_quad, "quad")
    end if
    time1 = io_time()
    !-------------------------------------------------------------------------------
  end subroutine jdos_calculate
Call graph
jdos_calculate calls jdos_utils_calculate, write_jdos, io_time
jdos_utils_calculate calls io_time, elec_read_band_gradient, jdos_utils_merge, dos_utils_set_efermi, setup_energy_scale, calculate_jdos, io_error
write_jdos calls io_error, io_file_unit, io_date, write_jdos_xmgrace
elec_read_band_gradient calls io_time, io_error, io_file_unit, elec_read_optical_mat, comms_recv, algor_dist_array, comms_send, comms_bcast, elec_dealloc_optical
jdos_utils_merge calls comms_reduce
dos_utils_set_efermi calls io_error, comms_bcast, comms_reduce, dos_utils_calculate
setup_energy_scale calls io_error, comms_bcast, comms_reduce
calculate_jdos calls io_error, doslin, allocate_jdos, doslin_sub_cell_corners, gaussian
write_jdos_xmgrace calls io_error, io_file_unit, xmgu_legend, xmgu_subtitle, xmgu_axis, xmgu_data, xmgu_setup, xmgu_data_header, xmgu_title
elec_read_optical_mat calls io_time, io_error, io_file_unit, comms_recv, algor_dist_array, comms_send
algor_dist_array calls io_error
xmgu_data calls io_error
allocate_jdos calls io_error
xmgu_setup calls io_date
doslin_sub_cell_corners calls heap_sort
elec_dealloc_optical calls io_error
dos_utils_calculate calls io_time, elec_read_band_gradient, io_error, comms_bcast, dos_utils_merge
dos_utils_merge calls comms_reduce
optados calls jdos_calculate