jdos_utils_calculate – OptaDOS
jdos_utils_calculate Subroutine
83 statements
Source File
public subroutine jdos_utils_calculate(matrix_weights, weighted_jdos)
Uses
od_parameters
od_comms
od_dos_utils
od_cell
od_electronic
od_io
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), optional :: matrix_weights(:,:,:,:,:)
real(kind=dp), intent(out), optional, allocatable :: weighted_jdos(:,:,:)
Calls
Called by
Contents
Source Code
jdos_utils_calculate
Source Code
  subroutine jdos_utils_calculate(matrix_weights, weighted_jdos)
    !===============================================================================
    ! Main routine in dos module, drives the calculation of Density of states for
    ! both task : dos and also if it is required elsewhere.
    !===============================================================================
    use od_parameters, only: linear, fixed, adaptive, quad, iprint, dos_per_volume, photo,&
      jdos_max_energy, jdos_spacing, photo
    use od_electronic, only: elec_read_band_gradient, band_gradient, nspins, electrons_per_state, &
      num_electrons, efermi_set
    use od_comms, only: on_root, comms_bcast
    use od_io, only: stdout, io_error, io_time, seedname
    use od_cell, only: cell_volume
    use od_dos_utils, only: dos_utils_set_efermi
    implicit none
    !integer :: ierr
    real(kind=dp) :: time0, time1
    real(kind=dp), intent(out), allocatable, optional    :: weighted_jdos(:, :, :)  !I've added this
    real(kind=dp), intent(in), optional  :: matrix_weights(:, :, :, :, :)               !I've added this
    calc_weighted_jdos = .false.
    if (present(matrix_weights)) calc_weighted_jdos = .true.
    if (calc_weighted_jdos .eqv. .false.) then ! We are called just to provide jdos.
      if (allocated(E)) then
        if (on_root .and. iprint > 1) write (stdout, *) " Already calculated jdos, so returning..."
        return  ! The jdos has already been calculated previously so just return.
      end if
    end if
    !-------------------------------------------------------------------------------
    ! R E A D   B A N D   G R A D I E N T S
    ! If we're using one of the more accurate roadening schemes we also need to read in the
    ! band gradients too
    if (quad .or. linear .or. adaptive) then
      if (.not. allocated(band_gradient)) call elec_read_band_gradient
    end if
    !-------------------------------------------------------------------------------
    if (.not. efermi_set) call dos_utils_set_efermi
    !-------------------------------------------------------------------------------
    ! C A L C U L A T E   J D O S
    ! Now everything is set up, we can perform the dos accumulation in parellel
    time0 = io_time()
    call setup_energy_scale(E)
    if (fixed) then
      if (calc_weighted_jdos) then
        call calculate_jdos('f', jdos_fixed, matrix_weights, weighted_jdos=weighted_jdos)
        call jdos_utils_merge(jdos_fixed, weighted_jdos)
      else
        call calculate_jdos('f', jdos_fixed)
        call jdos_utils_merge(jdos_fixed)
      end if
    end if
    if (adaptive) then
      if (calc_weighted_jdos) then
        call calculate_jdos('a', jdos_adaptive, matrix_weights, weighted_jdos=weighted_jdos)
        call jdos_utils_merge(jdos_adaptive, weighted_jdos)
      else
        call calculate_jdos('a', jdos_adaptive)
        call jdos_utils_merge(jdos_adaptive)
      end if
    end if
    if (linear) then
      if (calc_weighted_jdos) then
        call calculate_jdos('l', jdos_linear, matrix_weights, weighted_jdos=weighted_jdos)
        call jdos_utils_merge(jdos_linear, weighted_jdos)
      else
        call calculate_jdos('l', jdos_linear)
        call jdos_utils_merge(jdos_linear)
      end if
    end if
    if (quad) then
      call io_error("quadratic broadening not implemented")
      !if(quad)    call merge_dos(dos_quad)
      !if(quad)    call merge_dos(intdos_quad)
    end if
!    if(.not.on_root) then
!       if(allocated(E)) deallocate(E, stat=ierr)
!       if (ierr/=0) call io_error ("cannot deallocate  E")
!    endif
    time1 = io_time()
    if (on_root .and. iprint > 1) then
      write (stdout, '(1x,a59,f11.3,a8)') &
           '+ Time to calculate Joint Density of States              &
           &      ', time1 - time0, ' (sec) +'
    end if
    !-------------------------------------------------------------------------------
    if (dos_per_volume) then
      if (photo) then
        if (fixed) then
          jdos_fixed = jdos_fixed
        end if
        if (adaptive) then
          jdos_adaptive = jdos_adaptive
        end if
        if (linear) then
          jdos_linear = jdos_linear
        end if
      else
        if (fixed) then
          jdos_fixed = jdos_fixed/cell_volume
        end if
        if (adaptive) then
          jdos_adaptive = jdos_adaptive/cell_volume
        end if
        if (linear) then
          jdos_linear = jdos_linear/cell_volume
        end if
      end if
      ! if(quad) then
      !    dos_quad=dos_quad/cell_volume
      !    intdos_quad=intdos_quad/cell_volume
      ! endif
    end if
  end subroutine jdos_utils_calculate
Call graph
jdos_utils_calculate calls elec_read_band_gradient, io_time, dos_utils_set_efermi, setup_energy_scale, calculate_jdos, jdos_utils_merge, io_error
elec_read_band_gradient calls io_time, io_error, comms_bcast, comms_recv, algor_dist_array, comms_send, io_file_unit, elec_read_optical_mat, elec_dealloc_optical
dos_utils_set_efermi calls io_error, comms_bcast, comms_reduce, dos_utils_calculate
setup_energy_scale calls io_error, comms_bcast, comms_reduce
calculate_jdos calls io_error, gaussian, doslin_sub_cell_corners, doslin, allocate_jdos
jdos_utils_merge calls comms_reduce
doslin_sub_cell_corners calls heap_sort
algor_dist_array calls io_error
elec_read_optical_mat calls io_time, io_error, comms_recv, algor_dist_array, comms_send, io_file_unit
elec_dealloc_optical calls io_error
dos_utils_calculate calls elec_read_band_gradient, io_time, io_error, comms_bcast, dos_utils_merge
allocate_jdos calls io_error
dos_utils_merge calls comms_reduce
jdos_calculate calls jdos_utils_calculate
optics_calculate calls jdos_utils_calculate
optados calls jdos_calculate, optics_calculate