make_weights – OptaDOS
make_weights Subroutine
229 statements
Source File
public subroutine make_weights(matrix_weights)
Uses
od_parameters
od_comms
od_cell
od_constants
od_electronic
od_io
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), allocatable, dimension(:, :, :, :, :) :: matrix_weights
Calls
Called by
Contents
Source Code
make_weights
Source Code
  subroutine make_weights(matrix_weights)
    !***************************************************************
    use od_constants, only: dp
    use od_electronic, only: nbands, nspins, optical_mat, num_electrons, &
      electrons_per_state, band_energy, efermi
    use od_cell, only: nkpoints, cell_volume, num_kpoints_on_node, cell_get_symmetry, &
      num_crystal_symmetry_operations, crystal_symmetry_operations, kpoint_r
    use od_parameters, only: optics_geom, optics_qdir, legacy_file_format, scissor_op, devel_flag
    use od_io, only: io_error, stdout
    use od_comms, only: my_node_id
    real(kind=dp), intent(out), allocatable, dimension(:, :, :, :, :) :: matrix_weights
    real(kind=dp), dimension(3) :: qdir
    real(kind=dp), dimension(3) :: qdir1
    real(kind=dp), dimension(3) :: qdir2
    real(kind=dp) :: q_weight1
    real(kind=dp) :: q_weight2
    integer :: N, i, j, k
    integer :: N_in
    integer :: N_spin
    integer :: N2, N3
    integer :: n_eigen
    integer :: n_eigen2
    integer :: num_symm
    real(kind=dp), dimension(2) :: num_occ
    complex(kind=dp), dimension(3) :: g
    real(kind=dp) :: factor
    integer         :: gamma_is, top_filled_band, upper_window, lower_window
    character(len=30) :: rowfmt
    logical :: print_omes
    print_omes = .false. ! Only set to true if you want the experiemental OME writing
    top_filled_band = 0
    gamma_is = -1
    if (.not. legacy_file_format .and. index(devel_flag, 'old_filename') > 0) then
      num_symm = 0
      call cell_get_symmetry
    end if ! otherwise we have already set this
    num_symm = num_crystal_symmetry_operations
    !      Do N=1,num_symm
    !         Do N2=1,3
    !            print *, crystal_symmetry_operations(1,N2,N), crystal_symmetry_operations(2,N2,N), crystal_symmetry_operations(3,N2,N)
    !         end do
    !         print *,'# '
    !      end do
    num_occ = 0.0_dp
    do N_spin = 1, nspins
      num_occ(N_spin) = num_electrons(N_spin)
    end do
    if (electrons_per_state == 2) then
      num_occ(1) = num_occ(1)/2.0_dp
    end if
    if (.not. index(optics_geom, 'tensor') > 0) then ! I can rewrite this in a simplier way??
      N_geom = 1
    elseif (index(optics_geom, 'tensor') > 0) then
      N_geom = 6
    end if
    allocate (matrix_weights(nbands, nbands, num_kpoints_on_node(my_node_id), nspins, N_geom))
    matrix_weights = 0.0_dp
    if (index(optics_geom, 'polar') > 0) then
      qdir = optics_qdir
      q_weight = ((qdir(1)**2) + (qdir(2)**2) + (qdir(3)**2))**0.5_dp
      if (q_weight < 0.001_dp) &
        call io_error("Error:  please check optics_qdir, norm close to zero")
    end if
    if (index(optics_geom, 'unpolar') > 0) then
      if (optics_qdir(3) == 0) then
        qdir1(1) = 0.0_dp
        qdir1(2) = 0.0_dp
        qdir1(3) = 1.0_dp
      else
        qdir1(1) = 1.0_dp
        qdir1(2) = 1.0_dp
        qdir1(3) = -(optics_qdir(1) + optics_qdir(2))/optics_qdir(3)
      end if
      qdir2(1) = (optics_qdir(2)*qdir1(3)) - (optics_qdir(3)*qdir1(2))
      qdir2(2) = (optics_qdir(3)*qdir1(1)) - (optics_qdir(1)*qdir1(3))
      qdir2(3) = (optics_qdir(1)*qdir1(2)) - (optics_qdir(2)*qdir1(1))
      q_weight1 = ((qdir1(1)**2) + (qdir1(2)**2) + (qdir1(3)**2))**0.5_dp
      q_weight2 = ((qdir2(1)**2) + (qdir2(2)**2) + (qdir2(3)**2))**0.5_dp
    end if
    N_in = 1  ! 0 = no inversion, 1 = inversion
    g = 0.0_dp
    do N = 1, num_kpoints_on_node(my_node_id)                   ! Loop over kpoints
      if (print_omes) then ! If .not. then hopefully the compiler will get rid of this at
        ! compile time, and there's no 'if' overhead. AJM May 2018
        if ((kpoint_r(1, N)**2 + kpoint_r(2, N)**2 + kpoint_r(3, N)**2) < 0.01) then
          write (stdout, *) kpoint_r(1, N)**2 + kpoint_r(2, N)**2 + kpoint_r(3, N)**2, " = kpoint norm "
          write (stdout, *) " N= ", N
          gamma_is = N
        end if
      end if
      do N_spin = 1, nspins                                    ! Loop over spins
        do n_eigen = 1, nbands                                ! Loop over state 1
          do n_eigen2 = n_eigen, nbands                      ! Loop over state 2
            if (band_energy(n_eigen, N_spin, N) > efermi .and. n_eigen /= n_eigen2) cycle
            if (band_energy(n_eigen2, N_spin, N) < efermi .and. n_eigen /= n_eigen2) cycle
            factor = 0.0_dp
            if (n_eigen2 == n_eigen) then
              factor = 1.0_dp
            elseif (band_energy(n_eigen2, N_spin, N) > efermi) then
              factor = 1.0_dp/((band_energy(n_eigen2, N_spin, N) - band_energy(n_eigen, N_spin, N) &
                                + scissor_op)**2)
            end if
            if (index(optics_geom, 'unpolar') > 0) then
              if (num_symm == 0) then
                g(1) = (((qdir1(1)*optical_mat(n_eigen, n_eigen2, 1, N, N_spin)) + &
                         (qdir1(2)*optical_mat(n_eigen, n_eigen2, 2, N, N_spin)) + &
                         (qdir1(3)*optical_mat(n_eigen, n_eigen2, 3, N, N_spin)))/q_weight1)
                g(2) = (((qdir2(1)*optical_mat(n_eigen, n_eigen2, 1, N, N_spin)) + &
                         (qdir2(2)*optical_mat(n_eigen, n_eigen2, 2, N, N_spin)) + &
                         (qdir2(3)*optical_mat(n_eigen, n_eigen2, 3, N, N_spin)))/q_weight2)
                matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom) = &
                  0.5_dp*factor*(real(g(1)*conjg(g(1)), dp) + real(g(2)*conjg(g(2)), dp))
              else
                do N2 = 1, num_symm
                  do N3 = 1, 1 + N_in
                    do i = 1, 3
                      qdir(i) = 0.0_dp
                      do j = 1, 3
                        qdir(i) = qdir(i) + ((-1.0_dp)**(N3 + 1))* &
                                  (crystal_symmetry_operations(j, i, N2)*qdir1(j))
                      end do
                    end do
                    g(1) = (((qdir(1)*optical_mat(n_eigen, n_eigen2, 1, N, N_spin)) + &
                             (qdir(2)*optical_mat(n_eigen, n_eigen2, 2, N, N_spin)) + &
                             (qdir(3)*optical_mat(n_eigen, n_eigen2, 3, N, N_spin)))/q_weight1)
                    matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom) = &
                      matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom) + &
                      (0.5_dp/Real((num_symm*(N_in + 1)), dp))*real(g(1)*conjg(g(1)), dp)*factor
                    g(1) = 0.0_dp
                    do i = 1, 3 ! if I include an extra variable I can merge this and the last do loops
                      qdir(i) = 0.0_dp
                      do j = 1, 3
                        qdir(i) = qdir(i) + ((-1.0_dp)**(N3 + 1))* &
                                  (crystal_symmetry_operations(j, i, N2)*qdir2(j))
                      end do
                    end do
                    g(1) = (((qdir(1)*optical_mat(n_eigen, n_eigen2, 1, N, N_spin)) + &
                             (qdir(2)*optical_mat(n_eigen, n_eigen2, 2, N, N_spin)) + &
                             (qdir(3)*optical_mat(n_eigen, n_eigen2, 3, N, N_spin)))/q_weight2)
                    matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom) = &
                      matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom) + &
                      (0.5_dp/Real((num_symm*(N_in + 1)), dp))*real(g(1)*conjg(g(1)), dp)*factor
                  end do
                end do
              end if
            elseif (index(optics_geom, 'polar') > 0) then
              if (num_symm == 0) then
                g(1) = (((qdir(1)*optical_mat(n_eigen, n_eigen2, 1, N, N_spin)) + &
                         (qdir(2)*optical_mat(n_eigen, n_eigen2, 2, N, N_spin)) + &
                         (qdir(3)*optical_mat(n_eigen, n_eigen2, 3, N, N_spin)))/q_weight)
                matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom) = factor*real(g(1)*conjg(g(1)), dp)
                !           matrix_weights(n_eigen,n_eigen2,N,N_spin) = 1.0_dp  ! for JDOS
              else
                do N2 = 1, num_symm
                  do N3 = 1, 1 + N_in
                    do i = 1, 3
                      qdir(i) = 0.0_dp
                      do j = 1, 3
                        qdir(i) = qdir(i) + ((-1.0_dp)**(N3 + 1))* &
                                  (crystal_symmetry_operations(j, i, N2)*optics_qdir(j))
                      end do
                    end do
                    g(1) = 0.0_dp
                    g(1) = (((qdir(1)*optical_mat(n_eigen, n_eigen2, 1, N, N_spin)) + &
                             (qdir(2)*optical_mat(n_eigen, n_eigen2, 2, N, N_spin)) + &
                             (qdir(3)*optical_mat(n_eigen, n_eigen2, 3, N, N_spin)))/q_weight)
                    matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom) = &
                      matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom) + &
                      (1.0_dp/Real((num_symm*(N_in + 1)), dp))*factor*real(g(1)*conjg(g(1)), dp)
                  end do
                end do
              end if
            elseif (index(optics_geom, 'poly') > 0) then
              if (num_symm == 0) then
                do N2 = 1, 3
                  g(N2) = optical_mat(n_eigen, n_eigen2, N2, N, N_spin)
                  !if (n_eigen==1) then
                  !if (n_eigen2==NINT(num_occ(N_spin)+1)) then
                  !print *, N, N2
                  !print *, g(N2), abs(g(N2))
                  !print *, optical_mat(n_eigen2,n_eigen,N2,N,N_spin)
                  !print *, optical_mat(n_eigen,n_eigen,N2,N,N_spin), optical_mat(n_eigen2,n_eigen2,N2,N,N_spin)
                  !end if
                  !end if
                end do
                matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom) = (factor/3.0_dp)* &
                     &   (real(g(1)*conjg(g(1)), dp) + real(g(2)*conjg(g(2)), dp) +  &
                     &    real(g(3)*conjg(g(3)), dp))
                ! write (*, *) matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom)
                !                 print *, n_eigen, n_eigen2, N, matrix_weights(n_eigen,n_eigen2,N,N_spin,N_geom)
                !                 print *, band_energy(n_eigen2,N_spin,N), band_energy(n_eigen,N_spin,N)
              else
                do N2 = 1, num_symm
                  do N3 = 1, 1 + N_in
                    qdir = 0.0_dp
                    qdir1 = 0.0_dp
                    qdir2 = 0.0_dp
                    do i = 1, 3
                      qdir(i) = ((-1.0_dp)**(N3 + 1))*crystal_symmetry_operations(1, i, N2)
                      qdir1(i) = ((-1.0_dp)**(N3 + 1))*crystal_symmetry_operations(2, i, N2)
                      qdir2(i) = ((-1.0_dp)**(N3 + 1))*crystal_symmetry_operations(3, i, N2)
                    end do
                    g = 0.0_dp
                    g(1) = ((qdir(1)*optical_mat(n_eigen, n_eigen2, 1, N, N_spin)) + &
                            (qdir(2)*optical_mat(n_eigen, n_eigen2, 2, N, N_spin)) + &
                            (qdir(3)*optical_mat(n_eigen, n_eigen2, 3, N, N_spin)))
                    g(2) = ((qdir1(1)*optical_mat(n_eigen, n_eigen2, 1, N, N_spin)) + &
                            (qdir1(2)*optical_mat(n_eigen, n_eigen2, 2, N, N_spin)) + &
                            (qdir1(3)*optical_mat(n_eigen, n_eigen2, 3, N, N_spin)))
                    g(3) = ((qdir2(1)*optical_mat(n_eigen, n_eigen2, 1, N, N_spin)) + &
                            (qdir2(2)*optical_mat(n_eigen, n_eigen2, 2, N, N_spin)) + &
                            (qdir2(3)*optical_mat(n_eigen, n_eigen2, 3, N, N_spin)))
                    matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom) = &
                      matrix_weights(n_eigen, n_eigen2, N, N_spin, N_geom) + &
                       &(1.0_dp/Real((num_symm*(N_in + 1)), dp))*factor*((real(g(1)*conjg(g(1)), dp) + &
                       & real(g(2)*conjg(g(2)), dp) + real(g(3)*conjg(g(3)), dp))/3.0_dp)
                    !        write(*,*) "mw =", matrix_weights
                  end do
                end do
              end if
            elseif (index(optics_geom, 'tensor') > 0) then
              if (num_symm == 0) then
                do N2 = 1, 3
                  g(N2) = optical_mat(n_eigen, n_eigen2, N2, N, N_spin)
                end do
                matrix_weights(n_eigen, n_eigen2, N, N_spin, 1) = factor*real(g(1)*conjg(g(1)), dp)
                matrix_weights(n_eigen, n_eigen2, N, N_spin, 2) = factor*real(g(2)*conjg(g(2)), dp)
                matrix_weights(n_eigen, n_eigen2, N, N_spin, 3) = factor*real(g(3)*conjg(g(3)), dp)
                matrix_weights(n_eigen, n_eigen2, N, N_spin, 4) = factor*real(g(1)*conjg(g(2)), dp)
                matrix_weights(n_eigen, n_eigen2, N, N_spin, 5) = factor*real(g(1)*conjg(g(3)), dp)
                matrix_weights(n_eigen, n_eigen2, N, N_spin, 6) = factor*real(g(2)*conjg(g(3)), dp)
              else
                do N2 = 1, num_symm
                  do N3 = 1, 1 + N_in
                    g = 0.0_dp
                    do i = 1, 3
                      do j = 1, 3
                        g(i) = g(i) + ((-1.0_dp)**(N3 + 1))*(crystal_symmetry_operations(i, j, N2) &
                                                             *optical_mat(n_eigen, n_eigen2, j, N, N_spin))
                      end do
                    end do
                    matrix_weights(n_eigen, n_eigen2, N, N_spin, 1) = matrix_weights(n_eigen, n_eigen2, &
                         & N, N_spin, 1) + factor*real(g(1)*conjg(g(1)), dp) &
                         & /Real((num_symm*(N_in + 1)), dp)
                    matrix_weights(n_eigen, n_eigen2, N, N_spin, 2) = matrix_weights(n_eigen, n_eigen2, &
                         & N, N_spin, 2) + factor*real(g(2)*conjg(g(2)), dp)&
                         & /Real((num_symm*(N_in + 1)), dp)
                    matrix_weights(n_eigen, n_eigen2, N, N_spin, 3) = matrix_weights(n_eigen, n_eigen2, &
                         & N, N_spin, 3) + factor*real(g(3)*conjg(g(3)), dp)&
                         & /Real((num_symm*(N_in + 1)), dp)
                    matrix_weights(n_eigen, n_eigen2, N, N_spin, 4) = matrix_weights(n_eigen, n_eigen2, &
                         & N, N_spin, 4) + factor*real(g(1)*conjg(g(2)), dp)&
                         & /Real((num_symm*(N_in + 1)), dp)
                    matrix_weights(n_eigen, n_eigen2, N, N_spin, 5) = matrix_weights(n_eigen, n_eigen2, &
                         & N, N_spin, 5) + factor*real(g(1)*conjg(g(3)), dp)&
                         &/Real((num_symm*(N_in + 1)), dp)
                    matrix_weights(n_eigen, n_eigen2, N, N_spin, 6) = matrix_weights(n_eigen, n_eigen2, &
                         &N, N_spin, 6) + factor*real(g(2)*conjg(g(3)), dp)&
                         & /Real((num_symm*(N_in + 1)), dp)
                  end do
                end do
              end if
            end if
          end do
        end do
      end do
    end do
    if (print_omes) then
! This seems to be a rare thing to want to be able to do. So at the moment, I've made it a hard
! coded decision.  If you want the OMEs you probably know what you're doing enough to set this
! I haven't thought about spin or MPI. I think it behaves ok with symmetry.
! The results I wanted were polycrystalline.
      ! AJM May 2018
      ! Above, we have already looked to label the gamma point. That is,
      ! the kpoint number at gamma. The variable was set to -1. So if it
      ! hasn't been set -- we didn't find the gamma point.
      ! If we didn't find it -- then we're not going to get the OMEs
      ! at the Gamma point. It's a critical stop.
      if (gamma_is < 0) stop "Couldnt find the gamma point"
      ! Run through all the bands and find the last one that isn't above the Fermi level.
      ! This is inventivly called the "top filled band"
      do i = 1, nbands
        if (band_energy(i, 1, gamma_is) .ge. efermi) then
          exit
        else
          top_filled_band = i
        end if
      end do
! Set these for the number of bands either side of the Fermi energy that you want the
! OMES for.
      upper_window = top_filled_band + 2
      lower_window = top_filled_band - 25
!
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, *) ' + PRINT OUT SOME OPTICAL MATRIX ELEMENTS -- EASTER EGG CODE                  +'
      write (stdout, *) ' + Note that I wrote this for a specific purpose. I have documented it as best+'
      write (stdout, *) " + I can, but you should fully understand what's happening before you use it  +"
      write (stdout, *) " + AJM May 2018 B'ham                                                         +"
      write (stdout, *) " + Top filled band is", top_filled_band
      write (rowfmt, '(A,I4,A)') '(8x,', upper_window - lower_window + 1, '(3X,f8.5))'
! write(*,*) rowfmt ! For debugging
      write (stdout, *) kpoint_r(gamma_is, :)
      write (stdout, '(1x,a78)') '+============================================================================+'
      ! I haven't really thought about spins. So if you have a spin system, you get both an up and down spin
      ! OME
      do k = 1, nspins
        write (stdout, *) '+ For spin channel', k
        write (stdout, '(1x,a78)') '+============================================================================+'
        write (stdout, FMT=rowfmt) (band_energy(i, k, gamma_is) - band_energy(top_filled_band, k, gamma_is), &
                     & i=lower_window, upper_window)
        write (rowfmt, '(A,I4,A)') '(f8.5,', upper_window - lower_window + 1, '(3X,f8.5))'
        do i = lower_window, upper_window
          write (stdout, FMT=rowfmt) band_energy(i, k, gamma_is) - band_energy(top_filled_band, k, gamma_is), &
                  & (matrix_weights(i, j, gamma_is, k, :), j=lower_window, upper_window)
        end do
      end do
      write (stdout, '(1x,a78)') '+============================================================================+'
      stop " Completed generating the OMEs -- see the odo file"
    end if
  end subroutine make_weights
Call graph
make_weights calls cell_get_symmetry, io_error
cell_get_symmetry calls io_error, io_file_unit, comms_bcast
optics_calculate calls make_weights
optados calls optics_calculate