optics_calculate – OptaDOS
optics_calculate Subroutine
66 statements
Source File
public subroutine optics_calculate()
Uses
od_parameters
od_jdos_utils
od_comms
od_dos_utils
od_cell
od_electronic
od_io
Arguments
None
Calls
Called by
Contents
Source Code
optics_calculate
Source Code
  subroutine optics_calculate
    !
    !  Program to calculate optical properties
    !
    use od_electronic, only: optical_mat, elec_read_optical_mat, nbands, nspins, &
      efermi, efermi_set, elec_dealloc_optical
    use od_cell, only: cell_volume, num_kpoints_on_node, kpoint_r, real_lattice
    use od_jdos_utils, only: jdos_utils_calculate
    use od_comms, only: on_root, my_node_id
    use od_parameters, only: optics_geom, adaptive, linear, fixed, optics_intraband, &
      optics_drude_broadening, photo_slab_min, photo_slab_max, devel_flag
    use od_dos_utils, only: dos_utils_calculate_at_e, dos_utils_set_efermi
    use od_io, only: stdout
    if (on_root) then
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)') '+                                Optics Calculation                          +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)') '|                                                                            |'
    end if
    if (.not. efermi_set) call dos_utils_set_efermi
    ! Get information from .cst_ome file
    call elec_read_optical_mat
    ! Form matrix element
    call make_weights(matrix_weights)
    ! Send matrix element to jDOS routine and get weighted jDOS back
    call jdos_utils_calculate(matrix_weights, weighted_jdos=weighted_jdos)
    ! Calculate weighted DOS at Ef for intraband term
    if (optics_intraband) then
      allocate (dos_matrix_weights(size(matrix_weights, 5), nbands, num_kpoints_on_node(my_node_id), nspins))
      allocate (dos_at_e(3, nspins))
      allocate (weighted_dos_at_e(nspins, size(matrix_weights, 5)))
      weighted_dos_at_e = 0.0_dp
      do N = 1, size(matrix_weights, 5)
        do N2 = 1, nbands
          dos_matrix_weights(N, N2, :, :) = matrix_weights(N2, N2, :, :, N)
        end do
      end do
      call dos_utils_calculate_at_e(efermi, dos_at_e, dos_matrix_weights, weighted_dos_at_e)
    end if
    call elec_dealloc_optical ! don't need this large array anymore
    if (on_root) then
      if (index(devel_flag,'slab_volume') > 0) then
        slab_volume = (cell_volume/real_lattice(3, 3))*(photo_slab_max - photo_slab_min)
        ! Calculate epsilon_2
        call calc_epsilon_2(weighted_jdos, weighted_dos_at_e,slab_volume)
      else
        ! Calculate epsilon_2
        call calc_epsilon_2(weighted_jdos, weighted_dos_at_e)
      end if
      ! Calculate epsilon_1
      call calc_epsilon_1
      ! Calculate other optical properties
      if (.not. index(optics_geom, 'tensor') > 0) then
        call calc_conduct
        call calc_refract
        call calc_loss_fn
        call calc_absorp
        call calc_reflect
      end if
      ! Write everything out
      if (index(devel_flag,'slab_volume') > 0) then
        call write_epsilon(atom = 0,photo_volume = slab_volume)
      else
        call write_epsilon(0)
      end if
        if (.not. index(optics_geom, 'tensor') > 0) then
        call write_conduct
        call write_loss_fn
        if (index(devel_flag,'slab_volume') > 0) then
          call write_refract(atom = 0,photo_volume = slab_volume)
          call write_absorp(atom = 0,photo_volume = slab_volume)
          call write_reflect(atom = 0,photo_volume = slab_volume)
        else
          call write_refract(0)
          call write_absorp(0)
          call write_reflect(0)
        end if
      end if
    end if
  end subroutine optics_calculate
Call graph
optics_calculate calls write_conduct, write_absorp, jdos_utils_calculate, dos_utils_calculate_at_e, elec_read_optical_mat, make_weights, calc_epsilon_2, calc_epsilon_1, calc_refract, calc_reflect, calc_conduct, write_epsilon, calc_loss_fn, write_refract, dos_utils_set_efermi, write_loss_fn, write_reflect, calc_absorp, elec_dealloc_optical
write_conduct calls io_file_unit
write_absorp calls io_file_unit
jdos_utils_calculate calls dos_utils_set_efermi, io_time, calculate_jdos, setup_energy_scale, elec_read_band_gradient, jdos_utils_merge, io_error
dos_utils_calculate_at_e calls io_time, elec_read_band_gradient, io_error
elec_read_optical_mat calls io_file_unit, io_time, io_error, algor_dist_array, comms_send, comms_recv
make_weights calls cell_get_symmetry, io_error
write_epsilon calls io_file_unit
write_refract calls io_file_unit
dos_utils_set_efermi calls dos_utils_calculate, comms_bcast, io_error, comms_reduce
write_loss_fn calls io_file_unit
write_reflect calls io_file_unit
elec_dealloc_optical calls io_error
dos_utils_calculate calls comms_bcast, io_time, elec_read_band_gradient, io_error, dos_utils_merge
cell_get_symmetry calls comms_bcast, io_file_unit, io_error
calculate_jdos calls io_error, doslin, gaussian, allocate_jdos, doslin_sub_cell_corners
setup_energy_scale calls comms_bcast, io_error, comms_reduce
elec_read_band_gradient calls elec_read_optical_mat, elec_dealloc_optical, comms_bcast, io_file_unit, io_time, io_error, algor_dist_array, comms_send, comms_recv
jdos_utils_merge calls comms_reduce
algor_dist_array calls io_error
dos_utils_merge calls comms_reduce
allocate_jdos calls io_error
doslin_sub_cell_corners calls heap_sort
optados calls optics_calculate