param_dist – OptaDOS
param_dist Subroutine
97 statements
Source File
public subroutine param_dist()
Uses
od_comms
od_io
Arguments
None
Calls
Called by
Contents
Source Code
param_dist
Source Code
  subroutine param_dist
    !-----------------------------------------------------
    ! Send the parameters from the root node to all others
    !-----------------------------------------------------
    use od_comms, only: comms_bcast, on_root
    use od_io, only: io_error
    implicit none
    integer :: ierr
    call comms_bcast(output_format, len(output_format))
    call comms_bcast(devel_flag, len(devel_flag))
    call comms_bcast(iprint, 1)
    call comms_bcast(energy_unit, len(energy_unit))
    call comms_bcast(length_unit, len(length_unit))
    call comms_bcast(dos, 1)
    call comms_bcast(pdos, 1)
    call comms_bcast(jdos, 1)
    call comms_bcast(optics, 1)
    call comms_bcast(photo, 1)
    call comms_bcast(photo_photon_sweep, 1)
    call comms_bcast(core, 1)
    call comms_bcast(compare_dos, 1)
    call comms_bcast(compare_jdos, 1)
    call comms_bcast(fixed, 1)
    call comms_bcast(adaptive, 1)
    call comms_bcast(linear, 1)
    call comms_bcast(quad, 1)
    call comms_bcast(dos_nbins, 1)
    call comms_bcast(compute_band_energy, 1)
    call comms_bcast(compute_band_gap, 1)
    call comms_bcast(adaptive_smearing, 1)
    call comms_bcast(fixed_smearing, 1)
    call comms_bcast(linear_smearing, 1)
    call comms_bcast(hybrid_linear, 1)
    call comms_bcast(hybrid_linear_grad_tol, 1)
    call comms_bcast(dos_per_volume, 1)
    call comms_bcast(efermi_user, 1)
    call comms_bcast(efermi_choice, len(efermi_choice))
    call comms_bcast(finite_bin_correction, 1)
    call comms_bcast(numerical_intdos, 1)
    call comms_bcast(jdos_max_energy, 1)
    call comms_bcast(jdos_spacing, 1)
    call comms_bcast(scissor_op, 1)
    call comms_bcast(optics_geom, len(optics_geom))
    call comms_bcast(optics_qdir(1), 3)
    call comms_bcast(optics_intraband, 1)
    call comms_bcast(optics_drude_broadening, 1)
    call comms_bcast(core_chemical_shift, 1)
    call comms_bcast(core_geom, len(core_geom))
    call comms_bcast(core_type, len(core_type))
    call comms_bcast(core_qdir(1), 3)
    call comms_bcast(core_LAI_broadening, 1)
    call comms_bcast(LAI_gaussian_width, 1)
    call comms_bcast(LAI_gaussian, 1)
    call comms_bcast(LAI_lorentzian_width, 1)
    call comms_bcast(LAI_lorentzian_scale, 1)
    call comms_bcast(LAI_lorentzian_offset, 1)
    call comms_bcast(LAI_lorentzian, 1)
    call comms_bcast(dos_per_volume, 1)
    call comms_bcast(dos_min_energy, 1)
    call comms_bcast(dos_max_energy, 1)
    call comms_bcast(dos_spacing, 1)
    call comms_bcast(legacy_file_format, 1)
    call comms_bcast(projectors_string, len(projectors_string))
    call comms_bcast(set_efermi_zero, 1)
    !
    ! Photoemission
    ! TODO: Broadcast the rest of the photoemission parameters!!
    call comms_bcast(photo_model, len(photo_model))
    call comms_bcast(photo_momentum, len(photo_momentum))
    call comms_bcast(photo_photon_energy, 1)
    if (photo_photon_sweep) then
      call comms_bcast(photo_photon_min, 1)
      call comms_bcast(photo_photon_max, 1)
    end if
    call comms_bcast(photo_work_function, 1)
    ! call comms_bcast(photo_surface_area, 1)
    ! call comms_bcast(photo_slab_volume, 1)
    call comms_bcast(photo_slab_max, 1)
    call comms_bcast(photo_slab_min, 1)
    call comms_bcast(photo_layer_choice, len(photo_layer_choice))
    call comms_bcast(photo_max_layer, 1)
    call comms_bcast(photo_elec_field, 1)
    call comms_bcast(photo_remove_box_states,1)
    call comms_bcast(photo_len_imfp_const, 1)
    if (.not. on_root) then
      allocate (photo_imfp_const(photo_len_imfp_const), stat=ierr)
      if (ierr /= 0) call io_error('Error: param_dist - allocation failed for photo_imfp_const')
    end if
    call comms_bcast(photo_imfp_const(1), photo_len_imfp_const)
    call comms_bcast(photo_bulk_cutoff, 1)
    call comms_bcast(photo_temperature, 1)
    call comms_bcast(write_photo_output, len(write_photo_output))
    call comms_bcast(photo_theta_lower, 1)
    call comms_bcast(photo_theta_upper, 1)
    call comms_bcast(photo_phi_lower, 1)
    call comms_bcast(photo_phi_upper, 1)
    call comms_bcast(num_exclude_bands, 1)
    if (num_exclude_bands > 1) then
      if (.not. on_root) then
        allocate (exclude_bands(num_exclude_bands), stat=ierr)
        if (ierr /= 0) call io_error('Error allocating exclude_bands in param_read')
      end if
      call comms_bcast(exclude_bands(1), num_exclude_bands)
    end if
  end subroutine param_dist
Call graph
param_dist calls comms_bcast, io_error
optados calls param_dist