param_read – OptaDOS
param_read Subroutine
320 statements
Source File
public subroutine param_read()
Uses
od_cell
od_io
od_constants
change change change
Arguments
None
Calls
Called by
Contents
Source Code
param_read
Source Code
  subroutine param_read()
    !==================================================================!
    !                                                                  !
    ! Read parameters and calculate derived values                     !
    !                                                                  !
    !===================================================================
    use od_constants, only: bohr2ang
    use od_io, only: io_error, seedname, stderr
    use od_cell, only: cell_get_atoms, cell_read_cell
    implicit none
    !local variables
    integer :: i_temp, loop, ierr
    logical :: found
    character(len=20), allocatable :: task_string(:)
    character(len=20) :: c_string
    call param_in_file
    iprint = 1             ! Verbosity
    call param_get_keyword('iprint', found, i_value=iprint)
    legacy_file_format = .false.
    call param_get_keyword('legacy_file_format', found, l_value=legacy_file_format)
    energy_unit = 'ev'          !
    call param_get_keyword('energy_unit', found, c_value=energy_unit)
    if (index(energy_unit, 'ev') == 0 .and. index(energy_unit, 'ry') == 0 .and. index(energy_unit, 'ha') == 0) &
      call io_error('Error: value of energy_unit not recognised in param_read')
    dos = .false.; pdos = .false.; pdis = .false.; jdos = .false.; optics = .false.
    core = .false.; compare_dos = .false.; compare_jdos = .false.; photo = .false.; photo_photon_sweep = .false.
    call param_get_vector_length('task', found, i_temp)
    if (found .and. i_temp > 0) then
      allocate (task_string(i_temp), stat=ierr)
      if (ierr /= 0) call io_error('Error: param_read - allocation failed for task_string')
      call param_get_keyword_vector('task', found, i_temp, c_value=task_string)
      do loop = 1, i_temp
        if (index(task_string(loop), 'optics') > 0) then
          optics = .true.
        elseif (index(task_string(loop), 'core') > 0) then
          core = .true.
        elseif (index(task_string(loop), 'compare_jdos') > 0) then
          jdos = .true.; compare_jdos = .true.
        elseif (index(task_string(loop), 'jdos') > 0) then
          jdos = .true.
        elseif (index(task_string(loop), 'pdos') > 0) then
          pdos = .true.
        elseif (index(task_string(loop), 'pdispersion') > 0) then
          pdis = .true.
        elseif (index(task_string(loop), 'compare_dos') > 0) then
          dos = .true.; compare_dos = .true.
        elseif (index(task_string(loop), 'dos') > 0) then
          dos = .true.
        elseif (index(task_string(loop), 'photoemission') > 0) then
          photo = .true.
        elseif (index(task_string(loop), 'photon_sweep') > 0) then
          photo = .true.; photo_photon_sweep = .true.
        elseif (index(task_string(loop), 'none') > 0) then
          dos = .false.; pdos = .false.; jdos = .false.; optics = .false.; core = .false.
        elseif (index(task_string(loop), 'all') > 0) then
          dos = .true.; pdos = .true.; jdos = .true.; optics = .true.; core = .true.
        else
          call io_error('Error: value of task unrecognised in param_read')
        end if
      end do
      deallocate (task_string, stat=ierr)
      if (ierr /= 0) call io_error('Error: param_read - deallocation failed for task_string')
    end if
    if ((compare_dos .or. compare_jdos) .and. (pdos .or. core .or. optics .or. photo)) &
      call io_error('Error: compare_dos/compare_jdos are not comptable with pdos, core, optics or photoemission tasks')
    if (pdis .and. (optics .or. core .or. jdos .or. pdos .or. dos .or. compare_dos .or. compare_jdos .or. photo)) &
      call io_error('Error: projected bandstructure not compatible with any other tasks')
    i_temp = 0
    fixed = .false.; adaptive = .false.; linear = .false.; quad = .false.
    call param_get_keyword('broadening', found, c_value=c_string)
    if (found) then
      if (index(c_string, 'fixed') > 0) then
        fixed = .true.
      elseif (index(c_string, 'adaptive') > 0) then
        adaptive = .true.
      elseif (index(c_string, 'linear') > 0) then
        linear = .true.
      elseif (index(c_string, 'quad') > 0) then
        quad = .true.
        !          fixed=.true.;adaptive=.true.;linear=.true.
      else
        call io_error('Error: value of broadening unrecognised in param_read')
      end if
    end if
    if (compare_dos .or. compare_jdos) then
      fixed = .true.; adaptive = .true.; linear = .true.
    end if
    if (.not. pdis .and. .not. (fixed .or. adaptive .or. linear .or. quad)) then ! Pick a default
      adaptive = .true.
    end if
    kpoint_mp_grid = -999
    call param_get_keyword_vector('kpoint_mp_grid', found, 3, i_value=kpoint_mp_grid)
    length_unit = 'ang'         !
    lenconfac = 1.0_dp
    call param_get_keyword('length_unit', found, c_value=length_unit)
    if (length_unit .ne. 'ang' .and. length_unit .ne. 'bohr') &
      call io_error('Error: value of length_unit not recognised in param_read')
    if (length_unit .eq. 'bohr') lenconfac = 1.0_dp/bohr2ang
    adaptive_smearing = 0.4_dp ! LinDOS default
    call param_get_keyword('adaptive_smearing', found, r_value=adaptive_smearing)
    fixed_smearing = 0.3_dp ! LinDOS default
    call param_get_keyword('fixed_smearing', found, r_value=fixed_smearing)
    linear_smearing = 0.0_dp
    call param_get_keyword('linear_smearing', found, r_value=linear_smearing)
    efermi_user = -999.0_dp
    if (.not. pdis) then
      efermi_choice = "optados"
    else
      efermi_choice = "file"
    end if
    call param_get_efermi('efermi', found, efermi_choice, efermi_user)
    compute_band_energy = .true.
    call param_get_keyword('compute_band_energy', found, l_value=compute_band_energy)
    ! Here we apply a chemical shift to the core energy if supplied by the user
    core_chemical_shift = -1.0_dp ! Mizoguchi chemical shift is always +ve
    call param_get_keyword('core_chemical_shift', found, r_value=core_chemical_shift)
    if (core_chemical_shift > 0.0_dp) compute_band_gap = .true.
    ! Force all Gaussians to be greater than the width of a bin. When using numerical_indos
    ! this is critical for counting all of the Gaussian DOS peaks.
    ! When using semi-analytic integration it is desirable to show up very sharp peaks in the
    ! DOS. However, the intDOS will not be affected.
    finite_bin_correction = .true.
    call param_get_keyword('finite_bin_correction', found, l_value=finite_bin_correction)
    ! Perform fixed and adaptive smearing summing the contribution of each Gaussian
    ! instead of the new and better way of taking the erf. Left in for comparison to LinDOS
    numerical_intdos = .false.
    call param_get_keyword('numerical_intdos', found, l_value=numerical_intdos)
    ! Whenever very flat features are found when performing linear broadening, revert to adaptive.
    ! The tolerance is the gradient of the band at the kpoint.
    ! N.B. Finite_bin_correction may also be set, to further improve the spectra.
    hybrid_linear = .false.
    call param_get_keyword('hybrid_linear', found, l_value=hybrid_linear)
    hybrid_linear_grad_tol = 0.01_dp ! Seems about right for getting semi-core states correctly integrated.
    call param_get_keyword('hybrid_linear_grad_tol', found, r_value=hybrid_linear_grad_tol)
    set_efermi_zero = .false.
    if (pdis) set_efermi_zero = .true.
    call param_get_keyword('set_efermi_zero', found, l_value=set_efermi_zero)
    dos_per_volume = .false.
    call param_get_keyword('dos_per_volume', found, l_value=dos_per_volume)
    dos_min_energy = -huge(dos_min_energy)
    call param_get_keyword('dos_min_energy', found, r_value=dos_min_energy)
    dos_max_energy = huge(dos_max_energy)
    call param_get_keyword('dos_max_energy', found, r_value=dos_max_energy)
    dos_spacing = -1.0_dp
    call param_get_keyword('dos_spacing', found, r_value=dos_spacing)
    dos_nbins = -1 ! 10001 LinDOS default
    call param_get_keyword('dos_nbins', found, i_value=dos_nbins)
    projectors_string = ''
    if (pdos) call param_get_keyword('pdos', found, c_value=projectors_string)
    if (pdos .and. (len_trim(projectors_string) == 0)) call io_error('pdos requested but pdos is not specified')
    if (pdis) call param_get_keyword('pdispersion', found, c_value=projectors_string)
    if (pdis .and. (len_trim(projectors_string) == 0)) &
         & call io_error('pdispersion requested but pdispersion keyword is not specified')
    jdos_max_energy = -1.0_dp !! change
    call param_get_keyword('jdos_max_energy', found, r_value=jdos_max_energy)
    jdos_spacing = 0.01_dp !! change
    call param_get_keyword('jdos_spacing', found, r_value=jdos_spacing)
    num_exclude_bands = 0
    call param_get_range_vector('exclude_bands', found, num_exclude_bands, lcount=.true.)
    if (found) then
      if (num_exclude_bands < 1) call io_error('Error: problem reading exclude_bands')
      allocate (exclude_bands(num_exclude_bands), stat=ierr)
      if (ierr /= 0) call io_error('Error allocating exclude_bands in param_read')
      call param_get_range_vector('exclude_bands', found, num_exclude_bands, .false., exclude_bands)
      if (any(exclude_bands < 1)) &
        call io_error('Error: exclude_bands must contain positive numbers')
    end if
    compute_band_gap = .true.
    call param_get_keyword('compute_band_gap', found, l_value=compute_band_gap)
    devel_flag = ' '
    call param_get_keyword('devel_flag', found, c_value=devel_flag)
    output_format = 'xmgrace'
    call param_get_keyword('output_format', found, c_value=output_format)
    if (index(output_format, 'xmgrace') == 0 .and. index(output_format, 'gnuplot') == 0) &
      call io_error('Error: value of output_format not recognised in param_read')
    optics_geom = 'polycrys'
    call param_get_keyword('optics_geom', found, c_value=optics_geom)
    if (index(optics_geom, 'polar') == 0 .and. index(optics_geom, 'polycrys') == 0 .and. index(optics_geom, 'tensor') == 0) &
      call io_error('Error: value of optics_geom not recognised in param_read')
    scissor_op = 0.0_dp !! change
    call param_get_keyword('scissor_op', found, r_value=scissor_op)
    optics_qdir = 0.0_dp
    call param_get_keyword_vector('optics_qdir', found, 3, r_value=optics_qdir)
    if (index(optics_geom, 'polar') > 0 .and. .not. found) &
      call io_error('Error: polarised or unpolarised optics geometry requested but optics_qdir is not set')
    if ((index(optics_geom, 'polycrys') > 0 .or. index(optics_geom, 'tensor') > 0) .and. found) &
      call io_error('Error: polycrystalline optics geometry or full dielectric tensor requested but optics_qdir is set')
    optics_intraband = .false.
    call param_get_keyword('optics_intraband', found, l_value=optics_intraband)
    optics_drude_broadening = 1.0e14_dp
    call param_get_keyword('optics_drude_broadening', found, r_value=optics_drude_broadening)
    optics_lossfn_broadening = .false.
    optics_lossfn_gaussian = 0.0_dp
    call param_get_keyword('optics_lossfn_broadening', optics_lossfn_broadening, r_value=optics_lossfn_gaussian)
    if (optics_lossfn_gaussian < 0.0_dp) call io_error('Error: optics_lossfn_broadening must be positive')
    if (abs(optics_lossfn_gaussian) < 1.0e-6_dp) optics_lossfn_broadening = .false. ! trap too small values
    core_geom = 'polycrys'
    call param_get_keyword('core_geom', found, c_value=core_geom)
    if ((index(core_geom, 'polycrys') == 0) .and. (index(core_geom, 'polar') == 0)) &
      call io_error('Error: value of core_geom not recognised in param_read')
    core_type = 'absorption'
    call param_get_keyword('core_type', found, c_value=core_type)
    if (core_type .ne. 'absorption' .and. core_type .ne. 'emission' .and. core_type .ne. 'all') &
      call io_error('Error: value of core_type not recognised in param_read')
    core_qdir = 0.0_dp
    call param_get_keyword_vector('core_qdir', found, 3, r_value=core_qdir)
    if (index(core_geom, 'polar') > 0 .and. .not. found) &
      call io_error('Error: polarised core geometry requested but core_qdir is not set')
    if (index(core_geom, 'polycrys') > 0 .and. found) &
      call io_error('Error: polycrystalline core geometry requested but core_qdir is set')
    core_LAI_broadening = .false.
    call param_get_keyword('core_lai_broadening', found, l_value=core_LAI_broadening)
    LAI_gaussian_width = 0.0_dp
    LAI_gaussian = .false.
    call param_get_keyword('lai_gaussian_width', found, r_value=LAI_gaussian_width)
    if (LAI_gaussian_width .gt. 1E-14) LAI_gaussian = .true.
    if (LAI_gaussian_width .lt. 0.0_dp) call io_error('Error: LAI_gaussian_width must be positive')
    LAI_lorentzian_width = 0.0_dp
    LAI_lorentzian = .false.
    call param_get_keyword('lai_lorentzian_width', found, r_value=LAI_lorentzian_width)
    if (LAI_lorentzian_width .gt. 1E-14) LAI_lorentzian = .true.
    if (LAI_lorentzian_width .lt. 0.0_dp) call io_error('Error: LAI_lorentzian_width must be positive')
    LAI_lorentzian_scale = 0.1_dp
    call param_get_keyword('lai_lorentzian_scale', found, r_value=LAI_lorentzian_scale)
!    if (LAI_lorentzian_scale.gt.1E-14) LAI_lorentzian=.true.
    if (LAI_lorentzian_scale .lt. 0.0_dp) call io_error('Error: LAI_lorentzian_scale must be positive')
    LAI_lorentzian_offset = 0.0_dp
    call param_get_keyword('lai_lorentzian_offset', found, r_value=LAI_lorentzian_offset)
    if (LAI_lorentzian_offset .lt. 0.0_dp) call io_error('Error: LAI_lorentzian_offset must be positive')
    ! Photoemission parameters - V.Chang Nov-2020
    photo_momentum = 'crystal'
    call param_get_keyword('photo_momentum', found, c_value=photo_momentum)
    if (index(photo_momentum, 'kp') == 0 .and. index(photo_momentum, 'crystal') == 0 .and. index(photo_momentum, 'operator') == 0) &
      call io_error('Error: value of momentum not recognised in param_read')
    write_photo_output = 'off'
    call param_get_keyword('write_photo_output', found, c_value=write_photo_output)
    if (index(write_photo_output, 'qe_matrix') == 0 .and. index(write_photo_output, 'e_bind') == 0 .and. &
      & index(write_photo_output, 'off') == 0) then
      call io_error('Error: value of write_photo_output output not recognised in param_read')
    end if
    photo_model = '1step'
    call param_get_keyword('photo_model', found, c_value=photo_model)
    if (index(photo_model, '3step') > 0 .and. index(photo_model, '1step') > 0 .or. &
        index(photo_model, '3step') > 0 .and. index(photo_model, 'ds_like_pe') > 0 .or. &
        index(photo_model, '1step') > 0 .and. index(photo_model, 'ds_like_pe') > 0) then
      call io_error('Error: value of photoemission model not recognised in param_read')
    end if
    call param_get_keyword('photo_work_function', found, r_value=photo_work_function)
    if (photo .and. .not. found) &
      call io_error('Error: please set workfunction for photoemission calculation')
    photo_theta_lower = 0.0_dp
    call param_get_keyword('photo_theta_lower', found, r_value=photo_theta_lower)
    photo_theta_upper = 90.0_dp
    call param_get_keyword('photo_theta_upper', found, r_value=photo_theta_upper)
    photo_phi_lower = 0.0_dp
    call param_get_keyword('photo_phi_lower', found, r_value=photo_phi_lower)
    photo_phi_upper = 90.0_dp
    call param_get_keyword('photo_phi_upper', found, r_value=photo_phi_upper)
    photo_photon_min = 3.0_dp
    call param_get_keyword('photo_photon_min', found, r_value=photo_photon_min)
    photo_photon_max = 2.0_dp
    call param_get_keyword('photo_photon_max', found, r_value=photo_photon_max)
    if (photo_photon_min .gt. photo_photon_max .and. photo_photon_sweep) &
      call io_error('Error: max photon value is lower than min photon value or they have not been set')
    call param_get_keyword('photo_photon_energy', found, r_value=photo_photon_energy)
    if (found .and. photo_photon_sweep) call io_error('Error: cannot set photon energy for photon energy sweep calculation')
    if (photo .and. .not. found .and. .not. photo_photon_sweep) &
      call io_error('Error: please set photon energy for photoemission calculation')
    photo_bulk_cutoff = 10.0_dp
    call param_get_keyword('photo_bulk_cutoff', found, r_value=photo_bulk_cutoff)
    if (found) photo_bulk_cutoff = -1*log(photo_bulk_cutoff)
    photo_temperature = 298.0_dp
    call param_get_keyword('photo_temperature', found, r_value=photo_temperature)
    ! call param_get_keyword('photo_surface_area', found, r_value=photo_surface_area)
    ! if (photo .and. .not. found) &
    ! call io_error('Error: please set surface area for photoemission calculation')
    ! call param_get_keyword('photo_slab_volume', found, r_value=photo_slab_volume)
    ! if (photo .and. .not. found) &
    !   call io_error('Error: please set volume of the slab for photoemission calculation')
    photo_slab_min = 0.0_dp
    call param_get_keyword('photo_slab_min', found, r_value=photo_slab_min)
    ! if(photo .and. .not. found) &
    !     call io_error('Error: please set volume of the slab for photoemission calculation')
    photo_slab_max = 0.0_dp
    call param_get_keyword('photo_slab_max', found, r_value=photo_slab_max)
    if (photo_slab_max .lt. 0.0_dp .or. photo_slab_min .lt. 0.0_dp) then
      call io_error('Error: the supplied min or max values are negative, which causes faulty calculations!')
    end if
    if (photo_slab_max .lt. photo_slab_min) then
      call io_error('Error: the supplied slab_max value is less than the slab_min value!')
    end if
    photo_remove_box_states = .False.
    call param_get_keyword('photo_remove_box_states', found, l_value=photo_remove_box_states)
    photo_layer_choice = 'optados'
    call param_get_keyword('photo_layer_choice', found, c_value=photo_layer_choice)
    photo_max_layer = -1
    call param_get_keyword('photo_max_layer', found, i_value=photo_max_layer)
    if (photo .and. index(photo_layer_choice, 'user') .gt. 0 .and. .not. found) &
      call io_error('Error: max # of layers was set to be supplied by user, but does not exist in input')
    photo_elec_field = 0.00_dp
    call param_get_keyword('photo_elec_field', found, r_value=photo_elec_field)
    call param_get_vector_length('photo_imfp_const', found, i_temp)
    if (found) then
      photo_len_imfp_const = i_temp
      allocate (photo_imfp_const(i_temp), stat=ierr)
      if (ierr /= 0) call io_error('Error: param_read - allocation failed for photo_imfp_const')
      call param_get_keyword_vector('photo_imfp_const', found, i_temp, r_value=photo_imfp_const)
    else
      photo_len_imfp_const = 1
      allocate (photo_imfp_const(1), stat=ierr)
      if (ierr /= 0) call io_error('Error: param_read - allocation failed for photo_imfp_const')
      photo_imfp_const = 0.0_dp
    end if
    if (photo .and. .not. found) &
      call io_error('Error: constant imfp, but photo_imfp_const is not set')
    num_atoms = 0
    num_species = 0
    num_crystal_symmetry_operations = 0
    if (pdos .or. pdis .or. core .or. optics .or. photo .or. jdos) then
      ! try to read in the atoms from the cell file.
      ! We don't need them otherwise, so let's not bother
      !  if(index(devel_flag,'old_filename')>0) then
      ! No longer need to call get_atoms as we're forcing people who use the legacy code to make an -out.cell
      !     call cell_get_atoms
      !  else
      call cell_read_cell
      !  end if
    end if
    ! check to see that there are no unrecognised keywords
    if (any(len_trim(in_data(:)) > 0)) then
      write (stderr, '(1x,a)') 'The following section of file '//trim(seedname)//'.odi contained unrecognised keywords'
      write (stderr, *)
      do loop = 1, num_lines
        if (len_trim(in_data(loop)) > 0) then
          write (stderr, '(1x,a)') trim(in_data(loop))
        end if
      end do
      write (stderr, *)
      call io_error('Unrecognised keyword(s) in input file')
    end if
    call param_uppercase()
    deallocate (in_data, stat=ierr)
    if (ierr /= 0) call io_error('Error deallocating in_data in param_read')
    ! =============================== !
    ! Some checks and initialisations !
    ! =============================== !
    if (dos_min_energy .ge. dos_max_energy) then
      call io_error('Error: must have dos_min_energy < dos_max_energy')
    end if
    if ((dos_nbins > 0) .and. (dos_spacing > 0.0_dp)) then
      call io_error('Error: only one of dos_nbins and dos_spacing may be set')
    end if
    if ((dos_nbins < 0) .and. (dos_spacing < 0.0_dp)) then
      dos_spacing = 0.005 ! Roughly similar to LinDOS
    end if
    return
  end subroutine param_read
Call graph
param_read calls io_error, cell_read_cell
cell_read_cell calls io_error, io_file_unit, utility_cart_to_frac, cell_get_real_lattice, utility_frac_to_cart, utility_lowercase
cell_get_real_lattice calls io_file_unit
optados calls param_read