pdis_calculate – OptaDOS
pdis_calculate Subroutine
27 statements
Source File
public subroutine pdis_calculate()
Uses
od_parameters
od_comms
od_electronic
od_projection_utils
od_io
Arguments
None
Calls
Called by
Contents
Source Code
pdis_calculate
Source Code
  subroutine pdis_calculate
    use od_electronic, only: elec_pdis_read, efermi_castep, efermi
    use od_projection_utils, only: projection_merge, projection_get_string, projection_analyse_orbitals
    use od_comms, only: on_root
    use od_parameters, only: set_efermi_zero, iprint
    use od_io, only: stdout
    implicit none
    if (on_root) then
      write (stdout, *)
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)') '+                 Projected Dispersion Curve Calculation                     +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)')
    end if
    ! read in the pdos weights
    call elec_pdis_read
    ! look at the orbitals and figure out which atoms / states we have
    call projection_analyse_orbitals
    ! parse the pdis string to see what we want
    call projection_get_string
    ! form the right matrix elements
    call projection_merge
    ! set efermi
    if (on_root) write (stdout, '(1x,a1,a46,f8.4,a3,12x,a8)') "|",&
                          &" Set fermi energy from file : ", efermi_castep, " eV", "  <- EfC"
    efermi = efermi_castep
    ! write everything out
    if (on_root .and. (iprint > 2)) then
      call pdis_report_projectors
    end if
    if (on_root) then
      call pdis_write
    end if
  end subroutine pdis_calculate
Call graph
pdis_calculate calls elec_pdis_read, projection_get_string, projection_analyse_orbitals, projection_merge
elec_pdis_read calls io_file_unit, comms_bcast, io_error
projection_get_string calls io_error
projection_analyse_orbitals calls io_error
projection_merge calls io_error
optados calls pdis_calculate