pdos_calculate – OptaDOS
pdos_calculate Subroutine
28 statements
Source File
public subroutine pdos_calculate()
Uses
od_parameters
od_dos_utils
od_comms
od_electronic
od_projection_utils
od_io
Arguments
None
Calls
Called by
Contents
Source Code
pdos_calculate
Source Code
  subroutine pdos_calculate
    use od_electronic, only: elec_pdos_read, efermi, efermi_set
    use od_dos_utils, only: dos_utils_calculate, dos_utils_set_efermi
    use od_projection_utils, only: projection_merge, projection_get_string, projection_analyse_orbitals
    use od_comms, only: on_root
    use od_parameters, only: iprint, set_efermi_zero
    use od_io, only: stdout
    implicit none
    if (on_root) then
      write (stdout, *)
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)') '+                 Projected Density Of States Calculation                    +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, '(1x,a78)')
    end if
    ! read in the pdos weights
    call elec_pdos_read
    ! look at the orbitals and figure out which atoms / states we have
    call projection_analyse_orbitals
    ! parse the pdos string to see what we want
    call projection_get_string
    ! form the right matrix elements
    call projection_merge
    if (on_root .and. (iprint > 2)) then
      call pdos_report_projectors
    end if
    ! now compute the weighted dos
    call dos_utils_calculate(matrix_weights, dos_partial)
    ! and write everything out
    if (set_efermi_zero .and. .not. efermi_set) call dos_utils_set_efermi
    if (on_root) then
      call pdos_write
    end if
  end subroutine pdos_calculate
Call graph
pdos_calculate calls elec_pdos_read, projection_get_string, projection_analyse_orbitals, projection_merge, dos_utils_calculate, dos_utils_set_efermi
elec_pdos_read calls io_file_unit, comms_bcast, comms_recv, comms_send, io_error
projection_get_string calls io_error
projection_analyse_orbitals calls io_error
projection_merge calls io_error
dos_utils_calculate calls comms_bcast, io_error, dos_utils_merge, io_time, elec_read_band_gradient
dos_utils_set_efermi calls dos_utils_calculate, comms_bcast, io_error, comms_reduce
dos_utils_merge calls comms_reduce
elec_read_band_gradient calls io_file_unit, comms_bcast, comms_recv, comms_send, io_error, io_time, algor_dist_array, elec_read_optical_mat, elec_dealloc_optical
algor_dist_array calls io_error
elec_read_optical_mat calls io_file_unit, comms_recv, comms_send, io_error, io_time, algor_dist_array
elec_dealloc_optical calls io_error
optados calls pdos_calculate