projection_merge – OptaDOS
projection_merge Subroutine
25 statements
Source File
public subroutine projection_merge()
Uses
od_electronic
od_comms
od_io
od_cell
Arguments
None
Calls
Called by
Contents
Source Code
projection_merge
Source Code
  subroutine projection_merge
    !===============================================================================
    ! This subroutine accumulates the weights of desired projectors into the
    ! matrix_weights array.
    !===============================================================================
    use od_electronic, only: pdos_orbital, pdos_weights, pdos_mwab, nspins
    use od_cell, only: num_kpoints_on_node
    use od_comms, only: my_node_id
    use od_io, only: io_error, stdout
    implicit none
    integer :: N, N_spin, n_eigen, nproj, orb, ierr
    allocate (matrix_weights(num_proj, pdos_mwab%nbands, num_kpoints_on_node(my_node_id), nspins), stat=ierr)
    if (ierr /= 0) call io_error('Error: projection_merge - allocation of matrix_weights failed')
    matrix_weights = 0.0_dp
    do N = 1, num_kpoints_on_node(my_node_id) ! Loop over kpoints
      do N_spin = 1, nspins                  ! Loop over spins
        do n_eigen = 1, pdos_mwab%nbands    ! Loop over unoccupied states
          do nproj = 1, num_proj
            do orb = 1, pdos_mwab%norbitals
              if (projection_array(pdos_orbital%species_no(orb), pdos_orbital%rank_in_species(orb) &
                                   , pdos_orbital%am_channel(orb) + 1, nproj) == 1) then
                matrix_weights(nproj, n_eigen, N, N_spin) = matrix_weights(nproj, n_eigen, N, N_spin) + &
                                                            pdos_weights(orb, n_eigen, N, N_spin)
              end if
            end do
          end do
        end do
      end do
    end do
    return
  end subroutine projection_merge
Call graph
projection_merge calls io_error
pdos_calculate calls projection_merge
pdis_calculate calls projection_merge
optados calls pdos_calculate, pdis_calculate