projection_analyse_orbitals – OptaDOS
projection_analyse_orbitals Subroutine
30 statements
Source File
public subroutine projection_analyse_orbitals()
Uses
od_electronic
od_io
od_cell
od_constants
Arguments
None
Calls
Called by
Contents
Source Code
projection_analyse_orbitals
Source Code
  subroutine projection_analyse_orbitals
    use od_electronic, only: pdos_orbital, pdos_mwab
    use od_cell, only: atoms_symbol, num_species
    use od_constants, only: periodic_table_name
    use od_io, only: io_error
    implicit none
    integer :: loop, loop2, counter, ierr
    if (maxval(pdos_orbital%species_no(:)) > num_species) &
      call io_error('Error: projection_analyse_substring - more species in pdos file than in cell file')
    allocate (proj_sites(maxval(pdos_orbital%species_no(:))), stat=ierr)
    if (ierr /= 0) call io_error('Error: projection_analyse_substring - allocation of proj_sites failed')
    allocate (proj_am(maxval(pdos_orbital%species_no(:)), max_am), stat=ierr)
    if (ierr /= 0) call io_error('Error: projection_analyse_substring - allocation of proj_am failed')
    allocate (proj_symbol(maxval(pdos_orbital%species_no(:))), stat=ierr)
    if (ierr /= 0) call io_error('Error: projection_analyse_substring - allocation of proj_symbol failed')
    proj_sites = 0; proj_am = 0
    do loop = 1, pdos_mwab%norbitals
      if (pdos_orbital%rank_in_species(loop) > proj_sites(pdos_orbital%species_no(loop))) &
        proj_sites(pdos_orbital%species_no(loop)) = pdos_orbital%rank_in_species(loop)
      if (pdos_orbital%rank_in_species(loop) == 1) &
        proj_am(pdos_orbital%species_no(loop), pdos_orbital%am_channel(loop) + 1) = 1
    end do
    !Now need to figure out symbols for each species
    counter = 1
    do loop2 = 1, 109
      do loop = 1, num_species
        if (atoms_symbol(loop) == periodic_table_name(loop2)) then
          proj_symbol(counter) = periodic_table_name(loop2)
          counter = counter + 1
          !check atom count here
        end if
      end do
    end do
  end subroutine projection_analyse_orbitals
Call graph
projection_analyse_orbitals calls io_error
pdos_calculate calls projection_analyse_orbitals
pdis_calculate calls projection_analyse_orbitals
optados calls pdos_calculate, pdis_calculate