read_pdos_bin – OptaDOS
read_pdos_bin Subroutine
5 statements
Source File
public subroutine read_pdos_bin()
Wrapper to read a pdos binary file. Useful to keep the code tidy.
Arguments
None
Calls
Called by
Contents
Source Code
read_pdos_bin
Source Code
  subroutine read_pdos_bin()
    !! Wrapper to read a pdos binary file. Useful to keep the code tidy.
    implicit none
    write (stdout, *) " Read a binary pdos file."
    call elec_pdos_read()
  end subroutine read_pdos_bin
Call graph
read_pdos_bin calls elec_pdos_read
elec_pdos_read calls io_file_unit, comms_bcast, comms_recv, comms_send, io_error
od2od calls read_pdos_bin