read_elnes_bin – OptaDOS
read_elnes_bin Subroutine
5 statements
Source File
public subroutine read_elnes_bin()
Wrapper to read a binary elnes file. The wrapping allows us to have consistent names within the module, which makes life easier.
Arguments
None
Calls
Called by
Contents
Source Code
read_elnes_bin
Source Code
  subroutine read_elnes_bin()
    !! Wrapper to read a binary elnes file. The wrapping allows us to have
    !! consistent names within the module, which makes life easier.
    implicit none
    write (stdout, *) " Read a binary elnes file."
    call elec_read_elnes_mat()
  end subroutine read_elnes_bin
Call graph
read_elnes_bin calls elec_read_elnes_mat
elec_read_elnes_mat calls io_time, io_file_unit, comms_bcast, comms_send, io_error, comms_recv, elec_elnes_find_channel_names
elec_elnes_find_channel_names calls io_error
od2od calls read_elnes_bin