read_fem_bin – OptaDOS
read_fem_bin Subroutine
6 statements
Source File
public subroutine read_fem_bin()
Read a binary ome file. Wrapper to keep the naming tidy.
Arguments
None
Calls
Called by
Contents
Source Code
read_fem_bin
Source Code
  subroutine read_fem_bin()
    !! Read a binary ome file. Wrapper to keep the naming tidy.
    implicit none
    write (stdout, *) " Read a formatted ome file. "
    call elec_read_foptical_mat()
    write (stdout, *) " "//trim(seedname)//".fem_bin"//"--> Unformatted ome sucessfully read. "
  end subroutine read_fem_bin
Call graph
read_fem_bin calls elec_read_foptical_mat
elec_read_foptical_mat calls io_time, io_file_unit, algor_dist_array, comms_send, io_error, comms_recv, comms_reduce
algor_dist_array calls io_error
od2od calls read_fem_bin