read_ome_bin – OptaDOS
read_ome_bin Subroutine
6 statements
Source File
public subroutine read_ome_bin()
Read a binary ome file. Wrapper to keep the naming tidy.
Arguments
None
Calls
Called by
Contents
Source Code
read_ome_bin
Source Code
  subroutine read_ome_bin()
    !! Read a binary ome file. Wrapper to keep the naming tidy.
    implicit none
    write (stdout, *) " Read a formatted ome file. "
    call elec_read_optical_mat()
    write (stdout, *) " "//trim(seedname)//".ome_bin"//"--> Unformatted ome sucessfully read. "
  end subroutine read_ome_bin
Call graph
read_ome_bin calls elec_read_optical_mat
elec_read_optical_mat calls io_time, io_file_unit, algor_dist_array, comms_send, io_error, comms_recv
algor_dist_array calls io_error
od2od calls read_ome_bin