read_dome_bin – OptaDOS
read_dome_bin Subroutine
5 statements
Source File
public subroutine read_dome_bin()
Read a diagonal ome file. Wrapper to keep the naming scheme tidy.
Arguments
None
Calls
Called by
Contents
Source Code
read_dome_bin
Source Code
  subroutine read_dome_bin()
    !! Read a diagonal ome file. Wrapper to keep the naming scheme tidy.
    implicit none
    write (stdout, *) " Read a binary dome file."
    call elec_read_band_gradient()
  end subroutine read_dome_bin
Call graph
read_dome_bin calls elec_read_band_gradient
elec_read_band_gradient calls comms_bcast, io_time, io_error, algor_dist_array, io_file_unit, comms_send, comms_recv, elec_read_optical_mat, elec_dealloc_optical
algor_dist_array calls io_error
elec_read_optical_mat calls io_time, io_error, algor_dist_array, io_file_unit, comms_send, comms_recv
elec_dealloc_optical calls io_error
od2od calls read_dome_bin