read_elnes_fmt – OptaDOS
read_elnes_fmt Subroutine
46 statements
Source File
public subroutine read_elnes_fmt()
Uses
od_electronic
od_cell
od_io
Read a formatted elnes file.
Arguments
None
Calls
Called by
Contents
Source Code
read_elnes_fmt
Source Code
  subroutine read_elnes_fmt()
    !! Read a formatted elnes file.
    use od_electronic, only: elec_elnes_find_channel_names, elnes_orbital, &
         & elnes_mwab, elnes_mat
    use od_io, only: io_file_unit, seedname
    use od_cell, only: num_kpoints_on_node
    implicit none
    character(len=20) :: dummy20, dummy10
    real(dp) :: file_version
    !! The file verioson format to write. Currently we're on version 1.
    integer :: elnes_unit, ik, is, iorb, ib, indx, ierr
    !! Loop variable.
    character(len=80) :: string, string2
    !! Tempory string manipulation variable.
    write (stdout, *) " Read a formatted elnes file."
    elnes_unit = io_file_unit()
    open (unit=elnes_unit, file=trim(seedname)//".elnes_fmt", form='formatted')
    read (elnes_unit, '('//trim(format_precision)//')') file_version
    read (elnes_unit, '(a80)') elnesfile_header
    read (elnes_unit, '(a20,1x,i5)') dummy20, elnes_mwab%norbitals
    read (elnes_unit, '(a20,1x,i5)') dummy20, elnes_mwab%nbands
    read (elnes_unit, '(a20,1x,i5)') dummy20, elnes_mwab%nkpoints
    read (elnes_unit, '(a20,1x,i5)') dummy20, elnes_mwab%nspins
    write (string, '(i7,"(1x,",a,")")') elnes_mwab%norbitals, "i5"
    write (string2, '(i7,"(1x,",a,")")') elnes_mwab%norbitals*elnes_mwab%nbands*3, trim(format_precision)
    allocate (elnes_orbital%ion_no(elnes_mwab%norbitals), stat=ierr)
    if (ierr /= 0) call io_error(' Error : read_elnes_fmt cannot allocate elnes_orbital%ion_no')
    allocate (elnes_orbital%species_no(elnes_mwab%norbitals), stat=ierr)
    if (ierr /= 0) call io_error(' Error : read_elnes_fmt cannot allocate elnes_orbital%species_no')
    allocate (elnes_orbital%rank_in_species(elnes_mwab%norbitals), stat=ierr)
    if (ierr /= 0) call io_error(' Error : read_elnes_fmt cannot allocate elnes_orbitall%rank_in_species')
    allocate (elnes_orbital%shell(elnes_mwab%norbitals), stat=ierr)
    if (ierr /= 0) call io_error(' Error : read_elnes_fmt cannot allocate elnes_orbitall%shell')
    allocate (elnes_orbital%am_channel(elnes_mwab%norbitals), stat=ierr)
    if (ierr /= 0) call io_error(' Error : read_elnes_fmt cannot allocate elnes_orbital%am_channel')
    allocate (elnes_orbital%am_channel_name(elnes_mwab%norbitals), stat=ierr)
    if (ierr /= 0) call io_error(' Error : read_elnes_fmt cannot allocate elnes_orbital%am_channel_name')
    read (elnes_unit, '(a10,'//trim(string)//')') dummy10, elnes_orbital%species_no(1:elnes_mwab%norbitals)
    read (elnes_unit, '(a10,'//trim(string)//')') dummy10, elnes_orbital%rank_in_species(1:elnes_mwab%norbitals)
    read (elnes_unit, '(a10,'//trim(string)//')') dummy10, elnes_orbital%shell(1:elnes_mwab%norbitals)
    read (elnes_unit, '(a10,'//trim(string)//')') dummy10, elnes_orbital%am_channel(1:elnes_mwab%norbitals)
    allocate (elnes_mat(1:elnes_mwab%norbitals, 1:elnes_mwab%nbands, 1:3, &
                        1:num_kpoints_on_node(0), 1:elnes_mwab%nspins), stat=ierr)
    if (ierr /= 0) call io_error('Error: Problem allocating elnes_mat in read_elnes_fmt')
    do ik = 1, num_kpoints_on_node(0)
      do is = 1, elnes_mwab%nspins
        read (elnes_unit, '('//trim(string2)//')') (((elnes_mat(iorb, ib, indx, ik, is), iorb=1, elnes_mwab%norbitals), &
                                                     ib=1, elnes_mwab%nbands), indx=1, 3)
      end do
    end do
    call elec_elnes_find_channel_names()
    write (stdout, *) " "//trim(seedname)//".elnes_fmt"//"--> Formatted elnes sucessfully read. "
  end subroutine read_elnes_fmt
Call graph
read_elnes_fmt calls io_file_unit, io_error, elec_elnes_find_channel_names
elec_elnes_find_channel_names calls io_error
od2od calls read_elnes_fmt