read_pdos_fmt – OptaDOS
read_pdos_fmt Subroutine
51 statements
Source File
public subroutine read_pdos_fmt()
Uses
od_electronic
od_comms
od_io
od_cell
Read a formatted pdos file.
Arguments
None
Calls
Called by
Contents
Source Code
read_pdos_fmt
Source Code
  subroutine read_pdos_fmt()
    !! Read a formatted pdos file.
    use od_electronic, only: pdos_mwab, nbands_occ, pdos_orbital, nspins, pdos_weights
    use od_cell, only: nkpoints, kpoint_r, num_kpoints_on_node
    use od_io, only: stdout, seedname, io_file_unit
    use od_comms, only: my_node_id
    implicit none
    integer :: ik, is, ib, idummy, ierr, io
    integer :: pdos_in_unit
    character(len=80) :: string, dummy, string2
    real(dp) :: file_version
    write (stdout, *) " Read a formatted pdos file."
    !-------------------------------------------------------------------------!
    ! R E A D   T H E   D A T A   H E A D E R
    file_version = 1.0_dp
    pdos_in_unit = io_file_unit()
    open (unit=pdos_in_unit, file=trim(seedname)//".pdos_fmt", form='formatted')
    read (pdos_in_unit, '('//trim(format_precision)//')') file_version
    read (pdos_in_unit, '(a80)') pdosfile_header
    read (pdos_in_unit, '(a10, i6)') dummy, pdos_mwab%nkpoints
    read (pdos_in_unit, '(a10, i6)') dummy, pdos_mwab%nspins
    read (pdos_in_unit, '(a10, i6)') dummy, pdos_mwab%norbitals
    read (pdos_in_unit, '(a10, i6)') dummy, pdos_mwab%nbands
    !write(stdout,'(a, i6)') "DEBUG: pdos_mwab%nkpoints= ",pdos_mwab%nkpoints
    !write(stdout,'(a, i6)') "DEBUG: pdos_mwab%nspins= ",pdos_mwab%nspins
    !write(stdout,'(a, i6)') "DEBUG: pdos_mwab%norbitals= ",pdos_mwab%norbitals
    !write(stdout,'(a, i6)') "DEBUG: pdos_mwab%nbands= ",pdos_mwab%nbands
    write (string, '(i7,"(1x,",a,")")') pdos_mwab%norbitals, "i5"
    write (string2, '(i7,"(1x,",a,")")') pdos_mwab%norbitals, trim(format_precision)
    ! These should all be allocated!
    allocate (pdos_orbital%species_no(pdos_mwab%norbitals), stat=ierr)
    if (ierr /= 0) call io_error(" Error : cannot allocate pdos_orbital")
    allocate (pdos_orbital%rank_in_species(pdos_mwab%norbitals), stat=ierr)
    if (ierr /= 0) call io_error(" Error : cannot allocate pdos_orbital")
    allocate (pdos_orbital%am_channel(pdos_mwab%norbitals), stat=ierr)
    if (ierr /= 0) call io_error(" Error : cannot allocate pdos_orbital")
    allocate (nbands_occ(1:num_kpoints_on_node(my_node_id), 1:pdos_mwab%nspins), stat=ierr)
    if (ierr /= 0) stop " Error : cannot allocate nbands_occ"
    allocate (pdos_weights(1:pdos_mwab%norbitals, 1:pdos_mwab%nbands, &
                           1:num_kpoints_on_node(my_node_id), 1:pdos_mwab%nspins), stat=ierr)
    if (ierr /= 0) stop " Error : cannot allocate pdos_weights"
    read (pdos_in_unit, '(a60)') dummy
    read (pdos_in_unit, '('//trim(string)//')') pdos_orbital%species_no(1:pdos_mwab%norbitals)
    read (pdos_in_unit, '(a60)') dummy
    read (pdos_in_unit, '('//trim(string)//')') pdos_orbital%rank_in_species(1:pdos_mwab%norbitals)
    read (pdos_in_unit, '(a60)') dummy
    read (pdos_in_unit, '('//trim(string)//')') pdos_orbital%am_channel(1:pdos_mwab%norbitals)
    !-------------------------------------------------------------------------!
    !-------------------------------------------------------------------------!
    ! N O W   R E A D   T H E   D A T A
    ! These should already be alloacted
    ! allocate(nbands_occ(1:num_kpoints_on_node(my_node_id),1:pdos_mwab%nspins),stat=ierr)
    ! if(ierr/=0) stop " Error : cannot allocate nbands_occ"
    ! allocate(pdos_weights(1:pdos_mwab%norbitals,1:pdos_mwab%nbands, &
    !     1:num_kpoints_on_node(my_node_id),1:pdos_mwab%nspins),stat=ierr)
    ! if(ierr/=0) stop " Error : cannot allocate pdos_weights"
    do ik = 1, nkpoints
      ! The kpoint number, followed by the kpoint-vector
      read (pdos_in_unit, '(i6,3'//trim(format_precision)//')') idummy, kpoint_r(:, ik)
      do is = 1, pdos_mwab%nspins
        read (pdos_in_unit, '(i6)') idummy ! this is the spin number
        read (pdos_in_unit, '(i6)') nbands_occ(ik, is)
        do ib = 1, nbands_occ(ik, is)
          !      write(stdout,*) " ***** F U L L _ D E B U G _ P D O S _ W E I G H T S ***** "
          !      write(stdout,*) " DEBUG:", ib, ik, is
          !      write(stdout,*) "   **** ***** *****  ***** ***** *****  ***** ***** *****  "
          read (pdos_in_unit, '('//trim(string2)//')') (pdos_weights(io, ib, ik, is), io=1, pdos_mwab%norbitals)
        end do
      end do
    end do
    close (pdos_in_unit)
    write (stdout, *) " "//trim(seedname)//".pdos_fmt"//"--> Formatted pdos sucessfully read. "
  end subroutine read_pdos_fmt
Call graph
read_pdos_fmt calls io_file_unit, io_error
od2od calls read_pdos_fmt