setup_energy_scale – OptaDOS
setup_energy_scale Subroutine
38 statements
Source File
public subroutine setup_energy_scale(E)
Uses
od_parameters
od_dos_utils
od_comms
od_electronic
od_io
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), optional, allocatable :: E(:)
Calls
Called by
Contents
Source Code
setup_energy_scale
Source Code
  subroutine setup_energy_scale(E)
    !===============================================================================
    ! Sets up all broadening independent DOS concerns
    ! Calls the relevant dos calculator.
    !===============================================================================
    use od_dos_utils, only: dos_utils_calculate
    use od_parameters, only: jdos_max_energy, jdos_spacing, iprint
    use od_electronic, only: efermi, band_energy
    use od_comms, only: comms_reduce, comms_bcast, on_root
    use od_io, only: stdout, io_error
    implicit none
    integer       :: idos, ierr
    real(kind=dp) :: max_band_energy
    real(kind=dp), intent(out), allocatable, optional    :: E(:)
    if (jdos_max_energy < 0.0_dp) then ! we have to work it out ourselves
      max_band_energy = maxval(band_energy)
      call comms_reduce(max_band_energy, 1, 'MAX')
      call comms_bcast(max_band_energy, 1)
      jdos_max_energy = efermi - max_band_energy
      if (on_root .and. (iprint > 2)) then
        write (stdout, *)
        write (stdout, '(1x,a78)') &
             & '+----------------------------------------------------------------------------+'
        write (stdout, '(1x,a1,a38,f11.3,13x,a15)') &
             & '|', 'max_band_energy (before correction) : ',&
             & max_band_energy, "<-- JDOS Grid |"
      end if
    end if
    jdos_nbins = abs(ceiling(jdos_max_energy/jdos_spacing))
    jdos_max_energy = jdos_nbins*jdos_spacing
    allocate (E(1:jdos_nbins), stat=ierr)
    if (ierr /= 0) call io_error("Error: jdos_utils, setup_energy_scale: cannot allocate E")
    delta_bins = jdos_max_energy/real(jdos_nbins - 1, dp)
    do idos = 1, jdos_nbins
      E(idos) = real(idos - 1, dp)*delta_bins
    end do
    if (on_root .and. (iprint > 2)) then
      write (stdout, '(1x,a1,a38,f11.3,13x,a15)') '|', 'efermi : ', efermi, "<-- JDOS Grid |"
      write (stdout, '(1x,a1,a38,f11.3,13x,a15)') '|', 'jdos_max_energy : ', jdos_max_energy, "<-- JDOS Grid |"
      write (stdout, '(1x,a1,a38,i11,13x,a15)') '|', ' jdos_nbins : ', jdos_nbins, "<-- JDOS Grid |"
      write (stdout, '(1x,a1,a38,f11.3,13x,a15)') '|', 'jdos_spacing : ', jdos_spacing, "<-- JDOS Grid |"
      write (stdout, '(1x,a1,a38,f11.3,13x,a15)') '|', 'delta_bins : ', delta_bins, "<-- JDOS Grid |"
      write (stdout, '(1x,a78)') &
        '+----------------------------------------------------------------------------+'
    end if
  end subroutine setup_energy_scale
Call graph
setup_energy_scale calls comms_reduce, comms_bcast, io_error
jdos_utils_calculate calls setup_energy_scale
jdos_calculate calls jdos_utils_calculate
optics_calculate calls jdos_utils_calculate
optados calls jdos_calculate, optics_calculate