utility_frac_to_cart – OptaDOS
utility_frac_to_cart Subroutine
11 statements
Source File
public subroutine utility_frac_to_cart(frac, cart, real_lat)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: frac(3)
real(kind=dp), intent(out) :: cart(3)
real(kind=dp), intent(in) :: real_lat(3,3)
Called by
Contents
Source Code
utility_frac_to_cart
Source Code
  subroutine utility_frac_to_cart(frac, cart, real_lat)
    !==================================================================!
    !                                                                  !
    !  Convert from fractional to Cartesian coordinates                !
    !                                                                  !
    !===================================================================
    implicit none
    real(kind=dp), intent(in)  :: real_lat(3, 3)
    real(kind=dp), intent(in)  :: frac(3)
    real(kind=dp), intent(out) :: cart(3)
    integer :: i
    do i = 1, 3
      cart(i) = real_lat(1, i)*frac(1) + real_lat(2, i)*frac(2) + real_lat(3, i)*frac(3)
    end do
    return
  end subroutine utility_frac_to_cart
Call graph
cell_read_cell calls utility_frac_to_cart
cell_get_atoms calls utility_frac_to_cart
param_read calls cell_read_cell
optados calls param_read