write_epsilon – OptaDOS
write_epsilon Subroutine
129 statements
Source File
public subroutine write_epsilon(atom, photo_at_e, photo_volume)
Uses
od_jdos_utils
od_parameters
od_cell
od_electronic
od_io
This subroutine writes out the dielectric function
$ label%name="epsilon"//trim(achar(N2)) $ if(trim(output_format)=="xmgrace") then $ call write_optics_xmgrace(label,E,epsilon(:,1,N2,1),epsilon(:,2,N2,1)) $ elseif(trim(output_format)=="gnuplot") then $ write(stdout,) " WARNING: GNUPLOT output not yet available, continuing..." $ else $ write(stdout,) " WARNING: Unknown output format requested, continuing..." $ endif
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: atom
real(kind=dp), intent(in), optional, dimension(:, :) :: photo_at_e
real(kind=dp), intent(in), optional :: photo_volume
Calls
Called by
Contents
Source Code
write_epsilon
Source Code
  subroutine write_epsilon(atom, photo_at_e, photo_volume)
    !***************************************************************
    ! This subroutine writes out the dielectric function
    use od_cell, only: nkpoints, cell_volume
    use od_parameters, only: optics_geom, optics_qdir, jdos_max_energy, scissor_op, &
         &output_format, fixed, adaptive, linear, optics_intraband
    use od_electronic, only: nbands, num_electrons, nspins
    use od_jdos_utils, only: E, jdos_nbins
    use od_io, only: seedname, io_file_unit, stdout
    integer :: N, N2, N3
    real(kind=dp) ::dE
    integer :: epsilon_unit
    integer, intent(in), optional :: atom
    real(kind=dp), intent(in), dimension(:, :), optional :: photo_at_e
    real(kind=dp), intent(in), optional                  :: photo_volume
    character(len=3) :: atom_char
    type(graph_labels) :: label
    if (atom .gt. 0) then
      write (atom_char, '(I3)') atom
      label%name = "epsilon_atom_"//trim(adjustl(atom_char))
    else
      label%name = "epsilon"
    end if
    label%title = "Dielectric Function" ! Dimensionless
    label%x_label = "Energy (eV)"
    label%y_label = ""
    label%legend_a = "Real"
    label%legend_b = "Imaginary"
    dE = E(2) - E(1)
    ! Open the output file
    epsilon_unit = io_file_unit()
    if (atom .gt. 0) then
      write (atom_char, '(I3)') atom
      open (unit=epsilon_unit, action='write', file=trim(seedname)//'_epsilon_atom_'//trim(adjustl(atom_char))//'.dat')
    else
      open (unit=epsilon_unit, action='write', file=trim(seedname)//'_epsilon.dat')
    end if
    ! Write into the output file
    write (epsilon_unit, *) '#*********************************************'
    write (epsilon_unit, *) '#            Dielectric function                 '
    write (epsilon_unit, *) '#*********************************************'
    write (epsilon_unit, *) '#'
    write (epsilon_unit, *) '# Number of k-points: ', nkpoints
    if (nspins == 1) then
      write (epsilon_unit, *) '# Number of electrons:', num_electrons(1)
    else
      write (epsilon_unit, *) '# Number of electrons:', num_electrons(1), num_electrons(2)
    end if
    write (epsilon_unit, *) '# Number of bands:', nbands
    if (present(photo_volume)) then
      write (epsilon_unit, *) '# Volume calculated for optics and photoemission (Ang^3):', photo_volume
    else
      write (epsilon_unit, *) '# Volume of the unit cell (Ang^3):', cell_volume
    end if
    write (epsilon_unit, *) '#'
    write (epsilon_unit, '(1x,a,f10.6,1x,a,f10.6,1x,a)') &
         & '# Dielectric function calculated to', jdos_max_energy, 'eV in', dE, 'eV steps'
    write (epsilon_unit, *) '#'
    write (epsilon_unit, *) '# optics_geom:  ', optics_geom
    if (index(optics_geom, 'polar') > 0) then
      write (epsilon_unit, '(1x,a,f10.3,f10.3,f10.3)') '# q-vector', &
           & optics_qdir(1), optics_qdir(2), optics_qdir(3)
      write (epsilon_unit, *) '# q_weight:', q_weight
    end if
    if (scissor_op > 0) then
      write (epsilon_unit, '(1x,a,f10.3,f10.3,f10.3)') '# Scissor operator:', scissor_op
    end if
    write (epsilon_unit, *) '#'
    if (optics_intraband) then
      write (epsilon_unit, *) '# Calculation includes intraband term'
      if (present(photo_at_e)) then
        if (fixed) write (epsilon_unit, *) '# DOS at Ef:', photo_at_e(1, :)
        if (adaptive) write (epsilon_unit, *) '# DOS at Ef:', photo_at_e(2, :)
        if (linear) write (epsilon_unit, *) '# DOS at Ef:', photo_at_e(3, :)
      else
        if (fixed) write (epsilon_unit, *) '# DOS at Ef:', dos_at_e(1, :)
        if (adaptive) write (epsilon_unit, *) '# DOS at Ef:', dos_at_e(2, :)
        if (linear) write (epsilon_unit, *) '# DOS at Ef:', dos_at_e(3, :)
      end if
      do N = 1, N_geom
        write (epsilon_unit, *) '# Plasmon energy:', (intra(N)**0.5)
      end do
    end if
    if (N_geom == 1) then
      write (epsilon_unit, *) '# Result of sum rule: Neff(E) =  ', N_eff
      write (epsilon_unit, *) '#'
      if (.not. optics_intraband) then
        do N = 1, jdos_nbins
          write (epsilon_unit, *) E(N), ',', epsilon(N, 1, 1, 1), ',', epsilon(N, 2, 1, 1)
        end do
      else
        write (epsilon_unit, *) ''
        write (epsilon_unit, *) ''
        do N = 1, jdos_nbins
          write (epsilon_unit, *) E(N), ',', epsilon(N, 1, 1, 1), ',', epsilon(N, 2, 1, 1)
        end do
        do N2 = 2, 3
          write (epsilon_unit, *) ''
          write (epsilon_unit, *) ''
          do N = 2, jdos_nbins
            write (epsilon_unit, *) E(N), ',', epsilon(N, 1, 1, N2), ',', epsilon(N, 2, 1, N2)/(E(N)*e_charge)
          end do
        end do
      end if
      if (trim(output_format) == "xmgrace") then
        call write_optics_xmgrace(label, E, epsilon(:, 1, 1, 1), epsilon(:, 2, 1, 1))
      elseif (trim(output_format) == "gnuplot") then
        call write_optics_gnuplot(label, E, epsilon(:, 1, 1, 1), epsilon(:, 2, 1, 1))
      else
        write (stdout, *) " WARNING: Unknown output format requested, continuing..."
      end if
    end if
    if (index(optics_geom, 'tensor') > 0) then
      write (epsilon_unit, *) ''
      write (epsilon_unit, *) ''
      do N2 = 1, N_geom
        write (epsilon_unit, *) '# Component ', N2
        write (epsilon_unit, *) ''
        write (epsilon_unit, *) ''
        if (.not. optics_intraband) then
          do N = 1, jdos_nbins
            write (epsilon_unit, *) E(N), epsilon(N, 1, N2, 1), epsilon(N, 2, N2, 1)
          end do
        else
          do N3 = 1, 3
            do N = 1, jdos_nbins
              write (epsilon_unit, *) E(N), epsilon(N, 1, N2, N3), epsilon(N, 2, N2, N3)
            end do
            write (epsilon_unit, *) ''
            write (epsilon_unit, *) ''
          end do
        end if
        ! I don't think we want to plot in the tensor case, so this is commented out (it's broke anyhow!) jry
!!$          label%name="epsilon"//trim(achar(N2))
!!$          if(trim(output_format)=="xmgrace") then
!!$             call write_optics_xmgrace(label,E,epsilon(:,1,N2,1),epsilon(:,2,N2,1))
!!$          elseif(trim(output_format)=="gnuplot") then
!!$             write(stdout,*)  " WARNING: GNUPLOT output not yet available, continuing..."
!!$          else
!!$             write(stdout,*)  " WARNING: Unknown output format requested, continuing..."
!!$          endif
      end do
    end if
    ! Close output file
    close (unit=epsilon_unit)
  end subroutine write_epsilon
Call graph
write_epsilon calls io_file_unit
optics_calculate calls write_epsilon
optados calls optics_calculate