write_loss_fn – OptaDOS
write_loss_fn Subroutine
109 statements
Source File
public subroutine write_loss_fn()
Uses
od_jdos_utils
od_parameters
od_cell
od_electronic
od_io
This subroutine writes out the loss function
Arguments
None
Calls
Called by
Contents
Source Code
write_loss_fn
Source Code
  subroutine write_loss_fn
    !***************************************************************
    ! This subroutine writes out the loss function
    use od_cell, only: nkpoints, cell_volume
    use od_parameters, only: optics_geom, optics_qdir, jdos_max_energy, scissor_op, output_format, &
      optics_intraband, optics_lossfn_broadening
    use od_electronic, only: nbands, num_electrons, nspins
    use od_jdos_utils, only: jdos_nbins, E
    use od_io, only: seedname, io_file_unit, stdout
    integer :: N, N2
    integer :: loss_fn_unit
    type(graph_labels) :: label
    label%name = "loss_fn"
    label%title = "Loss Function"  ! Dimensionless
    label%x_label = "Energy (eV)"
    label%y_label = ""
    if (.not. optics_intraband) then
      if (optics_lossfn_broadening) then
        label%legend_a = ""
        label%legend_b = "Broadened"
      else
        label%legend_a = ""
      end if
    else
      if (optics_lossfn_broadening) then
        label%legend_a = "Interband"
        label%legend_b = "Intraband"
        label%legend_c = "Total"
        label%legend_d = "Broadened"
      else
        label%legend_a = "Interband"
        label%legend_b = "Intraband"
        label%legend_c = "Total"
      end if
    end if
    ! Open the output file
    loss_fn_unit = io_file_unit()
    open (unit=loss_fn_unit, action='write', file=trim(seedname)//'_loss_fn.dat')
    ! Write into the output file
    write (loss_fn_unit, *) '#*********************************************'
    write (loss_fn_unit, *) '#               Loss function                 '
    write (loss_fn_unit, *) '#*********************************************'
    write (loss_fn_unit, *) '#'
    write (loss_fn_unit, *) '# Number of k-points: ', nkpoints
    if (nspins == 1) then
      write (loss_fn_unit, *) '# Number of electrons:', num_electrons(1)
    else
      write (loss_fn_unit, *) '# Number of electrons:', num_electrons(1), num_electrons(2)
    end if
    write (loss_fn_unit, *) '# No of bands:', nbands
    write (loss_fn_unit, *) '# Volume of the unit cell (Ang^3):', cell_volume
    write (loss_fn_unit, *) '#'
    write (loss_fn_unit, *) '# optics_geom:  ', optics_geom
    if (index(optics_geom, 'polar') > 0) then
      write (loss_fn_unit, '(1x,a,f10.3,f10.3,f10.3)') '# q-vector', optics_qdir(1), optics_qdir(2), optics_qdir(3)
      write (loss_fn_unit, *) '# q_weight:', q_weight
    end if
    if (scissor_op > 0) then
      write (loss_fn_unit, '(1x,a,f10.3,f10.3,f10.3)') '# Scissor operator:', scissor_op
    end if
    write (loss_fn_unit, *) '#'
    write (loss_fn_unit, *) '# Result of first sum rule: Neff(E) = ', N_eff2
    write (loss_fn_unit, *) '# Result of second sum rule (pi/2 = 1.570796327):', N_eff3
    write (loss_fn_unit, *) '#'
    if (.not. optics_intraband) then
      if (optics_lossfn_broadening) then
        do N = 1, jdos_nbins
          write (loss_fn_unit, *) E(N), loss_fn(N, 1), loss_fn(N, 2)
        end do
      else
        do N = 1, jdos_nbins
          write (loss_fn_unit, *) E(N), loss_fn(N, 1)
        end do
      end if
    else
      if (optics_lossfn_broadening) then
        do N2 = 1, 4
          do N = 1, jdos_nbins
            write (loss_fn_unit, *) E(N), loss_fn(N, N2)
          end do
        end do
      else
        do N2 = 1, 3
          do N = 1, jdos_nbins
            write (loss_fn_unit, *) E(N), loss_fn(N, N2)
          end do
        end do
      end if
    end if
    ! Close output file
    close (unit=loss_fn_unit)
    if (trim(output_format) == "xmgrace") then
      if (.not. optics_intraband) then
        if (optics_lossfn_broadening) then
          call write_optics_xmgrace(label, E, loss_fn(:, 1), loss_fn(:, 2))
        else
          call write_optics_xmgrace(label, E, loss_fn(:, 1))
        end if
      else
        if (optics_lossfn_broadening) then
          call write_optics_xmgrace(label, E, loss_fn(:, 1), loss_fn(:, 2), loss_fn(:, 3), loss_fn(:, 4))
        else
          call write_optics_xmgrace(label, E, loss_fn(:, 1), loss_fn(:, 2), loss_fn(:, 3))
        end if
      end if
    elseif (trim(output_format) == "gnuplot") then
      if (.not. optics_intraband) then
        call write_optics_gnuplot(label, E, loss_fn(:, 1))
      else
        call write_optics_gnuplot(label, E, loss_fn(:, 1), loss_fn(:, 2), loss_fn(:, 3))
      end if
    else
      write (stdout, *) " WARNING: Unknown output format requested, continuing..."
    end if
  end subroutine write_loss_fn
Call graph
write_loss_fn calls io_file_unit
optics_calculate calls write_loss_fn
optados calls optics_calculate