write_jdos – OptaDOS
write_jdos Subroutine
61 statements
Source File
public subroutine write_jdos(E, dos, dos_name)
Uses
od_electronic
od_jdos_utils
od_io
od_parameters
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: E(jdos_nbins)
real(kind=dp), intent(in) :: dos(jdos_nbins,nspins)
character(len=*), intent(in) :: dos_name
Calls
Called by
Contents
Source Code
write_jdos
Source Code
  subroutine write_jdos(E, dos, dos_name)
    use od_parameters, only: dos_per_volume, output_format
    use od_jdos_utils, only: jdos_nbins
    use od_electronic, only: nspins
    use od_io, only: io_file_unit, seedname, stdout, io_error, io_date
    !===============================================================================
    ! This routine receives an energy scale, a density of states and a file name
    ! and writes out the DOS to disk
    !===============================================================================
    implicit none
    real(kind=dp), intent(in) :: E(jdos_nbins)
    real(kind=dp), intent(in) :: dos(jdos_nbins, nspins)
    character(len=*), intent(in) :: dos_name
    integer :: i, dos_file, ierr
    character(len=11) :: cdate
    character(len=9) :: ctime
    character(len=22) :: dos_units, intdos_units
    dos_file = io_file_unit()
    open (unit=dos_file, file=trim(seedname)//'.j'//trim(dos_name)//'.dat', iostat=ierr)
    if (ierr .ne. 0) call io_error(" ERROR: Cannot open output file in dos: write_dos")
    dos_units = "(electrons per eV)"; intdos_units = "(electrons)"
    if (dos_per_volume) then
      dos_units = "(electrons per eV/A^3)"
      intdos_units = "(electrons per A^3)"
    end if
    write (dos_file, *) "##############################################################################"
    write (dos_file, *) "#"
    write (dos_file, *) "#                  O p t a D O S   o u t p u t   f i l e "
    write (dos_file, '(1x,a1)') "#"
    write (dos_file, *) "#    Density of States using ", trim(dos_name), " broadening"
    call io_date(cdate, ctime)
    write (dos_file, *) '#  Generated on ', cdate, ' at ', ctime
    write (dos_file, *) "# Column        Data"
    write (dos_file, *) "#    1        Energy (eV)"
    if (nspins > 1) then
      write (dos_file, *) "#    2        Up-spin DOS ", trim(dos_units)
      write (dos_file, *) "#    3        Down-spin DOS ", trim(dos_units)
      write (dos_file, *) "#    4        Up-spin Integrated DOS ", trim(intdos_units)
      write (dos_file, *) "#    5        Down-spin Integrated DOS ", trim(intdos_units)
    else
      write (dos_file, *) "#    2        DOS ", trim(dos_units)
      write (dos_file, *) "#    3        Integrated DOS ", trim(intdos_units)
    end if
    write (dos_file, '(1x,a1)') "#"
    write (dos_file, '(1x,a78)') "##############################################################################"
    if (nspins > 1) then
      do i = 1, jdos_nbins
        write (dos_file, '(3(E21.13,2x))') E(i), dos(i, 1), -dos(i, 2)
      end do
    else
      do i = 1, jdos_nbins
        write (dos_file, '(2(E21.13,2x))') E(i), dos(i, 1)
      end do
    end if
    close (dos_file)
    if (trim(output_format) == "xmgrace") then
      call write_jdos_xmgrace(dos_name, E, dos)
    elseif (trim(output_format) == "gnuplot") then
      write (stdout, *) " WARNING: GNUPLOT output not yet available, calling xmgrace"
      call write_jdos_xmgrace(dos_name, E, dos)
      !     call write_dos_gnuplot(dos_name,E,dos)
    else
      write (stdout, *) " WARNING: Unknown output format requested, continuing..."
    end if
  end subroutine write_jdos
Call graph
write_jdos calls io_file_unit, io_date, io_error, write_jdos_xmgrace
write_jdos_xmgrace calls io_file_unit, io_error, xmgu_legend, xmgu_subtitle, xmgu_title, xmgu_axis, xmgu_setup, xmgu_data_header, xmgu_data
xmgu_setup calls io_date
xmgu_data calls io_error
jdos_calculate calls write_jdos
optados calls jdos_calculate