write_jdos_xmgrace – OptaDOS
write_jdos_xmgrace Subroutine
38 statements
Source File
public subroutine write_jdos_xmgrace(dos_name, E, dos)
Uses
od_electronic
od_jdos_utils
od_io
xmgrace_utils
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: dos_name
real(kind=dp), intent(in) :: E(jdos_nbins)
real(kind=dp), intent(in) :: dos(jdos_nbins,nspins)
Calls
Called by
Contents
Source Code
write_jdos_xmgrace
Source Code
  subroutine write_jdos_xmgrace(dos_name, E, dos)
    !===============================================================================
    use xmgrace_utils
    use od_jdos_utils, only: jdos_nbins
    use od_electronic, only: nspins
    use od_io, only: io_file_unit, io_error, seedname
    implicit none
    real(kind=dp), intent(in) :: E(jdos_nbins)
    real(kind=dp), intent(in) :: dos(jdos_nbins, nspins)
    real(kind=dp) :: min_x, max_x, min_y, max_y
    integer :: batch_file, ierr
    character(len=*), intent(in) :: dos_name
    batch_file = io_file_unit()
    open (unit=batch_file, file=trim(seedname)//'.j'//trim(dos_name)//'.agr', iostat=ierr)
    if (ierr .ne. 0) call io_error(" ERROR: Cannot open xmgrace batch file in dos: write_jdos_xmgrace")
    min_x = minval(E)
    max_x = maxval(E)
    min_y = 0
    max_y = maxval(dos)
    if (nspins > 1) then
      min_y = -max_y
    end if
    call xmgu_setup(batch_file)
    call xmgu_legend(batch_file)
    call xmgu_title(batch_file, min_x, max_x, min_y, max_y, "Joint Electronic Density of States")
    call xmgu_subtitle(batch_file, "Generated by OptaDOS")
    call xmgu_axis(batch_file, "x", "Energy eV")
    call xmgu_axis(batch_file, "y", "JDOS")
    if (nspins > 1) then
      call xmgu_data_header(batch_file, 0, 1, "up-spin channel")
      call xmgu_data_header(batch_file, 1, 2, "down-spin channel")
      call xmgu_data(batch_file, 0, E(:), dos(:, 1))
      call xmgu_data(batch_file, 1, E(:), -dos(:, 2))
    else
      call xmgu_data_header(batch_file, 0, 1, "Total JDOS")
      call xmgu_data(batch_file, 0, E(:), dos(:, 1))
    end if
    close (batch_file)
  end subroutine write_jdos_xmgrace
Call graph
write_jdos_xmgrace calls io_file_unit, xmgu_legend, io_error, xmgu_title, xmgu_setup, xmgu_subtitle, xmgu_axis, xmgu_data_header, xmgu_data
xmgu_setup calls io_date
xmgu_data calls io_error
write_jdos calls write_jdos_xmgrace
jdos_calculate calls write_jdos
optados calls jdos_calculate