write_elnes_fmt – OptaDOS
write_elnes_fmt Subroutine
33 statements
Source File
public subroutine write_elnes_fmt()
Uses
od_electronic
od_io
od_cell
Soubroute to write a formatted elnes file.
Arguments
None
Calls
Called by
Contents
Source Code
write_elnes_fmt
Source Code
  subroutine write_elnes_fmt()
    !! Soubroute to write a formatted elnes file.
    use od_electronic, only: elnes_mwab, elnes_orbital, elnes_mat, &
         & elec_elnes_find_channel_numbers
    use od_cell, only: num_kpoints_on_node
    use od_io, only: io_file_unit
    implicit none
    real(dp) :: file_version = 1.0_dp
    !! The file verioson format to write. Currently we're on version 1.
    integer :: elnes_unit
    !! File unit number to write to.
    integer :: ik, is, iorb, ib, indx
    !! Loop variables.
    character(len=80) :: string, string2
    !! Tempory string manipulation variables.
    write (stdout, *) " Write a formatted elnes file."
    ! CASTEP (hence the bin file) and OptaDOS think about am_channel numbers
    ! differently. To keep consistent we convert to CASTEP's numbering scheme
    ! before we write out.
    call elec_elnes_find_channel_numbers()
    elnes_unit = io_file_unit()
    open (unit=elnes_unit, file=trim(outseedname)//".elnes_fmt", form='formatted')
    write (elnes_unit, '('//trim(format_precision)//')') file_version
    write (elnes_unit, '(a80)') adjustl(elnesfile_header)
    write (elnes_unit, '(a20,1x,i5)') "Norbitals", elnes_mwab%norbitals
    write (elnes_unit, '(a20,1x,i5)') "Nbands", elnes_mwab%nbands
    write (elnes_unit, '(a20,1x,i5)') "Nkpoints", elnes_mwab%nkpoints
    write (elnes_unit, '(a20,1x,i5)') "Nspins", elnes_mwab%nspins
    write (string, '(i7,"(1x,",a,")")') elnes_mwab%norbitals, "i5"
    write (string2, '(i7,"(1x,",a,")")') elnes_mwab%norbitals*elnes_mwab%nbands*3, trim(format_precision)
    write (elnes_unit, '(a10,'//trim(string)//')') "Species_no", elnes_orbital%species_no(1:elnes_mwab%norbitals)
    write (elnes_unit, '(a10,'//trim(string)//')') "Rank", elnes_orbital%rank_in_species(1:elnes_mwab%norbitals)
    write (elnes_unit, '(a10,'//trim(string)//')') "Shell", elnes_orbital%shell(1:elnes_mwab%norbitals)
    write (elnes_unit, '(a10,'//trim(string)//')') "Am_channel", elnes_orbital%am_channel(1:elnes_mwab%norbitals)
    do ik = 1, num_kpoints_on_node(0)
      do is = 1, elnes_mwab%nspins
        write (elnes_unit, '('//trim(string2)//')') (((elnes_mat(iorb, ib, indx, ik, is), iorb=1, elnes_mwab%norbitals), &
                                                      ib=1, elnes_mwab%nbands), indx=1, 3)
      end do
    end do
    close (elnes_unit)
    write (stdout, *) " Sucesfully written a formatted elnes file --> "//trim(outseedname)//".elnes_fmt"
  end subroutine write_elnes_fmt
Call graph
write_elnes_fmt calls elec_elnes_find_channel_numbers, io_file_unit
elec_elnes_find_channel_numbers calls selectcase, io_error
od2od calls write_elnes_fmt