write_refract – OptaDOS
write_refract Subroutine
70 statements
Source File
public subroutine write_refract(atom, photo_volume)
Uses
od_jdos_utils
od_parameters
od_cell
od_electronic
od_io
This subroutine writes out the refractive index
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: atom
real(kind=dp), intent(in), optional :: photo_volume
Calls
Called by
Contents
Source Code
write_refract
Source Code
  subroutine write_refract(atom, photo_volume)
    !***************************************************************
    ! This subroutine writes out the refractive index
    use od_cell, only: nkpoints, cell_volume
    use od_parameters, only: optics_geom, optics_qdir, jdos_max_energy, scissor_op, output_format
    use od_electronic, only: nbands, num_electrons, nspins
    use od_jdos_utils, only: jdos_nbins, E
    use od_io, only: seedname, io_file_unit, stdout
    integer :: N
    integer :: refract_unit
    integer, intent(in), optional :: atom
    real(kind=dp), intent(in), optional :: photo_volume
    character(len=3) :: atom_char
    type(graph_labels) :: label
    if (atom .gt. 0) then
      write (atom_char, '(I3)') atom
      label%name = "refractive_index_atom_"//trim(adjustl(atom_char))
    else
      label%name = "refractive_index"
    end if
    label%title = "Refractive Index"  ! Dimensionless
    label%x_label = "Energy (eV)"
    label%y_label = ""
    label%legend_a = "Real"
    label%legend_b = "Imaginary"
    ! Open the output file
    refract_unit = io_file_unit()
    if (atom .gt. 0) then
      write (atom_char, '(I3)') atom
      open (unit=refract_unit, action='write', file=trim(seedname)//'_refractive_index_atom_'//trim(adjustl(atom_char))//'.dat')
    else
      open (unit=refract_unit, action='write', file=trim(seedname)//'_refractive_index.dat')
    end if
    ! Write into the output file
    write (refract_unit, *) '#*********************************************'
    write (refract_unit, *) '#             Refractive index                 '
    write (refract_unit, *) '#*********************************************'
    write (refract_unit, *) '#'
    write (refract_unit, *) '# N=n+ik'
    write (refract_unit, *) '#'
    write (refract_unit, *) '# Number of k-points: ', nkpoints
    if (nspins == 1) then
      write (refract_unit, *) '# Number of electrons:', num_electrons(1)
    else
      write (refract_unit, *) '# Number of electrons:', num_electrons(1), num_electrons(2)
    end if
    write (refract_unit, *) '# No of bands:', nbands
    if (present(photo_volume)) then
      write (refract_unit, *) '# Volume calculated for optics and photoemission (Ang^3):', photo_volume
    else
      write (refract_unit, *) '# Volume of the unit cell (Ang^3):', cell_volume
    end if
    write (refract_unit, *) '#'
    write (refract_unit, *) '# optics_geom:  ', optics_geom
    if (index(optics_geom, 'polar') > 0) then
      write (refract_unit, '(1x,a,f10.3,f10.3,f10.3)') '# q-vector', optics_qdir(1), optics_qdir(2), optics_qdir(3)
      write (refract_unit, *) '# q_weight:', q_weight
    end if
    if (scissor_op > 0) then
      write (refract_unit, '(1x,a,f10.3,f10.3,f10.3)') '# Scissor operator:', scissor_op
    end if
    write (refract_unit, *) '#'
    do N = 1, jdos_nbins
      write (refract_unit, *) E(N), ',', refract(N, 1), ',', refract(N, 2)
    end do
    ! Close output file
    close (unit=refract_unit)
    if (trim(output_format) == "xmgrace") then
      call write_optics_xmgrace(label, E, refract(:, 1), refract(:, 2))
    elseif (trim(output_format) == "gnuplot") then
      call write_optics_gnuplot(label, E, refract(:, 1), refract(:, 2))
    else
      write (stdout, *) " WARNING: Unknown output format requested, continuing..."
    end if
  end subroutine write_refract
Call graph
write_refract calls io_file_unit
optics_calculate calls write_refract
optados calls optics_calculate