write_reflect – OptaDOS
write_reflect Subroutine
69 statements
Source File
public subroutine write_reflect(atom, photo_volume)
Uses
od_jdos_utils
od_parameters
od_cell
od_electronic
od_io
This subroutine writes out the reflection coefficient
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: atom
real(kind=dp), intent(in), optional :: photo_volume
Calls
Called by
Contents
Source Code
write_reflect
Source Code
  subroutine write_reflect(atom, photo_volume)
    !***************************************************************
    ! This subroutine writes out the reflection coefficient
    use od_cell, only: nkpoints, cell_volume
    use od_parameters, only: optics_geom, optics_qdir, jdos_max_energy, scissor_op, output_format
    use od_electronic, only: nbands, num_electrons, nspins
    use od_io, only: seedname, io_file_unit, stdout
    use od_jdos_utils, only: jdos_nbins, E
    integer :: N
    integer :: reflect_unit
    integer, intent(in), optional :: atom
    real(kind=dp), intent(in), optional :: photo_volume
    character(len=3) :: atom_char
    type(graph_labels) :: label
    if (atom .gt. 0) then
      write (atom_char, '(I3)') atom
      label%name = "reflection_atom_"//trim(adjustl(atom_char))
    else
      label%name = "reflection"
    end if
    label%title = "Reflection Coefficient"  ! Dimensionless
    label%x_label = "Energy (eV)"
    label%y_label = ""
    label%legend_a = "R"
    ! Open the output file
    reflect_unit = io_file_unit()
    if (atom .gt. 0) then
      write (atom_char, '(I3)') atom
      open (unit=reflect_unit, action='write', file=trim(seedname)//'_reflection_atom_'//trim(adjustl(atom_char))//'.dat')
    else
      open (unit=reflect_unit, action='write', file=trim(seedname)//'_reflection.dat')
    end if
    ! Write into the output file
    write (reflect_unit, *) '#*********************************************'
    write (reflect_unit, *) '#           Reflection coefficient                '
    write (reflect_unit, *) '#*********************************************'
    write (reflect_unit, *) '#'
    write (reflect_unit, *) '# N=n+ik'
    write (reflect_unit, *) '#'
    write (reflect_unit, *) '# Number of k-points: ', nkpoints
    if (nspins == 1) then
      write (reflect_unit, *) '# Number of electrons:', num_electrons(1)
    else
      write (reflect_unit, *) '# Number of electrons:', num_electrons(1), num_electrons(2)
    end if
    write (reflect_unit, *) '# No of bands:', nbands
    if (present(photo_volume)) then
      write (reflect_unit, *) '# Volume calculated for optics and photoemission (Ang^3):', photo_volume
    else
      write (reflect_unit, *) '# Volume of the unit cell (Ang^3):', cell_volume
    end if
    write (reflect_unit, *) '#'
    write (reflect_unit, *) '# optics_geom:  ', optics_geom
    if (index(optics_geom, 'polar') > 0) then
      write (reflect_unit, '(1x,a,f10.3,f10.3,f10.3)') '# q-vector', optics_qdir(1), optics_qdir(2), optics_qdir(3)
      write (reflect_unit, *) '# q_weight:', q_weight
    end if
    if (scissor_op > 0) then
      write (reflect_unit, '(1x,a,f10.3,f10.3,f10.3)') '# Scissor operator:', scissor_op
    end if
    write (reflect_unit, *) '#'
    do N = 1, jdos_nbins
      write (reflect_unit, *) E(N), ',', reflect(N)
    end do
    ! Close output file
    close (unit=reflect_unit)
    if (trim(output_format) == "xmgrace") then
      call write_optics_xmgrace(label, E, reflect)
    elseif (trim(output_format) == "gnuplot") then
      call write_optics_gnuplot(label, E, reflect)
    else
      write (stdout, *) " WARNING: Unknown output format requested, continuing..."
    end if
  end subroutine write_reflect
Call graph
write_reflect calls io_file_unit
optics_calculate calls write_reflect
optados calls optics_calculate