write_conduct – OptaDOS
write_conduct Subroutine
54 statements
Source File
public subroutine write_conduct()
Uses
od_jdos_utils
od_parameters
od_cell
od_electronic
od_io
This subroutine writes out the conductivity
Arguments
None
Calls
Called by
Contents
Source Code
write_conduct
Source Code
  subroutine write_conduct
    !***************************************************************
    ! This subroutine writes out the conductivity
    use od_cell, only: nkpoints, cell_volume
    use od_parameters, only: optics_geom, optics_qdir, jdos_max_energy, scissor_op, output_format
    use od_electronic, only: nbands, num_electrons, nspins
    use od_jdos_utils, only: jdos_nbins, E
    use od_io, only: seedname, io_file_unit, stdout
    integer :: N
    integer :: conduct_unit
    type(graph_labels) :: label
    label%name = "conductivity"
    label%title = "Conductivity (S m-1)" ! Siemens per metre
    label%x_label = "Energy (eV)"
    label%y_label = ""
    label%legend_a = "Real"
    label%legend_b = "Imaginary"
    ! Open the output file
    conduct_unit = io_file_unit()
    open (unit=conduct_unit, action='write', file=trim(seedname)//'_conductivity.dat')
    ! Write into the output file
    write (conduct_unit, *) '#*********************************************'
    write (conduct_unit, *) '#               Conductivity                '
    write (conduct_unit, *) '#*********************************************'
    write (conduct_unit, *) '#'
    write (conduct_unit, *) '# Number of k-points: ', nkpoints
    if (nspins == 1) then
      write (conduct_unit, *) '# Number of electrons:', num_electrons(1)
    else
      write (conduct_unit, *) '# Number of electrons:', num_electrons(1), num_electrons(2)
    end if
    write (conduct_unit, *) '# No of bands:', nbands
    write (conduct_unit, *) '# Volume of the unit cell (Ang^3):', cell_volume
    write (conduct_unit, *) '#'
    write (conduct_unit, *) '# optics_geom:  ', optics_geom
    if (index(optics_geom, 'polar') > 0) then
      write (conduct_unit, '(1x,a,f10.3,f10.3,f10.3)') '# q-vector', optics_qdir(1), optics_qdir(2), optics_qdir(3)
      write (conduct_unit, *) '# q_weight:', q_weight
    end if
    if (scissor_op > 0) then
      write (conduct_unit, '(1x,a,f10.3,f10.3,f10.3)') '# Scissor operator:', scissor_op
    end if
    write (conduct_unit, *) '# Note: the conductivity is outputted in SI units, Siemens per metre'
    write (conduct_unit, *) '# to convert from SI units (Sm-1) to cgs units (s) divide by 4pixepsilon_0'
    write (conduct_unit, *) '# to convert from cgs (s) units to SI units (Sm-1) multiply by 4pixepsilon_0, '
    write (conduct_unit, *) '#'
    do N = 1, jdos_nbins
      write (conduct_unit, *) E(N), conduct(N, 1), conduct(N, 2)
    end do
    ! Close output file
    close (unit=conduct_unit)
    if (trim(output_format) == "xmgrace") then
      call write_optics_xmgrace(label, E, conduct(:, 1), conduct(:, 2))
    elseif (trim(output_format) == "gnuplot") then
      call write_optics_gnuplot(label, E, conduct(:, 1), conduct(:, 2))
    else
      write (stdout, *) " WARNING: Unknown output format requested, continuing..."
    end if
  end subroutine write_conduct
Call graph
write_conduct calls io_file_unit
optics_calculate calls write_conduct
optados calls optics_calculate