write_dos – OptaDOS
write_dos Subroutine
72 statements
Source File
public subroutine write_dos(E, dos, intdos, dos_name)
Uses
od_electronic
od_io
od_parameters
od_dos_utils
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: E(dos_nbins)
real(kind=dp), intent(in) :: dos(dos_nbins,nspins)
real(kind=dp), intent(in) :: intdos(dos_nbins,nspins)
character(len=*), intent(in) :: dos_name
Calls
Called by
Contents
Source Code
write_dos
Source Code
  subroutine write_dos(E, dos, intdos, dos_name)
    !===============================================================================
    ! This routine receives an energy scale, a density of states and a file name
    ! and writes out the DOS to disk
    !-------------------------------------------------------------------------------
    ! Arguments: E       (in) : The energy scale
    !            dos     (in) : The density of states
    !            intdos  (in) : The integrated DOS
    !            dos_name(in) : Name of the output file
    !-------------------------------------------------------------------------------
    ! Parent Module Varables Used: None
    !-------------------------------------------------------------------------------
    ! Modules Used: See below
    !-------------------------------------------------------------------------------
    ! Key Internal Variables: None
    !-------------------------------------------------------------------------------
    ! Necessary Conditions: None
    !-------------------------------------------------------------------------------
    ! Known Worries: None
    !-------------------------------------------------------------------------------
    ! Written by : A J Morris December 2010
    !===============================================================================
    use od_electronic, only: nspins, efermi, efermi_set
    use od_parameters, only: dos_nbins, dos_per_volume, output_format, set_efermi_zero
    use od_io, only: seedname, io_file_unit, io_date, io_error, stdout
    use od_dos_utils, only: dos_utils_set_efermi
    implicit none
    real(dp), intent(in) :: E(dos_nbins)
    real(dp), intent(in) :: dos(dos_nbins, nspins)
    real(dp), intent(in) :: intdos(dos_nbins, nspins)
    character(len=*), intent(in) :: dos_name
    integer :: i, dos_file, ierr
    character(len=11) :: cdate
    character(len=9) :: ctime
    character(len=22) :: dos_units, intdos_units
    real(kind=dp), allocatable :: E_shift(:)
    allocate (E_shift(dos_nbins), stat=ierr)
    if (ierr /= 0) call io_error('Error allocating E_shift in write_dos')
    if (set_efermi_zero) then
      E_shift = E - efermi
    else
      E_shift = E
    end if
    dos_file = io_file_unit()
    open (unit=dos_file, file=trim(seedname)//'.'//trim(dos_name)//'.dat', iostat=ierr)
    if (ierr .ne. 0) call io_error(" ERROR: Cannot open output file in dos: write_dos")
    dos_units = "(electrons per eV)"; intdos_units = "(electrons)"
    if (dos_per_volume) then
      dos_units = "(electrons per eV/A^3)"
      intdos_units = "(electrons per A^3)"
    end if
    write (dos_file, *) "##############################################################################"
    write (dos_file, *) "#"
    write (dos_file, *) "#                  O p t a D O S   o u t p u t   f i l e "
    write (dos_file, '(1x,a1)') "#"
    write (dos_file, *) "#    Density of States using ", trim(dos_name), " broadening"
    call io_date(cdate, ctime)
    write (dos_file, *) '#  Generated on ', cdate, ' at ', ctime
    write (dos_file, *) "# Column        Data"
    write (dos_file, *) "#    1        Energy (eV)"
    if (nspins > 1) then
      write (dos_file, *) "#    2        Up-spin DOS ", trim(dos_units)
      write (dos_file, *) "#    3        Down-spin DOS ", trim(dos_units)
      write (dos_file, *) "#    4        Up-spin Integrated DOS ", trim(intdos_units)
      write (dos_file, *) "#    5        Down-spin Integrated DOS ", trim(intdos_units)
    else
      write (dos_file, *) "#    2        DOS ", trim(dos_units)
      write (dos_file, *) "#    3        Integrated DOS ", trim(intdos_units)
    end if
    write (dos_file, '(1x,a1)') "#"
    write (dos_file, '(1x,a78)') "##############################################################################"
    if (nspins > 1) then
      do i = 1, dos_nbins
        write (dos_file, '(5(E21.13,2x))') E_shift(i), dos(i, 1), -dos(i, 2), intdos(i, 1), -intdos(i, 2)
      end do
    else
      do i = 1, dos_nbins
        write (dos_file, '(3(E21.13,2x))') E_shift(i), dos(i, 1), intdos(i, 1)
      end do
    end if
    close (dos_file)
    if (trim(output_format) == "xmgrace") then
      call write_dos_xmgrace(dos_name, E_shift, dos)
    elseif (trim(output_format) == "gnuplot") then
      write (stdout, *) " WARNING: GNUPLOT output not yet available, calling xmgrace"
      call write_dos_xmgrace(dos_name, E_shift, dos)
      !     call write_dos_gnuplot(dos_name,E,dos)
    else
      write (stdout, *) " WARNING: Unknown output format requested, continuing..."
    end if
    deallocate (E_shift, stat=ierr)
    if (ierr /= 0) call io_error('Error deallocating E_shift in write_dos')
  end subroutine write_dos
Call graph
write_dos calls io_error, io_date, io_file_unit, write_dos_xmgrace
write_dos_xmgrace calls io_error, io_file_unit, xmgu_legend, xmgu_subtitle, xmgu_title, xmgu_axis, xmgu_setup, xmgu_vertical_line, xmgu_data_header, xmgu_data
xmgu_setup calls io_date
xmgu_data calls io_error
dos_calculate calls write_dos
optados calls dos_calculate