write_dos_xmgrace – OptaDOS
write_dos_xmgrace Subroutine
43 statements
Source File
public subroutine write_dos_xmgrace(dos_name, E, dos)
Uses
od_io
od_electronic
od_parameters
xmgrace_utils
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: dos_name
real(kind=dp), intent(in) :: E(dos_nbins)
real(kind=dp), intent(in) :: dos(dos_nbins,nspins)
Calls
Called by
Contents
Source Code
write_dos_xmgrace
Source Code
  subroutine write_dos_xmgrace(dos_name, E, dos)
    !===============================================================================
    use xmgrace_utils
    use od_parameters, only: dos_nbins, set_efermi_zero
    use od_electronic, only: nspins, efermi, efermi_set
    use od_io, only: io_file_unit, io_error, seedname
    implicit none
    real(dp), intent(in) :: E(dos_nbins)
    real(dp), intent(in) :: dos(dos_nbins, nspins)
    real(dp) :: min_x, max_x, min_y, max_y
    integer :: batch_file, ierr
    character(len=*), intent(in) :: dos_name
    batch_file = io_file_unit()
    open (unit=batch_file, file=trim(seedname)//'.'//trim(dos_name)//'.agr', iostat=ierr)
    if (ierr .ne. 0) call io_error(" ERROR: Cannot open xmgrace batch file in dos: write_dos_xmgrace")
    min_x = minval(E)
    max_x = maxval(E)
    min_y = 0
    max_y = maxval(dos)
    if (nspins > 1) then
      min_y = -max_y
    end if
    call xmgu_setup(batch_file)
    call xmgu_legend(batch_file)
    call xmgu_title(batch_file, min_x, max_x, min_y, max_y, "Electronic Density of States")
    call xmgu_subtitle(batch_file, "Generated by OptaDOS")
    call xmgu_axis(batch_file, "x", "Energy eV")
    call xmgu_axis(batch_file, "y", "eDOS")
    if (set_efermi_zero) then
      call xmgu_vertical_line(batch_file, 0.0_dp, max_y, min_y)
    else
      if (efermi_set) call xmgu_vertical_line(batch_file, efermi, max_y, min_y)
    end if
    if (nspins > 1) then
      call xmgu_data_header(batch_file, 0, 1, "up-spin channel")
      call xmgu_data_header(batch_file, 1, 2, "down-spin channel")
      call xmgu_data(batch_file, 0, E(:), dos(:, 1))
      call xmgu_data(batch_file, 1, E(:), -dos(:, 2))
    else
      call xmgu_data_header(batch_file, 0, 1, "Total DOS")
      call xmgu_data(batch_file, 0, E(:), dos(:, 1))
    end if
    close (batch_file)
  end subroutine write_dos_xmgrace
Call graph
write_dos_xmgrace calls io_file_unit, xmgu_legend, io_error, xmgu_title, xmgu_setup, xmgu_subtitle, xmgu_axis, xmgu_vertical_line, xmgu_data_header, xmgu_data
xmgu_setup calls io_date
xmgu_data calls io_error
write_dos calls write_dos_xmgrace
dos_calculate calls write_dos
optados calls dos_calculate