xmgu_axis – OptaDOS
xmgu_axis Subroutine
43 statements
Source File
public subroutine xmgu_axis(unit, axis, label)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
character, intent(in) :: axis
character, intent(in) :: label
Called by
Contents
Source Code
xmgu_axis
Source Code
  subroutine xmgu_axis(unit, axis, label)
    !==================================================================!
    implicit none
    integer, intent(in)      :: unit
    character(*), intent(in) :: label
    character(*), intent(in)  :: axis
    character(5) :: axis_name
    if (axis == "x") then
      axis_name = "xaxis"
    elseif (axis == "y") then
      axis_name = "yaxis"
    end if
    write (unit, *) '@    '//trim(axis_name)//' on'
    write (unit, *) '@    '//trim(axis_name)//' type zero false'
    write (unit, *) '@    '//trim(axis_name)//' offset 0.000000 , 0.000000'
    write (unit, *) '@    '//trim(axis_name)//' bar on'
    write (unit, *) '@    '//trim(axis_name)//' bar color 1'
    write (unit, *) '@    '//trim(axis_name)//' bar linestyle 1'
    write (unit, *) '@    '//trim(axis_name)//' bar linewidth 2.5'
    write (unit, *) '@    '//trim(axis_name)//' label "'//trim(label)//'"'
    write (unit, *) '@    '//trim(axis_name)//' label layout para'
    write (unit, *) '@    '//trim(axis_name)//' label place auto'
    write (unit, *) '@    '//trim(axis_name)//' label char size 1.000000'
    write (unit, *) '@    '//trim(axis_name)//' label font 4'
    write (unit, *) '@    '//trim(axis_name)//' label color 1'
    write (unit, *) '@    '//trim(axis_name)//' label place normal'
    write (unit, *) '@    '//trim(axis_name)//' tick on'
    write (unit, *) '@ autoticks'
    !  write(unit,*)'@    '//trim(axis_name)//' tick major 10'
    !  write(unit,*)'@    '//trim(axis_name)//' tick minor ticks 1'
    !  write(unit,*)'@    '//trim(axis_name)//' tick default 6'
    write (unit, *) '@    '//trim(axis_name)//' tick place rounded true'
    write (unit, *) '@    '//trim(axis_name)//' tick in'
    write (unit, *) '@    '//trim(axis_name)//' tick major size 1.000000'
    write (unit, *) '@    '//trim(axis_name)//' tick major color 1'
    write (unit, *) '@    '//trim(axis_name)//' tick major linewidth 2.5'
    write (unit, *) '@    '//trim(axis_name)//' tick major linestyle 1'
    write (unit, *) '@    '//trim(axis_name)//' tick major grid off'
    write (unit, *) '@    '//trim(axis_name)//' tick minor color 1'
    write (unit, *) '@    '//trim(axis_name)//' tick minor linewidth 2.5'
    write (unit, *) '@    '//trim(axis_name)//' tick minor linestyle 1'
    write (unit, *) '@    '//trim(axis_name)//' tick minor grid off'
    write (unit, *) '@    '//trim(axis_name)//' tick minor size 0.500000'
    write (unit, *) '@    '//trim(axis_name)//' ticklabel on'
    write (unit, *) '@    '//trim(axis_name)//' ticklabel format general'
    write (unit, *) '@    '//trim(axis_name)//' ticklabel font 4'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel prec 5'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel formula ""'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel append ""'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel prepend ""'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel angle 0'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel skip 0'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel stagger 0'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel place normal'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel offset auto'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel offset 0.000000 , 0.010000'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel start type auto'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel start 0.000000'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel stop type auto'
    ! 1write(unit,*)'@    '//trim(axis_name)//' ticklabel stop 0.000000'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel char size 1.000000'
    ! write(unit,*)'@    '//trim(axis_name)//' ticklabel color 1'
    ! write(unit,*)'@    '//trim(axis_name)//' tick place both'
    ! write(unit,*)'@    '//trim(axis_name)//' tick spec type none'
!    write(unit,*) trim(axis_name)//" type zero true"
!    write(unit,*) trim(axis_name)//" bar on"
!    write(unit,*) trim(axis_name)//" bar color 1"
!    write(unit,*) trim(axis_name)//" bar linestyle 1"
!    write(unit,*) trim(axis_name)//" bar linewidth 2.5"
!    write(unit,*) trim(axis_name)//' label "'//trim(label)//'"'
!    write(unit,*) trim(axis_name)//" label layout para"
!    write(unit,*) trim(axis_name)//" label place auto"
!    write(unit,*) trim(axis_name)//" label char size 1.000000"
!    write(unit,*) trim(axis_name)//" label font 4"
!    write(unit,*) trim(axis_name)//" label color 1"
!    write(unit,*) trim(axis_name)//" label place normal"
!    write(unit,*) trim(axis_name)//" tick on"
!    write(unit,*) trim(axis_name)//" tick major 0.2"
!    write(unit,*) trim(axis_name)//" tick minor ticks 1"
!    write(unit,*) trim(axis_name)//" tick default 6"
!    write(unit,*) trim(axis_name)//" tick place rounded true"
!    write(unit,*) trim(axis_name)//" tick in"
!    write(unit,*) trim(axis_name)//" tick major size 1.000000"
!    write(unit,*) trim(axis_name)//" tick major color 1"
!    write(unit,*) trim(axis_name)//" tick major linewidth 2.5"
!    write(unit,*) trim(axis_name)//" tick major linestyle 1"
!    write(unit,*) trim(axis_name)//" tick major grid off"
!    write(unit,*) trim(axis_name)//" tick minor color 1"
!    write(unit,*) trim(axis_name)//" tick minor linewidth 2.5"
!    write(unit,*) trim(axis_name)//" tick minor linestyle 1"
!    write(unit,*) trim(axis_name)//" tick minor grid off"
!    write(unit,*) trim(axis_name)//" tick minor size 0.500000"
!    write(unit,*) trim(axis_name)//" ticklabel on"
!    write(unit,*) trim(axis_name)//" ticklabel format general"
!    write(unit,*) trim(axis_name)//" ticklabel prec 5"
!    write(unit,*) trim(axis_name)//" ticklabel start type spec"
!    write(unit,*) trim(axis_name)//" ticklabel start 0.200000"
!    write(unit,*) trim(axis_name)//" ticklabel stop type spec"
    !   write(unit,*) trim(axis_name)//" ticklabel stop 0.800000"
!    write(unit,*) trim(axis_name)//" ticklabel font 4"
  end subroutine xmgu_axis
Call graph
write_jdos_xmgrace calls xmgu_axis
write_dos_xmgrace calls xmgu_axis
write_jdos calls write_jdos_xmgrace
write_dos calls write_dos_xmgrace
jdos_calculate calls write_jdos
dos_calculate calls write_dos
optados calls jdos_calculate, dos_calculate