xmgu_data_header – OptaDOS
xmgu_data_header Subroutine
57 statements
Source File
public subroutine xmgu_data_header(unit, field, colour, legend)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
integer, intent(in) :: field
integer, intent(in) :: colour
character, intent(in) :: legend
Called by
Contents
Source Code
xmgu_data_header
Source Code
  subroutine xmgu_data_header(unit, field, colour, legend)
    !==================================================================!
    integer, intent(in)      :: unit
    integer, intent(in)      :: field, colour
    character(4)              :: char_field, char_colour
    character(*), intent(in)  :: legend
    write (char_field, '(I4)') field
    write (char_colour, '(I4)') colour
    char_field = trim("s"//adjustl(char_field))
    write (unit, *) '@    '//trim(char_field)//' hidden false'
    write (unit, *) '@    '//trim(char_field)//' type xy'
    write (unit, *) '@    '//trim(char_field)//' symbol 0'
    write (unit, *) '@    '//trim(char_field)//' symbol size 1.000000'
    write (unit, *) '@    '//trim(char_field)//' symbol color '//trim(char_colour)
    write (unit, *) '@    '//trim(char_field)//' symbol pattern 1'
    write (unit, *) '@    '//trim(char_field)//' symbol fill color 2'
    write (unit, *) '@    '//trim(char_field)//' symbol fill pattern 0'
    write (unit, *) '@    '//trim(char_field)//' symbol linewidth 1.0'
    write (unit, *) '@    '//trim(char_field)//' symbol linestyle 1'
    write (unit, *) '@    '//trim(char_field)//' symbol char 65'
    write (unit, *) '@    '//trim(char_field)//' symbol char font 0'
    write (unit, *) '@    '//trim(char_field)//' symbol skip 0'
    write (unit, *) '@    '//trim(char_field)//' line type 1'
    write (unit, *) '@    '//trim(char_field)//' line linestyle 1'
    write (unit, *) '@    '//trim(char_field)//' line linewidth 2.0'
    write (unit, *) '@    '//trim(char_field)//' line color  '//trim(char_colour)
    write (unit, *) '@    '//trim(char_field)//' line pattern 1'
    write (unit, *) '@    '//trim(char_field)//' baseline type 0'
    write (unit, *) '@    '//trim(char_field)//' baseline off'
    write (unit, *) '@    '//trim(char_field)//' dropline off'
    write (unit, *) '@    '//trim(char_field)//' fill type 0'
    write (unit, *) '@    '//trim(char_field)//' fill rule 0'
    write (unit, *) '@    '//trim(char_field)//' fill color 1'
    write (unit, *) '@    '//trim(char_field)//' fill pattern 1'
    write (unit, *) '@    '//trim(char_field)//' avalue off'
    write (unit, *) '@    '//trim(char_field)//' avalue type 2'
    write (unit, *) '@    '//trim(char_field)//' avalue char size 1.000000'
    write (unit, *) '@    '//trim(char_field)//' avalue font 0'
    write (unit, *) '@    '//trim(char_field)//' avalue color 1'
    write (unit, *) '@    '//trim(char_field)//' avalue rot 0'
    write (unit, *) '@    '//trim(char_field)//' avalue format general'
    write (unit, *) '@    '//trim(char_field)//' avalue prec 3'
    write (unit, *) '@    '//trim(char_field)//' avalue prepend ""'
    write (unit, *) '@    '//trim(char_field)//' avalue append ""'
    write (unit, *) '@    '//trim(char_field)//' avalue offset 0.000000 , 0.000000'
    write (unit, *) '@    '//trim(char_field)//' errorbar on'
    write (unit, *) '@    '//trim(char_field)//' errorbar place both'
    write (unit, *) '@    '//trim(char_field)//' errorbar color 2'
    write (unit, *) '@    '//trim(char_field)//' errorbar pattern 1'
    write (unit, *) '@    '//trim(char_field)//' errorbar size 1.000000'
    write (unit, *) '@    '//trim(char_field)//' errorbar linewidth 1.0'
    write (unit, *) '@    '//trim(char_field)//' errorbar linestyle 1'
    write (unit, *) '@    '//trim(char_field)//' errorbar riser linewidth 1.0'
    write (unit, *) '@    '//trim(char_field)//' errorbar riser linestyle 1'
    write (unit, *) '@    '//trim(char_field)//' errorbar riser clip off'
    write (unit, *) '@    '//trim(char_field)//' errorbar riser clip length 0.100000'
    write (unit, *) '@    '//trim(char_field)//' legend "'//trim(legend)//'"'
    ! write(unit,*) trim(char_field)//" hidden false"
    ! write(unit,*) trim(char_field)//" type xy"
    ! write(unit,*) trim(char_field)//" symbol 9"
    ! write(unit,*) trim(char_field)//" symbol size 1.000000"
    ! write(unit,*) trim(char_field)//" symbol color "//trim(char_colour)
    ! write(unit,*) trim(char_field)//" symbol pattern 1"
    ! write(unit,*) trim(char_field)//" symbol fill color 4"
    ! write(unit,*) trim(char_field)//" symbol fill pattern 1"
    ! write(unit,*) trim(char_field)//" symbol linewidth 1.5"
    ! write(unit,*) trim(char_field)//" symbol linestyle 1"
    ! write(unit,*) trim(char_field)//" symbol char 65"
    ! write(unit,*) trim(char_field)//" symbol char font 0"
    ! write(unit,*) trim(char_field)//" symbol skip 0"
    ! write(unit,*) trim(char_field)//" line type 0"
    ! write(unit,*) trim(char_field)//" line linestyle 1"
    ! write(unit,*) trim(char_field)//" lyine linewidth 1.0"
!s0 legend  ""
!s0 avalue on
!s0 avalue type 4
!s0 avalue char size 0.80000
!s0 avalue font 4
!s0 avalue color 1
!s0 avalue rot 0
!s0 avalue format general
!s0 avalue prec 4
!s0 avalue prepend ""
!s0 avalue append ""
!s0 avalue offset 0.000000 , 0.01000
  end subroutine xmgu_data_header
Call graph
write_jdos_xmgrace calls xmgu_data_header
write_dos_xmgrace calls xmgu_data_header
write_jdos calls write_jdos_xmgrace
write_dos calls write_dos_xmgrace
jdos_calculate calls write_jdos
dos_calculate calls write_dos
optados calls jdos_calculate, dos_calculate