xmgu_setup – OptaDOS
xmgu_setup Subroutine
64 statements
Source File
public subroutine xmgu_setup(unit)
Uses
od_io
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
Calls
Called by
Contents
Source Code
xmgu_setup
Source Code
  subroutine xmgu_setup(unit)
    !==================================================================!
    use od_io, only: io_date
    implicit none
    integer, intent(in)      :: unit
    character(len=9) :: ctime             ! Temp. time string
    character(len=11):: cdate             ! Temp. date string
    call io_date(cdate, ctime)
    write (unit, *) '# Grace project file'
    write (unit, *) '# Autogenrated by OptaDOS on ', cdate, ' at ', ctime
    write (unit, *) '@version 50122'
    write (unit, *) '@page size 792, 612'
    write (unit, *) '@page scroll 5%'
    write (unit, *) '@page inout 5%'
    write (unit, *) '@link page off'
    write (unit, *) '@map font 0 to "Times-Roman", "Times-Roman"'
    write (unit, *) '@map font 1 to "Times-Italic", "Times-Italic"'
    write (unit, *) '@map font 2 to "Times-Bold", "Times-Bold"'
    write (unit, *) '@map font 3 to "Times-BoldItalic", "Times-BoldItalic"'
    write (unit, *) '@map font 4 to "Helvetica", "Helvetica"'
    write (unit, *) '@map font 5 to "Helvetica-Oblique", "Helvetica-Oblique"'
    write (unit, *) '@map font 6 to "Helvetica-Bold", "Helvetica-Bold"'
    write (unit, *) '@map font 7 to "Helvetica-BoldOblique", "Helvetica-BoldOblique"'
    write (unit, *) '@map font 8 to "Courier", "Courier"'
    write (unit, *) '@map font 9 to "Courier-Oblique", "Courier-Oblique"'
    write (unit, *) '@map font 10 to "Courier-Bold", "Courier-Bold"'
    write (unit, *) '@map font 11 to "Courier-BoldOblique", "Courier-BoldOblique"'
    write (unit, *) '@map font 12 to "Symbol", "Symbol"'
    write (unit, *) '@map font 13 to "ZapfDingbats", "ZapfDingbats"'
    write (unit, *) '@map color 0 to (255, 255, 255), "white"'
    write (unit, *) '@map color 1 to (0, 0, 0), "black"'
    write (unit, *) '@map color 2 to (255, 0, 0), "red"'
    write (unit, *) '@map color 3 to (0, 255, 0), "green"'
    write (unit, *) '@map color 4 to (0, 0, 255), "blue"'
    write (unit, *) '@map color 5 to (255, 255, 0), "yellow"'
    write (unit, *) '@map color 6 to (188, 143, 143), "brown"'
    write (unit, *) '@map color 7 to (220, 220, 220), "grey"'
    write (unit, *) '@map color 8 to (148, 0, 211), "violet"'
    write (unit, *) '@map color 9 to (0, 255, 255), "cyan"'
    write (unit, *) '@map color 10 to (255, 0, 255), "magenta"'
    write (unit, *) '@map color 11 to (255, 165, 0), "orange"'
    write (unit, *) '@map color 12 to (114, 33, 188), "indigo"'
    write (unit, *) '@map color 13 to (103, 7, 72), "maroon"'
    write (unit, *) '@map color 14 to (64, 224, 208), "turquoise"'
    write (unit, *) '@default linewidth 1.0'
    write (unit, *) '@default linestyle 1'
    write (unit, *) '@default color 1'
    write (unit, *) '@default pattern 1'
    write (unit, *) '@default font 0'
    write (unit, *) '@default char size 1.000000'
    write (unit, *) '@default symbol size 1.000000'
    write (unit, *) '@default sformat "%.8g"'
    write (unit, *) '@background color 0'
    write (unit, *) '@page background fill on'
    write (unit, *) '@g0 on'
    write (unit, *) '@g0 hidden false'
    write (unit, *) '@g0 type XY'
    write (unit, *) '@g0 stacked false'
    write (unit, *) '@g0 bar hgap 0.000000'
    write (unit, *) '@g0 fixedpoint off'
    write (unit, *) '@g0 fixedpoint type 0'
    write (unit, *) '@g0 fixedpoint xy 0.000000, 0.000000'
    write (unit, *) '@g0 fixedpoint format general general'
    write (unit, *) '@g0 fixedpoint prec 6, 6'
!     write(unit,*) 'autoscale'
!     write(unit,*) 'world xmin 0.0'
!     write(unit,*) 'world xmax 1.0'
    !    write(unit,*) 'world ymax 0.1'
    !    write(unit,*) 'frame linestyle 1'
    !   write(unit,*) 'frame linewidth 2.5'
    !   write(unit,*) 'frame color 1'
    !   write(unit,*) 'frame pattern 1'
    !   write(unit,*) 'frame background color 0'
    !   write(unit,*) 'frame background pattern 0'
    !   write(unit,*) 'altxaxis  off'
    !   write(unit,*) 'altyaxis  off'
  end subroutine xmgu_setup
Call graph
xmgu_setup calls io_date
write_jdos_xmgrace calls xmgu_setup
write_dos_xmgrace calls xmgu_setup
write_jdos calls write_jdos_xmgrace
write_dos calls write_dos_xmgrace
jdos_calculate calls write_jdos
dos_calculate calls write_dos
optados calls jdos_calculate, dos_calculate