comms_reduce – OptaDOS
comms_reduce Interface
5 statements
Source File
public interface comms_reduce
Called by
Contents
Module Procedures
comms_reduce_int comms_reduce_real comms_reduce_cmplx
Module Procedures
private subroutine comms_reduce_int(array, size, op)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: array
integer, intent(in) :: size
character(len=*), intent(in) :: op
private subroutine comms_reduce_real(array, size, op)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: array
integer, intent(in) :: size
character(len=*), intent(in) :: op
private subroutine comms_reduce_cmplx(array, size, op)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(inout) :: array
integer, intent(in) :: size
character(len=*), intent(in) :: op
Call graph
dos_utils_merge calls comms_reduce
jdos_utils_merge calls comms_reduce
dos_utils_set_efermi calls comms_reduce, dos_utils_calculate
setup_energy_scale calls comms_reduce
dos_utils_compute_band_energies calls comms_reduce
elec_read_foptical_mat calls comms_reduce
dos_utils_calculate calls dos_utils_merge
jdos_utils_calculate calls jdos_utils_merge, dos_utils_set_efermi, setup_energy_scale
optics_calculate calls dos_utils_set_efermi, jdos_utils_calculate
dos_calculate calls dos_utils_set_efermi, dos_utils_compute_band_energies, dos_utils_calculate
pdos_calculate calls dos_utils_set_efermi, dos_utils_calculate
core_calculate calls dos_utils_set_efermi, dos_utils_calculate
read_fem_bin calls elec_read_foptical_mat
jdos_calculate calls jdos_utils_calculate
od2od calls read_fem_bin
optados calls optics_calculate, dos_calculate, pdos_calculate, core_calculate, jdos_calculate