comms_bcast – OptaDOS
comms_bcast Interface
7 statements
Source File
public interface comms_bcast
Called by
Contents
Module Procedures
comms_bcast_int comms_bcast_logical comms_bcast_real comms_bcast_cmplx comms_bcast_char
Module Procedures
private subroutine comms_bcast_int(array, size)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: array
integer, intent(in) :: size
private subroutine comms_bcast_logical(array, size)
Arguments
Type Intent Optional Attributes Name
logical, intent(inout) :: array
integer, intent(in) :: size
private subroutine comms_bcast_real(array, size)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: array
integer, intent(in) :: size
private subroutine comms_bcast_cmplx(array, size)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(inout) :: array
integer, intent(in) :: size
private subroutine comms_bcast_char(array, size)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array
integer, intent(in) :: size
Call graph
elec_read_band_energy calls comms_bcast
elec_read_band_curvature calls comms_bcast
cell_get_symmetry calls comms_bcast
dos_utils_set_efermi calls comms_bcast, dos_utils_calculate
elec_pdos_read calls comms_bcast
elec_read_band_energy_ordered calls comms_bcast
setup_energy_scale calls comms_bcast
dos_utils_calculate calls comms_bcast, elec_read_band_gradient
elec_read_band_gradient calls comms_bcast
dos_utils_compute_dos_at_efermi calls comms_bcast, dos_utils_calculate_at_e
param_dist calls comms_bcast
elec_read_elnes_mat calls comms_bcast
elec_pdis_read calls comms_bcast
cell_dist calls comms_bcast
read_dome_bin calls elec_read_band_gradient
read_elnes_bin calls elec_read_elnes_mat
get_band_energy calls elec_read_band_energy
make_weights calls cell_get_symmetry
pdos_calculate calls dos_utils_set_efermi, elec_pdos_read, dos_utils_calculate
jdos_utils_calculate calls dos_utils_set_efermi, setup_energy_scale, elec_read_band_gradient
optados calls elec_read_band_energy, elec_read_band_energy_ordered, param_dist, cell_dist, pdos_calculate, optics_calculate, dos_calculate, core_calculate, pdis_calculate, jdos_calculate
optics_calculate calls dos_utils_set_efermi, make_weights, jdos_utils_calculate, dos_utils_calculate_at_e
dos_calculate calls dos_utils_set_efermi, dos_utils_calculate, dos_utils_compute_dos_at_efermi
core_calculate calls dos_utils_set_efermi, dos_utils_calculate, elec_read_elnes_mat
read_pdos_bin calls elec_pdos_read
dos_utils_calculate_at_e calls elec_read_band_gradient
pdis_calculate calls elec_pdis_read
od2od calls read_dome_bin, read_elnes_bin, get_band_energy, read_pdos_bin
jdos_calculate calls jdos_utils_calculate