comms_send – OptaDOS
comms_send Interface
7 statements
Source File
public interface comms_send
Called by
Contents
Module Procedures
comms_send_int comms_send_logical comms_send_real comms_send_cmplx comms_send_char
Module Procedures
private subroutine comms_send_int(array, size, to)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: array
integer, intent(in) :: size
integer, intent(in) :: to
private subroutine comms_send_logical(array, size, to)
Arguments
Type Intent Optional Attributes Name
logical, intent(inout) :: array
integer, intent(in) :: size
integer, intent(in) :: to
private subroutine comms_send_real(array, size, to)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: array
integer, intent(in) :: size
integer, intent(in) :: to
private subroutine comms_send_cmplx(array, size, to)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(inout) :: array
integer, intent(in) :: size
integer, intent(in) :: to
private subroutine comms_send_char(array, size, to)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array
integer, intent(in) :: size
integer, intent(in) :: to
Call graph
elec_pdos_read calls comms_send
elec_read_optical_mat calls comms_send
elec_read_band_energy calls comms_send
dos_utils_compute_bandgap calls comms_send
elec_read_band_gradient calls comms_send, elec_read_optical_mat
elec_read_elnes_mat calls comms_send
elec_read_foptical_mat calls comms_send
elec_read_band_curvature calls comms_send
elec_read_band_energy_ordered calls comms_send
core_calculate calls elec_read_elnes_mat, dos_utils_calculate, dos_utils_set_efermi
read_dome_bin calls elec_read_band_gradient
read_elnes_bin calls elec_read_elnes_mat
pdos_calculate calls elec_pdos_read, dos_utils_calculate, dos_utils_set_efermi
get_band_energy calls elec_read_band_energy
read_pdos_bin calls elec_pdos_read
read_ome_bin calls elec_read_optical_mat
optics_calculate calls elec_read_optical_mat, jdos_utils_calculate, dos_utils_calculate_at_e, dos_utils_set_efermi
optados calls elec_read_band_energy, elec_read_band_energy_ordered, core_calculate, pdos_calculate, optics_calculate, dos_calculate, jdos_calculate
dos_calculate calls dos_utils_compute_bandgap, dos_utils_calculate, dos_utils_set_efermi, dos_utils_compute_dos_at_efermi
dos_utils_calculate calls elec_read_band_gradient
jdos_utils_calculate calls elec_read_band_gradient, dos_utils_set_efermi
dos_utils_calculate_at_e calls elec_read_band_gradient
read_fem_bin calls elec_read_foptical_mat
od2od calls read_dome_bin, read_elnes_bin, get_band_energy, read_pdos_bin, read_ome_bin, read_fem_bin
jdos_calculate calls jdos_utils_calculate
dos_utils_set_efermi calls dos_utils_calculate
dos_utils_compute_dos_at_efermi calls dos_utils_calculate_at_e