od2od – OptaDOS
od2od Program
177 statements
Source File
Uses
od_comms
od_conv
od_io
od_constants
Program to convert checkpoint files from formatted to unformmated and vice versa - useful for switching between computers.
Plan is to use to convert outputs of other DFT programs to ones that OptaDOS can read.
AJM 2019
Calls
Contents
Variables
cdate ctime dome_conv dummy_conv elnes_conv fem_conv file_found ome_conv pdos_conv pos stat time0 time1
Source Code
od2od
Variables
Type Attributes Name Initial
character(len=11) :: cdate
Temp. date string
character(len=9) :: ctime
Temp. time string
logical :: dome_conv
Flags to stop people trying to, say, read in a pdos and write out an elnes. That's not going to end well.
logical :: dummy_conv
Flags to stop people trying to, say, read in a pdos and write out an elnes. That's not going to end well.
logical :: elnes_conv
Flags to stop people trying to, say, read in a pdos and write out an elnes. That's not going to end well.
logical :: fem_conv
Flags to stop people trying to, say, read in a pdos and write out an elnes. That's not going to end well.
logical :: file_found
logical :: ome_conv
Flags to stop people trying to, say, read in a pdos and write out an elnes. That's not going to end well.
logical :: pdos_conv
Flags to stop people trying to, say, read in a pdos and write out an elnes. That's not going to end well.
character(len=9) :: pos
Status and position of .odo file
character(len=9) :: stat
Position of .odo file
real(kind=dp) :: time0
Varaibles for measuring exectuion time.
real(kind=dp) :: time1
Varaibles for measuring exectuion time.
Source Code
program od2od
  !! Program to convert checkpoint files from formatted to unformmated
  !! and vice versa - useful for switching between computers.
  !!
  !! Plan is to use to convert outputs of other DFT programs to ones that
  !! OptaDOS can read.
  !!
  !! AJM 2019
  use od_constants, only: dp
  use od_io, only: io_file_unit, stdout, stderr, io_error, seedname, io_time, &
    & io_date
  use od_conv
  use od_comms, only: num_nodes, comms_setup, comms_end
  implicit none
  logical :: file_found
  logical :: ome_conv, fem_conv, dome_conv, pdos_conv, elnes_conv, dummy_conv
  !! Flags to stop people trying to, say, read in a pdos and write out an
  !! elnes. That's not going to end well.
  real(kind=dp) :: time0, time1
  !! Varaibles for measuring exectuion time.
  character(len=9) :: pos
  !! Status and position of .odo file
  character(len=9) :: stat
  !! Position of .odo file
  character(len=9) :: ctime
  !! Temp. time string
  character(len=11):: cdate
  !! Temp. date string
  time0 = io_time()
  iprint = 4
  call comms_setup
  call conv_get_seedname
  stderr = io_file_unit()
  open (unit=stderr, file=trim(seedname)//'.opt_err')
  call io_date(cdate, ctime)
  write (stderr, *) 'od2od: Execution started on ', cdate, ' at ', ctime
  stdout = io_file_unit()
  open (unit=stdout, file=trim(seedname)//'.log')
  !-------------------------------------------------------------------------!
  write (stdout, *)
  write (stdout, *) 'od2od: Execution started on ', cdate, ' at ', ctime
  write (stdout, *)
  write (stdout, *) "+============================================================================+ "
  write (stdout, *) "|                                                                            | "
  write (stdout, *) "|                         OO   DDD   222    OO   DDD                         | "
  write (stdout, *) "|                        O  O  D  D     2  O  O  D  D                        | "
  write (stdout, *) "|                        O  O  D  D   22   O  O  D  D                        | "
  write (stdout, *) "|                        O  O  D  D  2     O  O  D  D                        | "
  write (stdout, *) "|                         OO   DDD   2222   OO   DDD                         | "
  write (stdout, *) "|                                                                            | "
  write (stdout, *) "|                   For doing the odd thing to OptaDOS files                 | "
  write (stdout, *) "|                                                                            | "
  write (stdout, *) "|                      OptaDOS Developers Group 2019 (C)                     | "
  write (stdout, *) "|                             (But blame Andrew)                             | "
  write (stdout, *) "|                                                                            | "
  write (stdout, *) "+============================================================================+ "
  if (num_nodes /= 1) then
    call io_error('od2od can only be used in serial...')
  end if
  write (stdout, *)
  write (stdout, *) "+--------------------------------- JOB CONTROL ------------------------------+"
  write (stdout, '(a40,i5)') "Number of nodes : ", num_nodes
  write (stdout, '(a40,a)') "Convert from : ", trim(infile)
  write (stdout, '(a40,a)') "Convert to : ", trim(outfile)
  write (stdout, '(a40,a)') "Seedname : ", trim(seedname)
  write (stdout, '(a40,a)') "Output Seedname : ", trim(outseedname)
  write (stdout, *) "+----------------------------------------------------------------------------+"
  ome_conv = .false.
  fem_conv = .false.
  dome_conv = .false.
  pdos_conv = .false.
  elnes_conv = .false.
  dummy_conv = .false.
  ! Main case to decide what file format to read in.
  read_input:select case(trim(infile))
case ("ome_fmt")
  ome_conv = .true.
  call get_band_energy()
  call write_read_file()
  call read_ome_fmt()
case ("ome_bin")
  ome_conv = .true.
  call get_band_energy()
  call write_read_file()
  call read_ome_bin()
case ("fem_fmt")
  fem_conv = .true.
  call get_band_energy()
  call write_read_file()
  call read_fem_fmt()
case ("fem_bin")
  fem_conv = .true.
  call get_band_energy()
  call write_read_file()
  call read_fem_bin()
case ("dome_fmt")
  dome_conv = .true.
  call get_band_energy()
  call write_read_file()
  call read_dome_fmt()
case ("dome_bin")
  dome_conv = .true.
  call get_band_energy()
  call write_read_file()
  call read_dome_bin()
case ("pdos_fmt")
  pdos_conv = .true.
  call get_band_energy()
  call write_read_file()
  call read_pdos_fmt()
case ("pdos_bin")
  pdos_conv = .true.
  call get_band_energy()
  call write_read_file()
  call read_pdos_bin()
case ("elnes_fmt")
  elnes_conv = .true.
  call get_band_energy()
  call write_read_file()
  call read_elnes_fmt()
case ("elnes_bin")
  elnes_conv = .true.
  call get_band_energy()
  call write_read_file()
  call read_elnes_bin()
case ("dummy")
  dummy_conv = .true.
  call get_band_energy()
  call write_read_file()
  write (stdout, *) " Not reading any input file."
case default
  call io_error('Unknown Input File format speccified')
  end select read_input
  write (stdout, *) "+----------------------------------------------------------------------------+"
  write (stdout, *)
  write (stdout, *) "+------------------------------- Write File ---------------------------------+"
  ! Main case to decide what file format to write.
  write_output:select case(trim(outfile))
case ("ome_fmt")
  if (.not. (dome_conv .or. ome_conv)) call io_error(' Input format '//trim(infile)//' not compatible with output format '&
       &//trim(outfile))
  if (dome_conv) call pad_an_ome()
  call write_ome_fmt()
case ("ome_bin")
  if (.not. (dome_conv .or. ome_conv)) call io_error(' Input format '//trim(infile)//' not compatible with output format '&
       &//trim(outfile))
  if (dome_conv) call pad_an_ome()
  call write_ome_bin()
case ("fem_fmt")
  if (.not. (fem_conv)) call io_error(' Input format '//trim(infile)//' not compatible with output format '&
       &//trim(outfile))
  call write_fem_fmt()
case ("fem_bin")
  if (.not. (fem_conv)) call io_error(' Input format '//trim(infile)//' not compatible with output format '&
       &//trim(outfile))
  call write_fem_bin()
case ("dome_fmt")
  if (.not. (dome_conv .or. ome_conv)) call io_error(' Input format '//trim(infile)//&
       &' not compatible with output format '//trim(outfile))
  if (ome_conv) call slice_an_ome()
  call write_dome_fmt()
case ("dome_bin")
  if (.not. (dome_conv .or. ome_conv)) call io_error(' Input format '//trim(infile)//&
       &' not compatible with output format '//trim(outfile))
  if (ome_conv) call slice_an_ome()
  call write_dome_bin()
case ("pdos_fmt")
  if (.not. pdos_conv) call io_error(' Input format '//trim(infile)//' not compatible with output format '//trim(outfile))
  call write_pdos_fmt()
case ("pdos_bin")
  if (.not. pdos_conv) call io_error(' Input format '//trim(infile)//' not compatible with output format '//trim(outfile))
  call write_pdos_bin()
case ("elnes_fmt")
  if (.not. elnes_conv) call io_error(' Input format '//trim(infile)//' not compatible with output format '//trim(outfile))
  call write_elnes_fmt()
case ("elnes_bin")
  if (.not. elnes_conv) call io_error(' Input format '//trim(infile)//' not compatible with output format '//trim(outfile))
  call write_elnes_bin()
case ("dummy")
  write (stdout, *) " Not writing any output file."
  if (dummy_conv) then
    write (stdout, *)
    write (stdout, *) "                 Dummy in + dummy out  -- who's the dummy now ?"
  else
    write (stdout, *)
    write (stdout, *) "                No point in taking up disk space unnecessarily, eh ?"
  end if
case default
  call io_error('Unknown Output File format speccified')
  end select write_output
  call io_date(cdate, ctime)
  write (stdout, *) "+----------------------------------------------------------------------------+"
  time1 = io_time()
  write (stdout, '(1x,a40,f11.3,a)') 'Total runtime :', time1 - time0, ' (sec)'
  write (stdout, *)
  write (stdout, *) 'od2od: Execution complete on ', cdate, ' at ', ctime
  write (stdout, *)
  close (stdout)
  close (stderr, status='delete')
  call comms_end
!  close(unit=stdout,status='delete')
end program od2od
Call graph
od2od calls write_fem_bin, write_pdos_fmt, read_dome_bin, conv_get_seedname, read_elnes_bin, pad_an_ome, read_pdos_fmt, io_date, comms_setup, get_band_energy, comms_end, write_pdos_bin, read_pdos_bin, io_time, read_dome_fmt, io_file_unit, write_dome_fmt, slice_an_ome, io_error, write_read_file, read_ome_fmt, read_ome_bin, write_ome_bin, write_fem_fmt, read_fem_bin, write_dome_bin, write_elnes_bin, write_elnes_fmt, write_ome_fmt, read_elnes_fmt, read_fem_fmt
write_pdos_fmt calls io_file_unit
read_dome_bin calls elec_read_band_gradient
conv_get_seedname calls io_error, print_usage
read_elnes_bin calls elec_read_elnes_mat
read_pdos_fmt calls io_file_unit, io_error
get_band_energy calls report_arraysize, elec_read_band_energy
write_pdos_bin calls io_file_unit
read_pdos_bin calls elec_pdos_read
read_ome_bin calls elec_read_optical_mat
read_fem_bin calls elec_read_foptical_mat
write_elnes_bin calls io_file_unit, elec_elnes_find_channel_numbers
write_elnes_fmt calls io_file_unit, elec_elnes_find_channel_numbers
read_elnes_fmt calls io_file_unit, io_error, elec_elnes_find_channel_names
elec_read_band_gradient calls io_time, io_file_unit, io_error, elec_read_optical_mat, comms_bcast, comms_recv, algor_dist_array, comms_send, elec_dealloc_optical
elec_read_elnes_mat calls io_time, io_file_unit, io_error, elec_elnes_find_channel_names, comms_bcast, comms_recv, comms_send
elec_read_band_energy calls io_time, io_file_unit, io_error, comms_bcast, comms_recv, algor_dist_array, comms_send, cell_find_mp_grid
elec_pdos_read calls io_file_unit, io_error, comms_bcast, comms_recv, comms_send
elec_read_optical_mat calls io_time, io_file_unit, io_error, comms_recv, algor_dist_array, comms_send
elec_read_foptical_mat calls io_time, io_file_unit, io_error, comms_recv, algor_dist_array, comms_send, comms_reduce
elec_elnes_find_channel_numbers calls io_error, selectcase
elec_elnes_find_channel_names calls io_error
algor_dist_array calls io_error
elec_dealloc_optical calls io_error
cell_find_mp_grid calls io_error