optados – OptaDOS
optados Program
192 statements
Source File
Uses
od_pdis
od_jdos
od_parameters
od_build
od_pdos
od_dos
od_core
od_optics
od_photo
od_comms
od_constants
od_cell
od_electronic
od_io
Calls
Contents
Variables
cdate ctime filename odo_found pos stat time0 time1
Subroutines
help_output version_output
Source Code
optados
Variables
Type Attributes Name Initial
character(len=11) :: cdate
character(len=9) :: ctime
character(len=120) :: filename
logical :: odo_found
character(len=9) :: pos
character(len=9) :: stat
real(kind=dp) :: time0
real(kind=dp) :: time1
Subroutines
subroutine help_output()
Arguments
None
subroutine version_output()
Arguments
None
Source Code
program optados
  !=========================================================================!
  !                             O P T A D O S                               !
  !                      OPTics And Density Of States                       !
  !-------------------------------------------------------------------------!
  ! Key Internal Variables:                                                 !
  ! Described below.                                                        !
  !-------------------------------------------------------------------------!
  ! Necessary conditions:                                                   !
  !-------------------------------------------------------------------------!
  ! Written by Andrew Morris, Rebecca Nicholls, Chris Pickard               !
  !             and Jonathan Yates      2010                                !
  !=========================================================================!
  use od_comms, only: comms_setup, on_root, comms_end, num_nodes
  use od_constants, only: dp
  use od_io, only: io_get_seedname, io_time, io_date, io_file_unit,&! Functions
       & stdout, stderr, seedname, options, temp_dir                ! Variables
  use od_parameters, only: param_read, param_write_header, param_Dist, param_write, &
    param_dealloc, pdos, pdis, dos, jdos, core, optics, photo, iprint, param_write_atomic_coord, &
    devel_flag, photo_photon_energy, photo_model
  use od_cell, only: cell_calc_lattice, cell_report_parameters, cell_dist
  use od_electronic, only: elec_read_band_energy, elec_read_band_energy_ordered, elec_report_parameters
  use od_dos, only: dos_calculate
  use od_jdos, only: jdos_calculate
  use od_core, only: core_calculate
  use od_pdos, only: pdos_calculate
  use od_pdis, only: pdis_calculate
  use od_optics, only: optics_calculate
  use od_photo, only: photo_calculate
  use od_build, only: build_info
  implicit none
  real(kind=dp)    :: time0, time1       ! Variables for timing
  logical          :: odo_found         ! Ouptut file exists?
  character(len=9) :: stat, pos          ! Status and position of .odo file
  character(len=9) :: ctime             ! Temp. time string
  character(len=11):: cdate             ! Temp. date string
  character(len=120):: filename            ! Added by Felix Mildner, 03/23 for multi file output
  ! call sleep(25)
  time0 = io_time()
  call comms_setup
  if (on_root) then
    call io_get_seedname()
    ! If blank set to seedname='--help'
    if (trim(seedname) == '-h' .or. trim(seedname) == '--help') call help_output
    if (trim(seedname) == '-v' .or. trim(seedname) == '--version') call version_output
    !-------------------------------------------------------------------------!
    ! O R G A N I S E   T H E   E R R O R   F I L E
    stderr = io_file_unit()
    ! This is to allow multiple OptaDOS photoemission runs to be performed in the same directory.
    if ((index(options, '-temp') > 0)) then
      filename = trim(adjustl(temp_dir))//'/'//trim(seedname)//'.opt_err'
      open (unit=stderr, file=filename)
    else
      open (unit=stderr, file=trim(seedname)//'.opt_err')
    end if
    call io_date(cdate, ctime)
    write (stderr, *) 'OptaDOS: Execution started on ', cdate, ' at ', ctime
    !-------------------------------------------------------------------------!
    !-------------------------------------------------------------------------!
    ! O R G A N I S E   T H E   O U T P U T   F I L E  A N D
    ! R E A D   A N D   W R I T E   U S E R   P A R A M E T E R S
    call param_read()
    ! This is to allow multiple simultaneous OptaDOS photoemission runs to be performed in the same directory.
    if ((index(options, '-temp') /= 0)) then
      filename = trim(adjustl(temp_dir))//'/'//trim(seedname)//'.odo'
      inquire (file=filename, exist=odo_found)
    else
      inquire (file=trim(seedname)//'.odo', exist=odo_found)
    end if
    if (odo_found) then
      stat = 'old'
    else
      stat = 'replace'
    end if
    pos = 'append'
    stdout = io_file_unit()
    ! This is to allow multiple OptaDOS photoemission runs to be performed in the same directory.
    if ((index(options, '-temp') /= 0)) then
      open (unit=stdout, file=filename, status=trim(stat), position=trim(pos))
    else
      open (unit=stdout, file=trim(seedname)//'.odo', status=trim(stat), position=trim(pos))
    end if
    write (stdout, *) 'OptaDOS: Execution started on ', cdate, ' at ', ctime
    write (stdout, '(1x,a26,i5,a10)') 'Parallelised over', num_nodes, ' thread(s)'
    if (iprint > 0) call param_write_header()
    if (iprint > 0) call param_write()
    time1 = io_time()
    if (iprint > 1) write (stdout, '(1x,a40,f11.3,a)') 'Time to read parameters ', time1 - time0, ' (sec)'
    !-------------------------------------------------------------------------!
  end if
  if (pdis) then
    call elec_read_band_energy_ordered
  else
    call elec_read_band_energy
  end if
  if (on_root) then
    call cell_calc_lattice
    if (iprint > 0) call param_write_atomic_coord
    if (iprint > 0) call cell_report_parameters
    if (iprint > 0) call elec_report_parameters
  end if
  ! now send the data from the parameter file to each node
  call param_dist
  call cell_dist
  !-------------------------------------------------------------------------!
  ! C A L L   P D O S   R O U T I N E S
  if (pdos) then
    time0 = io_time()
    call pdos_calculate
    time1 = io_time()
    if (on_root) then
      write (stdout, '(1x,a59,f11.3,a8)') &
           '+ Time to calculate Projected Density of States          &
           &      ', time1 - time0, ' (sec) +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, *) ' '
      write (stdout, *) ' '
    end if
  end if
  !-------------------------------------------------------------------------!
  !-------------------------------------------------------------------------!
  ! C A L L   P D I S   R O U T I N E S
  if (pdis) then
    time0 = io_time()
    call pdis_calculate
    time1 = io_time()
    if (on_root) then
      write (stdout, '(1x,a59,f11.3,a8)') &
           '+ Time to calculate Projected Dispersion &
           &      ', time1 - time0, ' (sec) +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, *) ' '
      write (stdout, *) ' '
    end if
  end if
  !-------------------------------------------------------------------------!
  !-------------------------------------------------------------------------!
  ! C A L L   C O R E   R O U T I N E S
  if (core) then
    time0 = io_time()
    call core_calculate
    time1 = io_time()
    if (on_root) then
      write (stdout, '(1x,a78)') '|                                                                            |'
      write (stdout, '(1x,a59,f11.3,a8)') &
                       '+ Time to calculate Core Level Spectra       &
                       &                  ', time1 - time0, ' (sec) +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, *) ' '
      write (stdout, *) ' '
    end if
  end if
  !-------------------------------------------------------------------------!
  !-------------------------------------------------------------------------!
  ! C A L L   D O S  R O U T I N E S
  if (dos) then
    time0 = io_time()
    call dos_calculate
    time1 = io_time()
    if (on_root) then
      write (stdout, '(1x,a59,f11.3,a8)') &
                       '+ Time to calculate Density of States        &
                       &                  ', time1 - time0, ' (sec) +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, *) ' '
      write (stdout, *) ' '
    end if
  end if
  !-------------------------------------------------------------------------!
  !-------------------------------------------------------------------------!
  ! C A L L   O P T I C S   R O U T I N E S
  if (optics) then
    time0 = io_time()
    call optics_calculate
    time1 = io_time()
    if (on_root) then
      write (stdout, '(1x,a78)') '|                                                                            |'
      write (stdout, '(1x,a59,f11.3,a8)') &
        '+ Time to calculate Optical properties                         ', time1 - time0, ' (sec) +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, *) ' '
      write (stdout, *) ' '
    end if
  end if
  !-------------------------------------------------------------------------!
  !-------------------------------------------------------------------------!
  ! C A L L   P H O T O E M I S S I O N   R O U T I N E S
  if (photo) then
    time0 = io_time()
    call photo_calculate
    time1 = io_time()
    if (on_root) then
      write (stdout, '(1x,a78)') '|                                                                            |'
      write (stdout, '(1x,a59,f11.3,a8)') &
        '+ Time to calculate Photoemission                              ', time1 - time0, ' (sec) +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, *) ' '
      write (stdout, *) ' '
    end if
  end if
  !-------------------------------------------------------------------------!
  !-------------------------------------------------------------------------!
  ! C A L L   J D O S   R O U T I N E S
  if (jdos) then
    time0 = io_time()
    call jdos_calculate
    time1 = io_time()
    if (on_root) then
      write (stdout, '(1x,a78)') '|                                                                            |'
      write (stdout, '(1x,a59,f11.3,a8)') &
        '+ Time to calculate Joint Density of States                    ', time1 - time0, ' (sec) +'
      write (stdout, '(1x,a78)') '+============================================================================+'
      write (stdout, *) ' '
      write (stdout, *) ' '
    end if
  end if
  !-------------------------------------------------------------------------!
  !-------------------------------------------------------------------------!
  ! F I N A L I S E
  call param_dealloc
  if (on_root) then
    call io_date(cdate, ctime)
    write (stdout, *)
    write (stdout, *) 'OptaDOS: Execution complete on ', cdate, ' at ', ctime
    close (stdout)
    close (stderr, status='delete')
  end if
  call comms_end
  !-------------------------------------------------------------------------!
contains
  subroutine help_output
    use od_constants, only: optados_version, copyright
    implicit none
    write (*, *)
    write (*, *) " OptaDOS version ", trim(build_info%build)
    write (*, *)
    write (*, *) " Andrew J. Morris, R. J. Nicholls, C. J. Pickard and J. R. Yates", trim(copyright)
    write (*, *) " Usage: optados <seedname>"
    write (*, *)
    stop
  end subroutine help_output
  subroutine version_output
    use od_build, only: build_info
    use od_constants, only: optados_version, copyright
    implicit none
    write (*, *)
    write (*, *) " OptaDOS version ", trim(build_info%build)
    write (*, *)
    write (*, *) " Andrew J. Morris, R. J. Nicholls, C. J. Pickard and J. R. Yates", trim(copyright)
    write (*, *) " Compiled with "//trim(build_info%compiler)//" on "//trim(build_info%compile_date)&
         & //" at "//trim(build_info%compile_time)//"."
    write (*, *) " Compile type: "//trim(build_info%build_type)//", "//trim(build_info%comms_arch)
    write (*, *) " From source "//trim(build_info%build)//" submitted on "//trim(build_info%source_date)&
         &//" at "//trim(build_info%source_time)//"."
    stop
  end subroutine version_output
end program optados
Call graph
optados calls jdos_calculate, param_dealloc, elec_report_parameters, comms_setup, param_dist, version_output, io_date, param_read, param_write, param_write_atomic_coord, io_file_unit, param_write_header, io_get_seedname, cell_report_parameters, dos_calculate, core_calculate, elec_read_band_energy_ordered, pdos_calculate, photo_calculate, optics_calculate, comms_end, cell_dist, elec_read_band_energy, cell_calc_lattice, io_time, pdis_calculate, help_output
jdos_calculate calls io_time, jdos_utils_calculate, write_jdos
param_dist calls io_error, comms_bcast
param_read calls io_error, cell_read_cell
dos_calculate calls io_time, dos_utils_compute_bandgap, write_dos, dos_utils_calculate, dos_utils_set_efermi, dos_utils_compute_dos_at_efermi, dos_utils_compute_band_energies
core_calculate calls elec_read_elnes_mat, dos_utils_calculate, dos_utils_set_efermi
elec_read_band_energy_ordered calls io_file_unit, io_time, cell_find_mp_grid, comms_recv, algor_dist_array, comms_send, io_error, comms_bcast
pdos_calculate calls projection_get_string, projection_analyse_orbitals, projection_merge, elec_pdos_read, dos_utils_calculate, dos_utils_set_efermi
optics_calculate calls write_epsilon, write_refract, write_loss_fn, jdos_utils_calculate, elec_dealloc_optical, dos_utils_calculate_at_e, calc_conduct, calc_reflect, calc_absorp, make_weights, write_conduct, write_absorp, calc_refract, dos_utils_set_efermi, elec_read_optical_mat, calc_epsilon_1, calc_loss_fn, write_reflect, calc_epsilon_2
cell_dist calls io_error, comms_bcast
elec_read_band_energy calls io_file_unit, io_time, cell_find_mp_grid, comms_recv, algor_dist_array, comms_send, io_error, comms_bcast
cell_calc_lattice calls cell_get_real_lattice
pdis_calculate calls projection_get_string, projection_analyse_orbitals, projection_merge, elec_pdis_read
write_epsilon calls io_file_unit
write_refract calls io_file_unit
write_loss_fn calls io_file_unit
cell_find_mp_grid calls io_error
projection_get_string calls io_error
algor_dist_array calls io_error
jdos_utils_calculate calls io_time, io_error, dos_utils_set_efermi, elec_read_band_gradient, jdos_utils_merge, setup_energy_scale, calculate_jdos
dos_utils_compute_bandgap calls io_time, comms_recv, comms_send, io_error
elec_read_elnes_mat calls io_file_unit, io_time, comms_recv, comms_send, io_error, comms_bcast, elec_elnes_find_channel_names
projection_analyse_orbitals calls io_error
projection_merge calls io_error
elec_dealloc_optical calls io_error
cell_get_real_lattice calls io_file_unit
dos_utils_calculate_at_e calls io_time, io_error, elec_read_band_gradient
make_weights calls io_error, cell_get_symmetry
write_conduct calls io_file_unit
write_absorp calls io_file_unit
write_dos calls io_date, io_file_unit, io_error, write_dos_xmgrace
elec_pdos_read calls io_file_unit, comms_recv, comms_send, io_error, comms_bcast
write_jdos calls io_date, io_file_unit, io_error, write_jdos_xmgrace
cell_read_cell calls io_file_unit, cell_get_real_lattice, io_error, utility_cart_to_frac, utility_lowercase, utility_frac_to_cart
dos_utils_calculate calls io_time, io_error, comms_bcast, dos_utils_merge, elec_read_band_gradient
dos_utils_set_efermi calls io_error, comms_bcast, dos_utils_calculate, comms_reduce
dos_utils_compute_dos_at_efermi calls io_time, dos_utils_calculate_at_e, comms_bcast
dos_utils_compute_band_energies calls io_time, comms_reduce
elec_pdis_read calls io_file_unit, io_error, comms_bcast
elec_read_optical_mat calls io_file_unit, io_time, comms_recv, algor_dist_array, comms_send, io_error
write_reflect calls io_file_unit
dos_utils_merge calls comms_reduce
elec_read_band_gradient calls io_file_unit, io_time, comms_recv, algor_dist_array, comms_send, elec_dealloc_optical, io_error, comms_bcast, elec_read_optical_mat
elec_elnes_find_channel_names calls io_error
jdos_utils_merge calls comms_reduce
setup_energy_scale calls io_error, comms_bcast, comms_reduce
calculate_jdos calls io_error, doslin, gaussian, allocate_jdos, doslin_sub_cell_corners
cell_get_symmetry calls io_file_unit, io_error, comms_bcast
write_dos_xmgrace calls io_file_unit, io_error, xmgu_legend, xmgu_setup, xmgu_title, xmgu_subtitle, xmgu_axis, xmgu_vertical_line, xmgu_data, xmgu_data_header
write_jdos_xmgrace calls io_file_unit, io_error, xmgu_legend, xmgu_setup, xmgu_title, xmgu_subtitle, xmgu_axis, xmgu_data, xmgu_data_header
allocate_jdos calls io_error
doslin_sub_cell_corners calls heap_sort
xmgu_setup calls io_date
xmgu_data calls io_error