name: Docs

on: push

defaults:
  run:
    working-directory: optados/ford

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        id: build
        uses: ResearchSoftwareActions/ford-build@v1.0
        with:
          project_file: ../../optados/ford/project.md
          output_dir: ../../optados/autod_doc
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: ${{ steps.build.outputs.out_dir }}
